### ISSUE TITLE
Peano numbers

### ISSUE THREAD

**Issue by rexim** [cqfn/eo#101]
@yegor256 Are you gonna go full OOP and define natural numbers (or any kind of numbers) in a Peano numerals style?

```yaml
type Nat:
  Nat add(Nat other)
  Nat mult(Nat other)

object zero as Nat:
  Nat add(Nat other):
    other

  Nat mult(Nat other):
    this

object succ as Nat:
  Nat @prev

  ctor(Nat prev):
    @prev = prev

  Nat add(Nat other):
    succ: @prev.add(other)

  Nat mult(Nat other):
    @prev.mult(other).add(other)

object SumOfXY:
  Nat @x
  Nat @y

  ctor():
    SumOfXY:
      succ: succ: succ: zero,
      succ: succ: succ: succ: succ: zero

  Nat sum():
    x.add(y)
    
cli:
  printed:
    SumOfXY.sum().asText

# Should print 8
```

It may not necessarily work exacly like that internally (because of performance reasons). It may be just a logical interface exposed to the user. Numeric literals can be aliases to `succ`-chains. For example, `3` is alias for `succ: succ: succ: zero`.

**Comment by pa9ey** [comment]
@rexim Why do think that Peano numbers would make things "full OOP"?

**Comment by yegor256** [comment]
@rexim I think that this "dot-notation" style is not really a "full OOP":

```
x.add(y)
```

It looks procedural to me. How about this instead:

```
add: x, y
```

Here we're creating a new object (a copy of `add`), which encapsulates `x` and `y` and behaves like a sum of them.

To make it possible we will have to let that `add` object have a direct access to the data encapsulated inside `x` and `y`, and I think it's OK. Check this out: http://www.yegor256.com/2016/12/20/can-objects-be-friends.html

What do you think?

**Comment by yegor256** [comment]
@rexim by the way, I haven't heard about [Peano numbers](https://en.wikipedia.org/wiki/Peano_axioms) before. Let me read and investigate more.

**Comment by rexim** [comment]
> `add: x, y`

Ah, yeah, I remember you proposed a similar idea with `max` object. :) Don't quite understand how friending can help here, because you don't reveal too much of the details. For example, what if we have nested adds:

```
add:
  add: x, y
  add: a, b
```

Should the adds disembowel each other recursively in that case?

Anyway, I don't care too much of concrete implementations. I'm sure you'll figure everything out in a good and elegant way. :) I was rather curious about your thoughts regarding Peano axioms. People love to implement them on the type level system of different languages and paradigms just to show that you don't need to hard-code too much in the core to have a simple arithmetic. :)

Feel free to close this issue/question if you feel it's irrelevant for eo.

Thanks.

**Comment by yegor256** [comment]
@rexim it is relevant, let's keep it open. My comment about "friending" was more of a side note. The real question here is about Peano numbers, not the implementation. Let's keep the discussion open, thanks.

**Comment by pa9ey** [comment]
I can remember watching a video where some guy (a functional programmer guys I think) implemented the church-encoding thing in objects just for the hell of it. It was very interesting. Not particularly practical of course but very interesting. I can't find it for life of me... :(

Anyway else know that video?

**Comment by pa9ey** [comment]
https://twitter.com/every_peano/status/819984173708484610

**Comment by yegor256** [comment]
@rexim I believe it's not valid anymore, since we don't have types in EO
