### ISSUE TITLE
Guidelines for mocking

### ISSUE THREAD

**Issue by pchmielowski** [cqfn/eo#113]
How can I write a test which verifies that tested class calls some method on fake object with correct parameters?

I'm thinking of refactoring `ProgramTest` and replace:

    program.save(new FileOutput(dir));
    // read Java file and check its content

with something similar to:

    program.save(fakeOutput);
    verify(fakeOutput).save(correctPath, correctContent);

AFAIK, @yegor256, you don't recommend using Mockito, however I don't know how to create [build-in fake object](http://www.yegor256.com/2014/09/23/built-in-fake-objects.html) which can verify parameters of called method.

**Comment by yegor256** [comment]
@pchmielowski just make it "mutable." That fake `output` will store everything in, say, `StringBuffer` and then will give everybody access to the stored data.

**Comment by pchmielowski** [comment]
So should I add the `saved()` method to `Output` interface or only to `FakeOutput` class?
IMO none of these solutions are clean (maybe second one is worse)...

**Comment by yegor256** [comment]
@nlchar we need to think about a mocking sample in our unit tests

**Comment by nlchar** [comment]
> @nlchar we need to think about a mocking sample in our unit tests

@yegor256 can you explain what you mean exactly? 

I added this to our backlog.

**Comment by yegor256** [comment]
@nlchar when we write a unit test, we may want to create a fake/mock object instead of a real one, and pass it as an argument to the object being tested. I suggest you read this: https://www.yegor256.com/2014/09/23/built-in-fake-objects.html

**Comment by yegor256** [comment]
@pchmielowski it seems that in current EO syntax mocking is no different from any other object construction, I'm closing this one

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#113` is not assigned, can't get performer
