### ISSUE TITLE
Default object value

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#117]
If we create new object, we always have to pass constructor arguments to save it into attributes:
```
object zero(0, "USD") as Money:
  Int @amount
  Text @currency
```
But do we really need to initialize any object?
I'm talking about objects like `equals`, `if`, `not`, `plus` etc. What is default value of them?

Confusing me examples:
```
not not
not equals
if equals plus minus
print if
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 very good comment. I would actually suggest to get rid of this syntax all together and make it mandatory for _all_ objects to have default no-args constructors. Thus, it will look like:

```
object zero as Money:
  Int @amount
  Text @currency
  ctor()
    zero:
      0, 
      "USD"
```

Make sense?

**Comment by pchmielowski** [comment]
But there are many kind of objects where is hard to find default values. 
For example it is very intuitive to create `zero` with default value of `0`, but how to determine default values for `user` object? `John Smith` or something? 
IMO it can confuse readers of the code: "Why John Smith"?

**Comment by pa9ey** [comment]
@yegor256 Just out of interest... Why did @0crat join in this discussion?

**Comment by yegor256** [comment]
@pa9ey it's a bot that is reminding project architect about new tasks showing up. It's in beta testing though: www.zerocracy.com

**Comment by yegor256** [comment]
@g4s8 we don't have ctors anymore

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/cqfn/eo/issues/117#issuecomment-276151552); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)
