### ISSUE TITLE
EO is missing from GitHub's programming languages list

### ISSUE THREAD

**Issue by alexpanov** [cqfn/eo#120]
GitHub maintains a list of programming languages developed on GitHub: https://github.com/showcases/programming-languages.

We need to be there.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@alexpanov good point, thanks! I've sent an email to GitHub support.

**Comment by nlchar** [comment]
I proposed adding the EO programming language to the list. Now it is in the end of the list.
So, maybe close? 
@yegor256

**Comment by nlchar** [comment]
@yegor256 maybe let's close the issue as it is resolved?

**Comment by yegor256** [comment]
@nlchar thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4a07447a-25ae-4dc9-b0d1-e99cf6d3ad97, thread: pool-1155-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#120, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4a07447a-25ae-4dc9-b0d1-e99cf6d3ad97, thread: pool-1158-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#120, Action: `created`

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
