### ISSUE TITLE
eo appears to include "if"

### ISSUE THREAD

**Issue by sharpobject** [cqfn/eo#123]
Hello,

It looks like the examples use `if` to branch, but the language should not include any flow control constructs such as `if`

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by pa9ey** [comment]
Hi @sharpobject! This is kind of true. But the README says "flow control statements" not "constructs". The `if`'s in the examples are objects, not statements.

**Comment by sharpobject** [comment]
Good to know! How can I create my own object that does conditional execution without using the `if` object?

**Comment by sharpobject** [comment]
Ok, I just wonder if there is a useful distinction between objects and statements when we're talking about objects that are impossible to implement in the language.

**Comment by pa9ey** [comment]
@sharpobject Ah, I see. In answer to your previous question then ("How can I create my own object that does conditional execution without using the `if` object?"): polymorphism I guess.

**Comment by LandonPowell** [comment]
@pa9ey 
Maybe he'd rather use something similar to LISP's 'cond'? 
Is there a possible answer or is the language just devoid of that feature?

**Comment by pa9ey** [comment]
@LandonPowell In one sense the language is devoid of all sorts of things at the moment. I'm not trying to give a final answer, just an answer in the current framework of expected things (and to the original questions). A `cond` object is an interesting idea. Although it's only a sort of expanded `if` isn't it?

But even if we had that I think I would still have to answer the original questions the same way. (I've only just seen @sharpobject's edits by the way.)

**Comment by pa9ey** [comment]
@sharpobject I may not be following the questioning very well, so forgive me if so. But `match` and `switch` seem to be things that would be saying something like "you tell me what type of object you are and I'll tell you (or someone else) what to do". This doesn't seem very "elegant" nor very object-y.

**Comment by stain** [comment]
Half the point of if is to branch execution, for instance to avoid infinite
recusion.

I think in EO we also want if to return a value as there is no other
immutable way to give back a result

If arguments to the if constructor are evaluated before calling the
constructor, then a regular if object would be of limited use (it would
revert to a choice object).

However if the if constructor takes two **functions** as arguments (if/else
branch) then it is all much easier. You may then need syntactic sugar
similar to Java's lambdas, or override two methods in the if interface
(more verbose, scoping repeatability issues), or pass two method objects
from arbitrary pre-existing objects (object2::method3)

If we go into lisp-land, then if is a Macro (does not evaluate it's
arguments, return new code block), which typically relies on cond macro as
a special construct.






24. feb. 2017 3:09 e.h. skrifaði "John Page" <notifications@github.com>:

**Comment by yegor256** [comment]
@sharpobject we don't have `if` anymore. Instead, the object `bool` has `if` child object for branching.
