### ISSUE TITLE
Java keywords collision

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#128]
We can name EO methods, object, attributes same as java keywords. Just look at [fibonacci example](https://github.com/yegor256/eo#examples):
```
Int int():
    if:
```
`if` and `int` are Java keywords here.
If we translate to Java this names as is, we won't be able to compile it into jar.
How to avoid this collision?

**Comment by alex-semenyuk** [comment]
Maybe obvious and simple to append an underscore when translate them. (int_)

**Comment by yegor256** [comment]
@g4s8 maybe we should just add `eo_` prefix to all of them, just like @alex-semenyuk suggested?

**Comment by g4s8** [comment]
@yegor256 yes, I think it would be acceptable. So we need to change java-classes compiler

**Comment by yegor256** [comment]
@g4s8 yes, correct.

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/eo/issues/128#issuecomment-320526587))

@yegor256 Job `gh:yegor256/eo#128` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+795](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/eo/issues/128#issuecomment-386854410))

@yegor256 The job [#128](https://github.com/yegor256/eo/issues/128) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-0
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), can't add this XML to 2 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1260544441">
   <created>2018-05-06T05:10:37.151Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:yegor256/xcop#20</param>
      <param name="repo">yegor256/xcop</param>
      <param name="issue">20</param>
      <param name="comment">386854470</param>
   </params>
   <token>github;yegor256/xcop;20;386854470</token>
   <author>yegor256</author>
</claim>

com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), can't add this XML to 2 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1260544441">
   <created>2018-05-06T05:10:37.151Z</created>
   <type>Request order start</type>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:yegor256/xcop#20</param>
      <param name="repo">yegor256/xcop</param>
      <param name="issue">20</param>
      <param name="comment">386854470</param>
   </params>
   <token>github;yegor256/xcop;20;386854470</token>
   <author>yegor256</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/eo#128, Action: created

**Comment by yegor256** [comment]
@g4s8 it's fixed, we translate EO words to Java with prefix `EO`, to avoid any collisions

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/cqfn/eo/issues/128#issuecomment-386854410))

@yegor256 Job `gh:cqfn/eo#128` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#128` is not assigned, can't get performer
