### ISSUE TITLE
Constructors is not need.

### ISSUE THREAD

**Issue by DronMDF** [cqfn/eo#130]
eolang assumes that objects are cloned from one another. This is a wrong. This is are not respectful for object. We are not clone our childrens! :)

Every new object should set self state and describe self behavior.

```
object alphabet as Book:
  // This is a initializations (like a ctor)
  Text @isbn = "978-1-51916-691-3"
  Text @title = "The Alphabet"
  Text asText():
    sprintf:
      "ISBN is %s, title is '%s'",
      @isbn,
      @title
```

Сloning - this is a code sharing technique.

Can we live without the code sharng?
How often is it really needed?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by mdbs99** [comment]
Using `clone` is like using a `class` because we don't need to initialize the state of each object writing the same code every time.

**Comment by g4s8** [comment]
Constructors can be used for decorating (see #114), not only for cloning.

**Comment by DronMDF** [comment]
@g4s8 Not need, use initialization of state.

We can not create a new object without specifying its state and behavior (at the moment).
Main question: How to inherit behavior?

```
object one decorates zero:
  ctor()  # secondary ctor
    one: 1
  ctor(num)  # secondary ctor
    one:  # call primary ctor
      zero:
        num 
  Text print:
    origin.asText() # here
```

What is zero? This is a object (we cannot construct it, object have self state), or this is a type?

**Comment by DronMDF** [comment]
I must open my point of view...

The creation of an object from other object is code sharing. This is a bad thing.
We say that we do not need classes, but it turns out that we need code sharing.

Why can not a type have behavior from the beginning?

Or it is worth to be more specific and the behavior of each object should be set at its creation.
And if so, then there is no need to describe a few constructors. Constructors is not need!

**Comment by yegor256** [comment]
@DronMDF the latest version of EO doesn't have constructors at all

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#130` is not assigned, can't get performer
