### ISSUE TITLE
Using javapoet to generate java files

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#132]
I've found some library: [square/javapoet](https://github.com/square/javapoet)
> JavaPoet is a Java API for generating .java source files.

I think it can be useful in this project. It will be much easier to generate java files with this api than with `String.format`.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by sergiofigueras** [comment]
I've used javapoet for a quite long time, it only have one issue: It can only generate, but never update anything. Does it make any difference for EO?

**Comment by yegor256** [comment]
@g4s8 good idea, let's do it!

**Comment by nlchar** [comment]
@yegor256 The proposition does not seem to be incorporated into the project (as I can assume from pom.xml's), so maybe close?

**Comment by yegor256** [comment]
@nlchar yes, right, we are using XSLT for generating Java code

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#132` is not assigned, can't get performer
