### ISSUE TITLE
Creating objects from their interfaces 

### ISSUE THREAD

**Issue by ixmanuel** [cqfn/eo#134]
I don't remember exactly how @yegor256 exposed the issue about using "new" in methods in EO1, but the idea is something like:

Use the new keyword only in constructors, but I think that the "new" keyword (or the creation of an object in a method) is not an issue. 

Imagine  (pseudocode):
```
class Employee {
  private final int id;

  // We could use a shorter word: join: Profile, Memory
  Employee(int id, assignments: Profile) {
    this.id = id;
  }

  public Profile profile() {
    return new Profile(id);
  } 
}

// Deployment
new Employee(5, assignments: EmployeeProfile);
// Testing
new Employee(5, assignments: TestProfile);

// Alternative keyword
new Employee(5, join: EmployeeProfile);
```

Thus, within the objects we will be working with abstractions (protocols, positions, interfaces) not with the real objects that respond to the contracts. The objects are hired for a "position" and thus it is a position assignment, but "join" is shorter.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ixmanuel the latest version of EO doesn't have types

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#134` is not assigned, can't get performer
