### ISSUE TITLE
Compile eo to intermediate language

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#147]
It's not so easy to translate EO directly to java. It will be more harder when we start to implement new features like decorators and others. Also now is possible to compile invalid java classes because we can not validate eo code.

I think it can be more flexible if we translate EO to some intermediate language and then compile it into java or something else. It can be an xml for example:
```java
object alphabet as Book:
  Text @isbn
  Text @title
  ctor()
    alphabet:
      "978-1-51916-691-3",
      "The Alphabet"
  ctor(String i, String t):
    @isbn = i
    @title = t
  Text asText():
    sprintf:
      "ISBN is %s, title is '%s'",
      @isbn,
      @title
```
translated to:
```xml
<object name="alphabet">
  <types>
    <type name="Book" />
  </types>
  <attributes>
    <attribute name="isbn">
        <type name="Text" />
    </attribute>
    <attribute name="title">
        <type name="Text" />
    </attribute>
  </attributes>
  <ctors>
    <ctor>
      <copy name="alphabet">
       <args>
          <scalar type="string">978-1-51916-691-3</scalar>
          <scalar type="string">The Alphabet</scalar>
        </args>
      </copy>
    </ctor>
  </ctors>
  <methods>
    <method name="asText">
        <type name="Text" />
        <copy name="sprintf">
          <args>
            <scalar type="string">ISBN is %s, title is '%s'</scalar>
            <attr name="isbn" />
            <attr name="title" />
          </args>
        </copy>
    </method>
  </methods>
</object>
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 totally agree! Moreover, we can generate Java through XSL. Let's do it.

**Comment by Fly-Style** [comment]
I have one question : why does not it compile to JVM bytecode?

**Comment by eugene-nikolaev** [comment]
@Fly-Style, #14

**Comment by nlchar** [comment]
@yegor256 I propose closing this issue since the idea @g4s8 proposed was successfully implemented and embedded into the EO translator.

**Comment by g4s8** [comment]
@nlchar sure, thanks
