### ISSUE TITLE
eo-core failed to parse plugin descriptor

### ISSUE THREAD

**Issue by simonjenga** [cqfn/eo#153]
While trying to compile this project, the following error occurs:

```
C:\javaworkspace\eo>mvn compile
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] eo-parent
[INFO] eo-compiler
[INFO] eo-maven-plugin
[INFO] eo-archetype
[INFO] eo-core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eo-parent 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ eo-parent ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (jcabi-build-number) @ eo-parent ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=7 HEAD"
[INFO] Working directory: C:\javaworkspace\eo
[INFO] Storing buildNumber: 231d9f3 at timestamp: 2018-12-11T12:47:54
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (jcabi-build-number) @ eo-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eo-compiler 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ eo-compiler ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (jcabi-build-number) @ eo-compiler ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (jcabi-build-number) @ eo-compiler ---
[INFO]
[INFO] --- antlr4-maven-plugin:4.5.3:antlr4 (jcabi-antlr4) @ eo-compiler ---
[INFO] No grammars to process
[INFO] ANTLR 4: Processing source directory C:\javaworkspace\eo\eo-compiler\src\main\antlr4
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ eo-compiler ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ eo-compiler ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 40 source files to C:\javaworkspace\eo\eo-compiler\target\classes
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eo-maven-plugin 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ eo-maven-plugin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (jcabi-build-number) @ eo-maven-plugin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (jcabi-build-number) @ eo-maven-plugin ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ eo-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\javaworkspace\eo\eo-maven-plugin\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ eo-maven-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\javaworkspace\eo\eo-maven-plugin\target\classes
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (compile-helpmojo) @ eo-maven-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eo-archetype 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ eo-archetype ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (jcabi-build-number) @ eo-archetype ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (jcabi-build-number) @ eo-archetype ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ eo-archetype ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ eo-archetype ---
[INFO] No sources to compile
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eo-core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] eo-parent .......................................... SUCCESS [  9.765 s]
[INFO] eo-compiler ........................................ SUCCESS [ 20.982 s]
[INFO] eo-maven-plugin .................................... SUCCESS [  9.501 s]
[INFO] eo-archetype ....................................... SUCCESS [  0.125 s]
[INFO] eo-core ............................................ FAILURE [  0.031 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.302 s
[INFO] Finished at: 2018-12-11T12:48:25
[INFO] Final Memory: 26M/628M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to parse plugin descriptor for org.eolang:eo-maven-plugin:1.0-SNAPSHOT (C:\javaworkspace\eo\eo-maven-plugin\target\classes): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException
C:\javaworkspace\eo>



```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@simonjenga[/z](https://www.0crat.com/u/simonjenga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by simonjenga** [comment]
@0crat OK

**Comment by 0crat** [comment]
> @0crat OK ([here](https://github.com/yegor256/eo/issues/153#issuecomment-453548545))

@simonjenga Can't understand "OK", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by simonjenga** [comment]
@0crat ```hello```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#153](https://github.com/yegor256/eo/issues/153); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@simonjenga this is not valid anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4a07447a-25ae-4dc9-b0d1-e99cf6d3ad97, thread: pool-1155-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#153, Comment: 453548545

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4a07447a-25ae-4dc9-b0d1-e99cf6d3ad97, thread: pool-1158-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#153, Comment: 453552045

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/cqfn/eo/issues/153#issuecomment-453553800); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)
