### ISSUE TITLE
Consider to reject AOP

### ISSUE THREAD

**Issue by aivinog1** [cqfn/eo#154]
AOP is a terrible idea, that makes code very unpredictable. This should be rejected.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 we agree, rejected

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#154` is not assigned, can't get performer
