### ISSUE TITLE
How to compile and run Eolang programms (e.g. Hello World)

### ISSUE THREAD

**Issue by GeekNickson** [cqfn/eo#166]
I've just downloaded the repository and I'm unable to find the information on developing programs in Eolang.

**Comment by nlchar** [comment]
@GeekNickson You can run an example program that is located in the `sandbox` directory of the `root` directory of the repository. 
To do it, you can run in the `sandbox` directory this command:  
`mvn compile && ./run.sh 3`  
`3` here is the parameter that you pass to the program (so, here it mean 'find and print the 3rd Fibonacci number').  
I am working on more examples and on references on the eo language and eo library.  
[Here ](https://github.com/nlchar/eo/tree/nlchar-docs#the-eo-programming-language-standard-library)you can the current WIP version.

**Comment by nlchar** [comment]
@yegor256 I propose closing the issue since it is resolved.

**Comment by GeekNickson** [comment]
Thanks

**Comment by nlchar** [comment]
@GeekNickson could you close the issue, please?

**Comment by GeekNickson** [comment]
@nlchar yep

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#166` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
