### ISSUE TITLE
Finishing the project migration 

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#178]
@yegor256  please, consider these options for the organization:
1. eo-lang
2. eo-project
Or also cqfn as it is now. 

After that some changes to the pom.xml are to be made: 
```xml
<issueManagement>
    <system>GitHub</system>
    <url>https://github.com/yegor256/eo/issues</url>
</issueManagement>
<scm>
  <connection>scm:git:git@github.com:yegor256/eo.git</connection>
  <developerConnection>scm:git:git@github.com:yegor256/eo.git</developerConnection>
  <url>https://github.com/yegor256/eo</url>
</scm>
<distributionManagement>
  <site>
    <id>github-pages</id>
    <url>https://github.com/yegor256/eo</url>
  </site>
</distributionManagement>
```

**Comment by yegor256** [comment]
@nlchar let's stay here for a while, in @cqfn

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#178](https://github.com/cqfn/eo/issues/178); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
