### ISSUE TITLE
[bug] Wrong float constants parsing

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#186]
`float` constant parsing is performed wrong.  
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%%.9f\n"
      9999999999.0000012

```
Here, the `9999999999.0000012` is parsed as `1.0E10`:
**target/parse/app.eo.xml**
```xml

<objects>
    <o line="5" name="app">
       <o line="5" name="args" vararg=""/>
       <o base="stdout" line="6" name="@">
          <o base="sprintf" line="7">
             <o base="string" data="string" line="8">%%.9f\n</o>
             <o base="float" data="float" line="9">1.0E10</o>
          </o>
       </o>
    </o>
</objects>
```

**Comment by nlchar** [comment]
Even more interesting case.  
`999777777799999.0000012` is parsed as `9.9977779E14` (which is `999777790000000.000000000`).

**Comment by yegor256** [comment]
@nlchar the error is in this line: https://github.com/cqfn/eo/blob/master/eo-parser/src/main/java/org/eolang/parser/XeListener.java#L315 I'm sure you can try to fix it :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#186](https://github.com/cqfn/eo/issues/186); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#186` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
