### ISSUE TITLE
Example: HTTP call

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#187]
I think some real world examples are missed, e.g. how to call HTTP endpoint (eo programm as a client) and write content to file if response status is 200 or print content and headers to stderr in case of response error.

**Comment by yegor256** [comment]
@g4s8 we'll do it here: https://github.com/yegor256/objectionary/issues/7

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#187` is not assigned, can't get performer
