### ISSUE TITLE
Example: batch file reading with a consumer

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#188]
Please add an example of how to read huge file into some buffer and reduce these buffers into some consumer (e.g. hahs-sum calculator), similar to reactive approach (avoid loading all data into memory).

In Java it could be similar to:
```java
MessageDigest sha1 = MessageDigest.getInstance("SHA-1");
// read 10Gb file by 8Kb buffers and update sha digest with each buffer
new File(Path.of("/tmp/big-file")).read(buffer -> sha1.update(buffer));
return sha.digest();
```

**Comment by yegor256** [comment]
@g4s8 we already have it here: https://github.com/yegor256/eo-files

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#188` is not assigned, can't get performer
