### ISSUE TITLE
[bug] Missing implementation for the char data type

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#191]
The compiler recognized these data-types, however, the eo-runtime does not have the corresponding objects for them. Hence, the following errors are produced on compilation.
And for `char`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quick-start: Compilation failure: Compilation failure: 
[ERROR] /home/nlchar/sandbox/target/generated-sources/eo/EOapp.java:[30,39] cannot find symbol
[ERROR]   symbol:   class EOchar
[ERROR]   location: package org.eolang
[ERROR] /home/nlchar/sandbox/target/generated-sources/eo/EOapp.java:[32,68] cannot find symbol
[ERROR]   symbol:   variable a
[ERROR]   location: class sandbox.EOapp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
***The syntax for `char`:***

![CHAR](https://user-images.githubusercontent.com/64870515/105915785-2aac2e80-6041-11eb-9e22-70e9aeae9ac8.png)
  
**EBNF:**
```EBNF
CHAR     ::= "'" [0-9a-zA-Z] "'"
```

**Comment by yegor256** [comment]
@nlchar good point, let's implement them

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#191` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
