### ISSUE TITLE
[bug] Wrong int.div implementation

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#192]
The current `int.div` attribute implementation is incorrect.  
```
# Divide this one by another int
  [x] > div
    mul (x.pow -1) > @
```
where `pow` is defined as:  
```java
/**
 * POW.
 *
 * @since 1.0
 */
public class EOint$EOpow extends PhDefault {

    public EOint$EOpow(final Phi parent) {
        super(parent);
        this.add("x", new AtFree());
        this.add("φ", new AtBound(new AtLambda(this, self -> new Data.ToPhi(
            (long) Math.pow(
                new Data.Take(self.attr("ρ").get()).take(Long.class),
                new Data.Take(self.attr("x").get()).take(Long.class)
            )
        ))));
    }

}
```
Hence, the assumption here is such that `a / x = a * x^(-1)` which is totally wrong in the integer domain (since `x^(-1) = 0` for all integers except `0` and `1`).  
**Example**  
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%d\n%d\n"
      2.pow -1
      2.div 2

```
**Running**  
```
IN$: ./run.sh
OUT>: 0
OUT>: 0
IN$: 
```  
The correct result here, surely, is `1`.  
It could be algebraically concluded, that the `a. div b`  works as described:  
1. `a` if `b = 1`  
2. product of `a` and the large int number (i.e. infinity) if `b = 0`
3. `0` if  `b != 0 && b != 1 `

**Comment by nlchar** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#floorDiv-long-long-

**Comment by yegor256** [comment]
@nlchar good point, let's fix

**Comment by nlchar** [comment]
Math.floorDiv(Long, Long)
@IngeniariusSoftware

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#192` is not assigned, can't get performer
