### ISSUE TITLE
[bug] wrong int.pow implementation

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#193]
### Problem
The `int.pow` attribute object implementation is wrong.  
For all `b < 0`, `0^b` should be undefined. For now, it is a large `int` number that corresponds to `(long) Double.POSITIVE_INFINITY` (`9223372036854775807`). This may be ok for `FPU` computations to return `+∞`. However, for integer computations returning `9223372036854775807` seems ambiguous. 
### Example  
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%d\n%d\n%d\n%d\n%d\n"
      0.pow 0
      0.pow -1
      0.pow -2
      0.pow -1000
      0.pow 1

```
#### Running
```
IN$: ./run.sh
OUT>: 1
OUT>: 9223372036854775807
OUT>: 9223372036854775807
OUT>: 9223372036854775807
OUT>: 0
IN$: 
```
#### Comment
`0^1 = 1` is correct  
`0^0 = 1` is okay, even though the opinions vary on this point ([link](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero)). 
`0^(-1), 0^(-2), 0^(-1000)` should be either `unfedined`, `+∞`, `zero division exception`, not `9223372036854775807`.

**Comment by yegor256** [comment]
@nlchar maybe you can submit a PR?

**Comment by nlchar** [comment]
> @nlchar maybe you can submit a PR?

I will fix all the bugs I submitted.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#193` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
