### ISSUE TITLE
[bug]: Unable to run the compiled Eolang code (windows)

### ISSUE THREAD

**Issue by jizzel** [cqfn/eo#198]
This is what I did:
1. git clone https://github.com/cqfn/eo.git
2. cd eo/sandbox
3. mvn compile
4. run.cmd (and also tried "run.cmd 3")

This is my console output:

java -cp "target/classes;target/eo-runtime.jar" org.eolang.phi.Main sandbox.app $1
Exception in thread "main" org.eolang.phi.Attr$Exception: Error at sandbox.EOapp#data
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.Data$Take.take(Data.java:122)
        at org.eolang.phi.Data$Take.take(Data.java:127)
        at org.eolang.phi.Main.exec(Main.java:70)
        at org.eolang.phi.Main.main(Main.java:52)
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "data" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 4 more

My system information:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\apache-maven-3.6.3\bin\..
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_211\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

An archive of my sandbox directory is attached here:
[sandbox.zip](https://github.com/cqfn/eo/files/5906227/sandbox.zip)

**Comment by nlchar** [comment]
This is due to your default Java platform encoding sat to `Cp1252`.
See `target/05-compile/app.eo.xml` in your `sandbox.zip`, line `#78`:  
```
this.add("φ", new AtBound(new AtOnce(new AtLambda(this, self -&gt; {
```
Now, see `target/generated-sources/eo/EOapp.java`, line `#22`:  
```
this.add("?", new AtBound(new AtOnce(new AtLambda(this, self -> {
```
Here, we can see the same line, but with the corrupted `φ` character. The reason is that your default Java platform encoding is set to `Cp1252`.  
The `φ` character is vital from the EO perspective, that's why the program crashes with the `data is absent` error.

**Comment by nlchar** [comment]
To solve the issue, I recommend that you set the `JAVA_TOOL_OPTIONS` environment variable to this value: `-Dfile.encoding=UTF8`.  
To do it, run in the windows command like this command: `set JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF8`

**Comment by nlchar** [comment]
> To solve the issue, I recommend that you set the `JAVA_TOOL_OPTIONS` environment variable to this value: `-Dfile.encoding=UTF8`.
> To do it, run in the windows command like this command: `set JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF8`

If this won't help, try setting this also: `set MAVEN_OPTS= -Dfile.encoding=UTF-8`

**Comment by jizzel** [comment]
Great! The problem is solved.
I had to modify the command slightly though to this: 
setx JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8

Now I am able to build and run the sandbox code successfully.

Thanks!

**Comment by yegor256** [comment]
@nlchar how about we add a checker into our Main.java class, which will throw an exception if the default encoding is wrong? Something similar to this: https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/web/TkApp.java#L86-L92

**Comment by nlchar** [comment]
> Great! The problem is solved.
> I had to modify the command slightly though to this:
> setx JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8
> 
> Now I am able to build and run the sandbox code successfully.
> 
> Thanks!


That's great! Did you use Windows PowerShell? A friend of mine faced the same problem. And we solved it using the plain old Windows Command Line.

**Comment by nlchar** [comment]
> @nlchar how about we add a checker into our Main.java class, which will throw an exception if the default encoding is wrong? Something similar to this: https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/web/TkApp.java#L86-L92

Ok. I'll try to do it.

**Comment by jizzel** [comment]
> > Great! The problem is solved.
> > I had to modify the command slightly though to this:
> > setx JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8
> > 
> > Now I am able to build and run the sandbox code successfully.
> > 
> > Thanks!
> 
> 
> That's great! Did you use Windows PowerShell? A friend of mine faced the same problem. And we solved it using the plain old Windows Command Line. 

I did not use PowerShell, I used cmd.

**Comment by nlchar** [comment]
@IngeniariusSoftware
as @jizzel said, the correct solution is to run `setx JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8` in Windows CMD instead of `set`. So, if you encounter the problem again, please, use the `setx` command.

**Comment by nlchar** [comment]
> > > Great! The problem is solved.
> > > I had to modify the command slightly though to this:
> > > setx JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8
> > > Now I am able to build and run the sandbox code successfully.
> > > Thanks!
> > 
> > 
> > That's great! Did you use Windows PowerShell? A friend of mine faced the same problem. And we solved it using the plain old Windows Command Line.
> 
> I did not use PowerShell, I used cmd.

Thank you for the information.

**Comment by nlchar** [comment]
@jizzel please close the issue as it is resolved.

**Comment by yegor256** [comment]
@nlchar I closed

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#198` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#198](https://github.com/cqfn/eo/issues/198); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
