### ISSUE TITLE
Unicode in identifiers

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#204]
Identifiers in EOLANG are very limited in their syntax now. We can only use English letters. The original paper says: "Attributes may have any Unicode symbols in their names, as long as they don’t start with a dot and don’t contain spaces or line breaks." Let's make sure this works.

**Comment by yegor256** [comment]
@nlchar interested in fixing?

**Comment by nlchar** [comment]
> @nlchar interested in fixing?

Yes. We'll try to cover it with @ingeniariussoftware

**Comment by nlchar** [comment]
The only issue is that 123 or 13.5 or "hello" or 'c' or any other syntax-specific things should not be identifiers.

**Comment by yegor256** [comment]
@nlchar they are not. I'm talking only about `NAME`: https://github.com/cqfn/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L243

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#204](https://github.com/cqfn/eo/issues/204); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
@yegor256 what about these names? They all fit the restrictions you listed, but these are parts of the EO syntax:
1. `@`
2. `^$@`
3. `[myFancyObjectNameWithBrackets]`
4. `43`
5. `>>>HELLOTHISISИМЯ<<<`
6. `"myname"`
7. `'n'`
8. `999.123`

**Comment by yegor256** [comment]
@nlchar you are right, my mistake. Let's go with this: "Attributes may have any Unicode symbols in their names, as long as they **start with a lowercase English letter** and don’t contain spaces or line breaks."

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#204](https://github.com/cqfn/eo/issues/204); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@nlchar[/z](https://www.0crat.com/u/nlchar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nlchar** [comment]
@yegor256 
fixed in f79eee28f657052b39bab2835b10198dd954c31d  
please, check and reopen if it is not fixed yet

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#204](https://github.com/cqfn/eo/issues/204); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
