### ISSUE TITLE
Missing implementation for the bytes data type

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#207]
The compiler recognized these data-types, however, the eo-runtime does not have the corresponding objects for them. Hence, the following errors are produced on compilation.
For `bytes`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quick-start: Compilation failure
[ERROR] /home/nlchar/sandbox/target/generated-sources/eo/EOapp.java:[30,39] cannot find symbol
[ERROR]   symbol:   class EObytes
[ERROR]   location: package org.eolang
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
***The syntax for `byte` and `bytes`:***
![BYTE](https://user-images.githubusercontent.com/64870515/105916008-6515cb80-6041-11eb-867f-5568f3e46c66.png)
![BYTES](https://user-images.githubusercontent.com/64870515/105916013-6646f880-6041-11eb-90dd-7fdeea56b509.png)

**EBNF:**
```EBNF
BYTE     ::= [0-9A-F] [0-9A-F] '-'
BYTES    ::= BYTE ( BYTE* [0-9A-F] [0-9A-F] )?
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#207](https://github.com/cqfn/eo/issues/207); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
Added to the backlog.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#207](https://github.com/cqfn/eo/issues/207); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@nlchar[/z](https://www.0crat.com/u/nlchar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@nlchar we have it already, for example:

```
01-FE-C5 > x
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#207](https://github.com/cqfn/eo/issues/207); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
