### ISSUE TITLE
let's rename "data" to something less visible

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#208]
Now we use "data" everywhere for datarization. If someone creates attribute `data` in his object, the process of datarization will break.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.16`

**Comment by 0crat** [comment]
Job was finished in 11 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
