### ISSUE TITLE
Syntactic sugar for decorating

### ISSUE THREAD

**Issue by MadridianFox** [cqfn/eo#21]
Perhaps this syntax will be more comfortable for wrapping object in many decorators?
Doesn't matter, which type of brackets will be used for grouping decorators. Important only the idea - decorator is an object, which wraps other object of same type and we can simplify our life, when we make object + decorators hierarchy flatter.
```java
// before
sliced(
    upperCased(
        reversed(
            string("hello world")
        )
    )
, 4)
// after
string("hello world")[
    reversed(),
    upperCased(),
    sliced(4)
]
// and decorator implementation
decorator sliced for string{
    int len;
    constructor(int len){
        this.len = len;
    }
    // string interface realization
    text(){
        // we can work with wrapped object via this.wrapped
    }
}
```

**Comment by 0x13a** [comment]
this doesn't look anymore as a decorator, seems more like a pipe or chain of responsibility which is not the same thing imho

**Comment by MadridianFox** [comment]
@0x13a not pipe. In result we will have object SlicedString, which has inside UpperCasedString object, which also has inside ReversedString...
And yes - it's like chain of responsibility, because it's chain of decorators, where every decorator does only his work and delegates other to inner object.
It's only sugar for more readable writing of chain of decorators.

**Comment by DronMDF** [comment]
About slice... 
What prevents the transfer object as an argument to create a method in the depths of the decorator.
```
object slice as String:
      ctor(String line, Int len):
             ...
object slice4 from slice:
       ctor(String line):
             slice(4)                    // We cannot inherit implementation?
string("hello world").decorate([reversed, upperCased, slice4])
```
and create decorated object inside

**Comment by g4s8** [comment]
@MadridianFox, @yegor256 
I want to suggest another way for decorating objects. It's decoration via constructors only.
E.g. if you have this two objects:
```
object bufferedOutputStream as OutputStream:
    ctor(OutputStream origin)
    write(? data):
        ...

object fileOutputStream as OutputStream:
    ctor(File file)
    write(? data):
        ...
```
and want to add bufferisation to file stream, you can decorate it in constructor:
```
object bufferedFileOutputStream decorates bufferedOutputStream:
    ctor(File file):
        bufferedOutputStream:
            fileOutputStream:
                file
```
This decorator object will be same as `bufferedOutputStream` (you cannot override methods), but provide new constructor for `File` argument, that wraps file into `fileOutputStream` object and pass it to `bufferedOutputStream` as constructor parameter.

I've seen this decorators many times in [Takes](https://github.com/yegor256/takes) ([e.g. this one](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/RqWithHeader.java)), and I like it.

**Comment by yegor256** [comment]
@MadridianFox we have a new syntax now, this suggestion I believe is not relevant anymore
