### ISSUE TITLE
direct access to parent object

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#211]
Let's make it possible to access parent object from abstract object.

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.17`

**Comment by 0crat** [comment]
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it
