### ISSUE TITLE
[enhancement] array.length

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#219]
Implement `array.length` that obtains the length of the base `array` object

**Comment by nlchar** [comment]
The assignee: @nlchar

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#219` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
