### ISSUE TITLE
objectionary.com

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#22]
I own this domain: [objectionary.com](http://www.objectionary.com/).  The idea was introduced by David West in his book "Object Thinking" ten years ago. The idea is that objects will stay in some "repository" and applications will use them. Objects, not libraries, artifacts, binaries. Maybe it's time to use this paradigm in EO?

**Comment by mdbs99** [comment]
Could you explain more this idea?
Is this something about the `Memory` object?

**Comment by yegor256** [comment]
@mdbs99 I'm not sure yet, but maybe just like that. We deploy objects there and we use them from there. Not JAR libraries, but `.eo` files. We will manage dependencies on the level of objects, not libraries. In the language I will say `import org.eolang.string` and the object will be retrieved from objectionary. Together with other objects it depends on.

**Comment by mdbs99** [comment]
I didn't understand the difference, in the code level, between dependencies from objects instead of libraries.
When you say `import org.eolang.string` for me it's mean `org.eolang` library.

**Comment by englishman** [comment]
@yegor256 is this `objectionary` is kind of `repository` or `factory`?

**Comment by yegor256** [comment]
@englishman both. David West says "object-dictionary-factory"

**Comment by mdbs99** [comment]
@yegor256 these objects will be shared, like a "conection pool"?

**Comment by amaembo** [comment]
Which version of `org.eolang.string` will be imported from objectionary?

**Comment by yegor256** [comment]
@amaembo good question. maybe we will use it like this:

```
import org.eolang.string:1.4.8
import org.eolang.if:1.3
```

We will specify versions per object.

**Comment by mdbs99** [comment]
@yegor256 I like the syntax, but I didn't understand which "version" do you're talking about.

**Comment by amaembo** [comment]
@yegor256 what if ten different classes in your project import ten different versions of `org.eolang.string`? Will you package all of them inside the resulting application? Also note that you will have problems with code generation (regardless whether you want to produce Java code or JVM bytecode): you will have to rename all these different versions to avoid possible clashes. While this might look like an implementation detail, the renamed class name could be visible in debugger, exception stack traces, etc.

**Comment by yegor256** [comment]
@amaembo what's about ten different objects with same name and different versions? Remember, they are objects, not classes. Yes, the stacktrace may look strange, but we can name them right. For example `org.eolang.string` will look like `org.eolang.string$1$4$8` in Java.

**Comment by amaembo** [comment]
@yegor256 another question: suppose that source file A (I'm trying my best to avoid the word "class") refers to `org.eolang.string:1.4.8` while source file B refers to `org.eolang.string:1.4.9`. Can the string object from file A be passed into file B and used there?

**Comment by MadridianFox** [comment]
Few weeks ago I thought exactly same thing. But I started from other side. Every object is a concept of ontological modeling. What is ontological modeling? It's process of describing concepts and relationships, and building a model in current domain. It as programming, isn't it?
People, who work with ontology, use repositories of concepts, for maximal reusing them. And repository operates not with domain or project, it works with every concept. It can supply separately one concept for your own schema by concept's url.

**Comment by martinstraus** [comment]
I like this idea very, very much! I'm pretty sure other languages have something similar, but I'm not an expert... What exactly would you be getting from the objectionary? The source code for an object's version? A compiled version?

**Comment by jachinte** [comment]
@MadridianFox, how do  they deal with different versions of the same concept, is that possible?

>  It can supply separately one concept for your own schema by concept's url.

**Comment by yegor256** [comment]
@amaembo I believe it's a problem of a compiler. Let's say, we represent objects as JVM static methods (I believe, that's how it will work). In that case `string:1.4.8` is one static method, while `string:1.4.9` is just another static method. No conflicts. In other words, I don't think we will use JVM objects at all, simply because they are not powerful enough.

**Comment by stain** [comment]
I guess published EO objects would depend on each-other kind of like how Docker images build on each-other - so you would have a particular version of the object. However its interfaces would also need to be versioned the same way.. so it will be a versioned dependency graph.

[Semantic versioning](http://semver.org/) can be calculated programmatically (at least in terms of API compatibility) - see for instance how [japicmp](http://stain.github.io/commons-rdf/0.3.0-RC2/commons-rdf-api/japicmp.html) checks each method.

**Comment by DronMDF** [comment]
I do not quite understand how we can publish a string object. Object should have state.
What is the state of the object `org.eolang.string:1.4.8`?

**Comment by stain** [comment]
It should be an empty string (length() = 0), a reasonable default, just
like an empty list is reasonable default for implementations of Collection
interface?

(It's constructor would allow deriving objects with other state, obviously)

**Comment by DronMDF** [comment]
if `org.eolang.string:1.4.8` have default value, we can use this value in code.
`If(Eq(hello, org.eolang.string:1.4.8), ...)`

This is like a static variable...

What is the default value for `If` or `Eq`

**Comment by stain** [comment]
Eq default should be false.
If default is tricky. Lacking generics and null, perhaps also false?



On 1 Apr 2017 8:28 pm, "Andrey Valyaev" <notifications@github.com> wrote:

if org.eolang.string:1.4.8 have default value, we can use this value in
code.
If(Eq(hello, org.eolang.string:1.4.8), ...)

This is like a static variable...

What is the default value for If or Eq

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/yegor256/eo/issues/22#issuecomment-290941814>, or mute
the thread

**Comment by yegor256** [comment]
We'll continue in #214

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#22` is not assigned, can't get performer
