### ISSUE TITLE
implement array.ctor to create array objects

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#221]
`array` constructor implementation is missing. Now we cannot create arrays without a special wrapping object, like here:
```
[elements...] > wrapper
  elements > @
```
Here, the `wrapper` object is used to implement the constructor behavior.

**Comment by nlchar** [comment]
The assignee: @nlchar

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by nlchar** [comment]
Failed to finish in the previous sprint. Moved to the current sprint.

**Comment by nlchar** [comment]
Implemented in #276 by Yegor.
The PR is closed since it is not relevant.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#221` is not assigned, can't get performer
