### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#223]
@yegor256 could you please make a release?
The `sandbox` directory uses the outdated version of EO.
How do we supply the latest version of EO into the `sandbox` directory, by the way? I mean, the lates version of `eo-maven-plugin` and `eo-runtime.jar`?

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.18`

**Comment by yegor256** [comment]
@nlchar done

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#223` is not assigned, can't get performer
