### ISSUE TITLE
[enhancement] implement float.neg

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#229]
`float.neg` should datarize to the negate value of its base `float` object

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#229` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
