### ISSUE TITLE
[enhancement] implement float.sub

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#230]
`float.sub` should datarize to the difference between its base `float` object and its `x` free attribute

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#230` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
