### ISSUE TITLE
implement float.abs

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#231]
`float.abs` should datarize to the absolute value of its base `float` object

**Comment by nlchar** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#abs-double-

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#231` is not assigned, can't get performer
