### ISSUE TITLE
[enhancement] implement float.pow

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#233]
`float.pow` should datarize to its base `float` object raised to the power of its `x` free attribute

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#233` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
