### ISSUE TITLE
implement float.signum

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#234]
`float.signum` should datarize to the sign of its base `float` object:  
1. +1.0 if `$` is positive.
2. 0.0 if `$` is zero.
3. -1.0 if `$` is negative.

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#234` is not assigned, can't get performer
