### ISSUE TITLE
[bug] wrong short-circuiting implementation in bool.and & bool.or

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#235]
The current implementation of short-circuiting in `bool.and` and `bool.or` is wrong. It should consider the `ρ` object first, not its application to the first element of the `x` vararg.  
This makes the datarization process of the `bool.and` and `bool.or` less efficient and conceptually wrong.

**Comment by nlchar** [comment]
@IngeniariusSoftware thanks for finding the bug

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#235` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#235](https://github.com/cqfn/eo/issues/235); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#235](https://github.com/cqfn/eo/issues/235); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/cqfn/eo/issues/235#issuecomment-780824579))

@yegor256 Job `gh:cqfn/eo#235` is not assigned, can't get performer
