### ISSUE TITLE
imlement float comparison attributes

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#241]
- [x] `float.less` should datarize to the result of the following comparison: `$ < x`, where `$` is the base `float` object of the `.less` attribute, and `x` is the free attribute of type `float` of the `.less` attribute  
- [x] `float.greater` should datarize to the result of the following comparison: `$ > x`, where `$` is the base `float` object of the `.greater` attribute, and `x` is the free attribute of type `float` of the `.greater` attribute  
- [x] `float.leq` should datarize to the result of the following comparison: `$ ≤ x`, where `$` is the base `float` object of the `.leq` attribute, and `x` is the free attribute of type `float` of the `.leq` attribute  
- [x] `float.geq` should datarize to the result of the following comparison: `$ ≥ x`, where `$` is the base `float` object of the `.geq` attribute, and `x` is the free attribute of type `float` of the `.geq` attribute    
- [x] `float.neq` should datarize to the result of the following comparison: `$ ≠ x`, where `$` is the base `float` object of the `.neq` attribute, and `x` is the free attribute of type `float` of the `.neq` attribute

**Comment by nlchar** [comment]
Added to the current sprint. The assignee: @IngeniariusSoftware

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#241` is not assigned, can't get performer
