### ISSUE TITLE
Possible Rultor Bug

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#242]
In #223, I asked @yegor256 to make a release. After the release was ordered and performed, two issues occurred: 
1.  Rultor named [the release](https://github.com/cqfn/eo/releases/tag/0.1.18) after the issue (i.e., `"Release"` instead of `0.1.18`). Maybe, it is not a bug, but for the future, we should consider naming release issues properly. 
2. Rultor [forgot](https://github.com/cqfn/eo/blob/38836ab3a6f33ffcd912c0124a20d34d8dda3ca7/sandbox/pom.xml#L31) to update the EO version in `sandbox/pom.xml`, so a manual update from `0.1.15` to `0.1.18` is needed.

**Comment by nlchar** [comment]
@yegor256 what do you think, Yegor? Is it a bug (especially, the second problem)?

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by yegor256** [comment]
@nlchar the first one is not a bug, it's a feature. The second one is also not really a bug, but we can automate it.
