### ISSUE TITLE
array.mapi implementation is broken: cannot use the index free attribute

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#243]
The `array.mapi` implementation is broken. One cannot access the `index` attribute inside the `map-function`, because of the incorrect data type conversion performed inside the language.

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#243](https://github.com/cqfn/eo/issues/243); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#243` is not assigned, can't get performer
