### ISSUE TITLE
Decoration mechanism does not work with memory

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#248]
Here is an example of a program that uses the decoration mechanism together with a `memory` object:  
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[a] > test
  a > @
  "string" > attr1
  123 > attr2


[] > app
  memory > m
  seq > @
    m.write (test 101)
    stdout
      sprintf
        "%s %s %s"
        m
        m.attr1
        m.attr2

```
It fails with the following error:  
```
Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.EOint#attr1
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault$AtChild.get(PhDefault.java:178)
        at org.eolang.phi.PhMethod.lambda$new$0(PhMethod.java:41)
        at org.eolang.phi.Data$Once.take(Data.java:58)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.Data$Take.take(Data.java:122)
        at org.eolang.txt.EOsprintf.lambda$new$0(EOsprintf.java:57)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 31 more
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "attr1" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 41 more
```
However, if we omit the `memory` object like this:  
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[a] > test
  a > @
  "string" > attr1
  123 > attr2


[] > app
  test 122 > m
  stdout > @
    sprintf
      "%s %s %s"
      m
      m.attr1
      m.attr2

```
The program works fine:  
```
122 string 123
```

**Comment by nlchar** [comment]
The source of the issue is that the object that we bind to the `x` attribute of the `memory.write` attribute is datarized before memorizing. Hence, the datarization result is stored inside `memory`, not the original object. https://github.com/cqfn/eo/blob/bed77fe2fa1d7d00e06b6a13378b2ca3fd0c02e2/eo-runtime/src/main/java/org/eolang/EOmemory.java#L66

**Comment by nlchar** [comment]
Added to the current sprint. The assignee: @IngeniariusSoftware

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
@yegor256 
In essence, the problem is that the `memory` object datarizes its inner object eagerly, not lazily (like in the rest of the library and the language). This results in the data being stored inside `memory`, not the object that we have put previously.  
However, evaluating the inner object inside the `memory` object also leads to another problem. That's why your tests fail in #251.  
Consider this simple test:
https://github.com/cqfn/eo/blob/3425275ce072e22bbdc9ace0a25fa09d101292f4/eo-runtime/src/test/eo/org/eolang/memory-tests.eo#L17  
```
[] > rewritesAndIncrementsItself
  memory > m
  and. > @
    m.write 1
    m.write (m.add 5)
    m.eq 6
```  
It fails with the following error: https://travis-ci.com/github/cqfn/eo/builds/218854057#L11372  
```
[ERROR]   EOrewritesAndIncrementsItselfTest>PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135->PhDefault.attr:135 » StackOverflow
```  
This may be caused by an idiomatic flaw in the language. So that's why I ask you to look at the error closely.

**Comment by yegor256** [comment]
@nlchar do you have an idea how to solve this?

**Comment by yegor256** [comment]
@nlchar my suggestion is this: `memory` is the place to store data, not objects. This is what it was designed for. It's not supposed to store objects, that's why its name is memory. Memory is the storage for data. Objects are not data :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#248](https://github.com/cqfn/eo/issues/248); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#248` is not assigned, can't get performer
