### ISSUE TITLE
imlement int comparison attributes

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#249]
- [x] `int.greater` should datarize to the result of the following comparison: `$ > x`, where `$` is the base `int` object of the `.greater` attribute, and `x` is the free attribute of type `int` of the `.greater` attribute  
- [x] `int.leq` should datarize to the result of the following comparison: `$ ≤ x`, where `$` is the base `int` object of the `.leq` attribute, and `x` is the free attribute of type `int` of the `.leq` attribute  
- [x] `int.geq` should datarize to the result of the following comparison: `$ ≥ x`, where `$` is the base `int` object of the `.geq` attribute, and `x` is the free attribute of type `int` of the `.geq` attribute  
- [x] `int.neq` should datarize to the result of the following comparison: `$ ≠ x`, where `$` is the base `int` object of the `.neq` attribute, and `x` is the free attribute of type `int` of the `.neq` attribute

**Comment by nlchar** [comment]
Added to the current sprint. The assignee: @IngeniariusSoftware

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#249` is not assigned, can't get performer
