### ISSUE TITLE
How to use the latest version of EO inside the sandbox

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#250]
@yegor256 can you explain how to use the latest version of the `eo-parser`, `eo-maven-plugin`, and `eo-runtime` inside the `sandbox` directory? I mean, how do we use the exact version that we have on the local machine in the parent `eo` directory to test new features and work with the latest cutting-edge objects that the `maven-central` version is missing?

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by yegor256** [comment]
@nlchar I believe this question is already answered, I'm closing
