### ISSUE TITLE
Implement org.eolang.io.stdin

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#252]
The `org.eolang.io.stdin` should datarize to the input the user typed into the CLI.

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by nlchar** [comment]
Moving to https://github.com/HSE-Eolang/eo

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#252` is not assigned, can't get performer
