### ISSUE TITLE
int.toFloat

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#254]
The `int.toFloat` attribute should datarize to the `float` object made up of the base `int` object.

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#254` is not assigned, can't get performer
