### ISSUE TITLE
string.match for regular expression usage

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#256]
Let's add reg exps to EO

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.20`

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#256](https://github.com/cqfn/eo/issues/256); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
