### ISSUE TITLE
inline anonymous abstract objects

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#266]
Let's make it possible to write abstract objects in line, for example:

```
[x] /a-z/.matches x
```

is the same as

```
[x]
  /a-z/.matches x > @
```

**Comment by nlchar** [comment]
Good issue. Thought of it many times.

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.22`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#266` is not assigned, can't get performer
