### ISSUE TITLE
The new constructor/method call syntax

### ISSUE THREAD

**Issue by gukoff** [cqfn/eo#27]
Imagine that a method call doesn't consist of a method name and a list of its arguments. On the contrary, it looks more like a natural language sentence, is more agile and readable, but still well structured. Does it sound interesting?

In order to get closer to this idea, I like to use named arguments, i.e `match(text='abcd', regex='\w+')` instead of `match('abcd', '\w+')`. Particularly, it makes a lot of sense in case of deeply nested constructions, where an order of method arguments gets non-obvious and simply unshapely because of a cumbersome structure:
```
match(
  stripped_text(
    file(
      file_path(
        ['tmp', 'xxx.txt']
      ),
      'r'
    )
  ),
  '10$'
)
```
Here, one wouldn't so easily understand, what's going on. Really, what do these `'r'` and `'10$'` mean? They are already out of context. Here, named arguments would come in very handy.

Let's get back to the first example: `match(text='abcd', regex='\w+')` vs `match('abcd', '\w+')`. The need to use named arguments here is much more controversial. They are still useful in case one mixes up an order of arguments, but make the code twice as verbose.

What would be the compromise?

I suggest to make argument naming **required** and eliminate the difference between a **method name** and **argument names**.

Simply put, I'd change `match('w+', 'abcd')` to `match: '\w+' text: 'abcd'`. Makes sense? 

Take a look at our current code outline: 
```
create fibonacci(1) as Number:
  Number n
  bytes asBytes():
    if:
      lessThan: @n, 2
      1,
      plus:
        @n
        fibonacci:
          minus: @n, 1
```
Indeed, as we got rid of the brackets, it isn't verbose at all. But the readability suffers just like in the example above. I believe, if the `if` had more code inside, it wouldn't be readable anymore.

What about something like this? 
```
create fibonacci(1) as Number:
  Number n
  bytes asBytes():
    if:
      less: @n than: 2
    then:
      1
    else:  
      plus:
        @n
      and:
        fibonacci:
            minus: @n and: 1
```

Here, the `if` isn't a constructor with 3 unnamed arguments anymore. It has two named arguments: good old `then` and `else` are back in the game, but now in an object oriented way!

What do you think?

**Comment by pa9ey** [comment]
I like the general idea and reasoning for your change (I find some of this stuff not as readable as I might like) but the fact that, in the new idea, `if:` is an object and `then:` is the name of an argument (even thought they look identical) is not at all obvious and so it seems confusing.

**Comment by yegor256** [comment]
@gukoff yeah, I agree with @pa9ey It does look more similar to the good old Java, but it's not OOP any more. We have to make `if` an object with 3 arguments. In your example we have `if`, `then` and `else` -- three objects.

Also, keep in mind that long methods is a bad idea in the first place. They will have to be short in order to be readable. It's like in Lisp -- long structures are not readable and developers avoid them.

**Comment by gukoff** [comment]
> the fact that, in the new idea, `if:` is an object and `then:` is the name of an argument (even thought they look identical) is not at all obvious and so it seems confusing.

@pa9ey well, it's all about their order. The first one is a main thing being called, the others mean some additional information. Yes, it is pretty unusual and isn't obvious at first glance. But I got used to it very quickly, while writing this issue :)

> We have to make `if` an object with 3 arguments

@yegor256 yup, and these arguments have to be objects.

> In your example we have if, then and else -- three objects.

Hmm. What do you mean? `if` is some standard library object here, and `then` and `else` are just the names of its constructor parameters. The new constructor accepts three objects, and so it does in our current example as well.

**Comment by gukoff** [comment]
Actually, I was talking primarily about constructors. A method call would look like this:
```
filesystem file: '/tmp/x.txt' mode: 'r'
```
Or, the more complex example:
```
filesystem
    file:
        stripped: '__new_name.txt__' by_symbol: '_'
    mode:
        if: 
            filesystem writable
        then: 'rw'
        else: 'r'
```

**Comment by MadridianFox** [comment]
I see three levels of syntax.
First, **basic** relations of objects - instantiating and invoking of methods. All that above will be translated to this level. It's technical level. 
Second, user friendly expressions: control statements, operators, etc - all that forms logic of method.
Third, level of composition of objects. This we not only instantiate and invoke. This it has a sense, and will be comfortable to see names of arguments. 

What we have - first level is  as third level, but without optional elements.
Second level - sugar for more readable composition of low-level, senseless objects.

**Comment by astynax** [comment]
Hello! May I bring some SmallTalk here? Take a look:
```
expr ifTrue: [statements to evaluate if expr] ifFalse: [statements to evaluate if not expr]
```
In the SmallTalk "if statement" is just a method (message) of some boolean expression, and `ifTrue`/`ifFalse` is just a named arguments of method `if`.

A smalltalk'ish version of fibonacci example can look like this:
```text
create fibonacci(1) as Number:
  Number n
  bytes asBytes():
    lessThan: @n, 2
      ifTrue: 1
      ifFalse:
        plus:
          @n
          fibonacci:
            minus: @n, 1
```
And this example is even closer to FP: it looks just like a Church encoding of booleans:
```
true = (x, y) -> x
false = (x, y) -> y
if = (expr, then, else) -> expr(then, else)

if(lessThan(1, 2), "less", "greater") --> "less"
```
The main benefit of `if as a method` is type safety - `if` will be available only for "boolean" objects.

**Comment by yegor256** [comment]
@gukoff take a look at our new syntax, I believe you will like it
