### ISSUE TITLE
Too many free attributes error

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#280]
When compiling, the error "The object test has too many free attributes" occurs if there are more than 4 free attributes of an object.
```
[a b c d e] > test
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test 1 2 3 4 5
```   
Let's remove the extra free attribute and the code will compile without errors
```
[a b c d] > test
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test 1 2 3 4
```
      
After that, add an attribute to the test object and the code will also be compiled without errors.
```
[a b c d] > test
  321 > attr1
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test 1 2 3 4
``` 
Now let's change the description of the attribute and the error will return again
```
[a b c d] > test
  [] > attr1
    321 > @
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test 1 2 3 4
```
We remove 1 more free attribute and the compilation error disappears
```
[a b c] > test
  [] > attr1
    321 > @
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test 1 2 3
      
```
We can get this error without free attributes, for example like this:
```
[] > test
  [] > attr1
    321 > @
  [] > attr2
    321 > @
  [] > attr3
    321 > @
  [] > attr4
    321 > @
  [] > attr5
    321 > @
  123 > @

[args...] > app
  stdout > @
    sprintf
      "%d\n"
      test

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#280](https://github.com/cqfn/eo/issues/280); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@nlchar it's not an error, it's a feature. We don't want objects to have more than 4 free attributes, to keep the design clean.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#280` is not assigned, can't get performer

**Comment by nlchar** [comment]
@yegor256 we can reproduce the error while not having free attributes at all. I'll investigate this deeper if you like. However, for now, this is of a lower priority since we're working on a new transpiler.

**Comment by yegor256** [comment]
@nlchar yes, indeed, would be nice to investigate and report an accurate test case reproducing the bug

**Comment by yegor256** [comment]
@nlchar  I'm closing. If you think the bug is still there, please open a new issue.
