### ISSUE TITLE
Feedback required - new language design

### ISSUE THREAD

**Issue by sergiofigueras** [cqfn/eo#283]
Hello there guys!

I know that it is not related to EO directly, but as a reader of all @yegor256 books, and having some good experience in coding, I've decided to start a new JVM-based language focused on readability, maintainability, and testability.

Currently, it's still a very draft syntax proposal, and I'm looking more about the caveats that I'm forgetting on how to handle.

In that sense, I would like to ask anyone in the community, if it's possible, please check out https://github.com/sergiofigueras/belchior-language/blob/master/README.md and create an issue that should be clarified in my proposal.

Thank you, folks!

**Comment by yegor256** [comment]
@sergiofigueras I suggest you join our Telegram group and discuss it there: https://t.me/elegantobjects

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#283` is not assigned, can't get performer
