### ISSUE TITLE
Problem in the definition of decoration

### ISSUE THREAD

**Issue by anaumchev** [cqfn/eo#292]
If a is not in the scope of x, then the expression x.a is undefined:
https://github.com/cqfn/eo/blob/954d7105b94594f8a807be89885565edc47afc11/paper/calculus.tex#L186

**Comment by yegor256** [comment]
@anaumchev well, this is the idea of decoration: if a certain condition is true, x.a is not undefined anymore. How do you think we should explain it better?

**Comment by yegor256** [comment]
@anaumchev  I'm closing. If you think the bug is still there, please open a new issue.
