### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by anaumchev** [cqfn/eo#294]
Name d_4 is used in Figure 2:

https://github.com/cqfn/eo/blob/954d7105b94594f8a807be89885565edc47afc11/paper/semantics.tex#L52

But in the sequence of GMIs it changes to d_1:

https://github.com/cqfn/eo/blob/954d7105b94594f8a807be89885565edc47afc11/paper/semantics.tex#L205
https://github.com/cqfn/eo/blob/954d7105b94594f8a807be89885565edc47afc11/paper/semantics.tex#L206

**Comment by yegor256** [comment]
@anaumchev fixed, in b56e591 thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#294` is not assigned, can't get performer
