### ISSUE TITLE
Problem with access to decorator

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#295]
Code:
```eolang
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[dx dy] > vector
  ((dx.pow 2.0).add (dy.pow 2.0)).pow 0.5 > length

[x y] > point
  [to] > distance
    (vector (to.x.sub (^.x)) (to.y.sub (^.y))).length > @

[center radius] > cirle
  center > @
  [p] > is-inside
    leq. > @
      ^.@.distance $.p
      ^.radius

[args...] > app
  stdout > @
    sprintf
      "%f\n"
      (point 1.0 2.0).distance (point 4.0 6.0)
```
Example from the offcial paper:
![image](https://user-images.githubusercontent.com/49319353/121676884-db314100-cabd-11eb-9385-74ca294fdbdf.png)

System: Windows 10, JDK 16, Maven 3.6.3 
pom.xml: https://github.com/cqfn/eo/blob/master/sandbox/pom.xml

Error logs:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.eolang:quick-start >-----------------------
[INFO] Building quick-start 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- eo-maven-plugin:0.1.25:parse (default) @ quick-start ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.726 s
[INFO] Finished at: 2021-06-11T14:04:33+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.1.25:parse (default) on project quick-start: Execution default of goal org.eolang:eo-maven-plugin:0.1.25:parse failed: [16:7] mismatched input '.' expecting EOL: "      ^.@.distance $.p": InputMismatchException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by nikololiahim** [comment]
https://github.com/cqfn/eo/blob/85d831b543cb46946a2f6dc0b2a9050f0d0a0f89/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L180-L195

Yeah, as of now, parser basically does not allow accessing special attributes of special attributes, e.g. `$.^`, `^.@`, which makes `@` attribute basically unusable. This must be a bug.

**Comment by someilay** [comment]
Solution:
```eolang
[center radius] > cirle
  center > @
  [p] > is-inside
    leq. > @
      (^.distance p)
      (^.radius)
```

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#295` is not assigned, can't get performer
