### ISSUE TITLE
Include Maven wrapper

### ISSUE THREAD

**Issue by SimonHarmonicMinor** [cqfn/eo#296]
The `Readme.md` tells that the project requires Maven to build it. The fact is that not all developers use Maven. And even if they do, not everyone has the specific version installed.

It would be much more convenient if the project provided the [Maven Wrapper](https://maven.apache.org/plugins/maven-wrapper-plugin/wrapper-mojo.html) as a build tool. Firstly, if Maven version required an upgrade, this could be done transparently without bothering contributors. Secondly, this would make the environment easy to reproduce on any machine.

**Comment by yegor256** [comment]
@SimonHarmonicMinor you are welcome to submit a PR!

**Comment by SimonHarmonicMinor** [comment]
@yegor256 here is the [pull request](https://github.com/cqfn/eo/pull/298)

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#296` is not assigned, can't get performer
