### ISSUE TITLE
XsLine.with(XSL, Func<XML, Boolean>)

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#302]
Let's add a new method `XsLine.with(XSL, Func<XML, Boolean>)` to let the line apply XSL a number of times, until the `bool` is `false`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.28`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#302` is not assigned, can't get performer
