### ISSUE TITLE
Sugar for operators

### ISSUE THREAD

**Issue by MadridianFox** [cqfn/eo#31]
Uniformity of syntax it's good, but constructing objects and calling their methods for every control flow statement and operator is not comfortable for people. Perhaps we need to use traditional syntax for it, which will translated into instantiating of object and method call?
```java
if(1==2):
    11
else:
    12
// Will be translated to
(new If( new Equals(1,2) , 11 , 12)).value();
// Where
class If implements Computation{
    public Object value(){
        return this.test.value() ? this.first : this.second;
    }
}
```

**Comment by gukoff** [comment]
@MadridianFox I've found a kind of solution for this issue here: https://github.com/yegor256/eo/issues/27
I think, such an approach would make the syntax more readable and explicit at the same time - no implicit code substitution would be needed.

**Comment by yegor256** [comment]
@MadridianFox well, I see your point, but this "control flow" syntax is comfortable for you only because you're used to Java/C/C++ syntax and the way of thinking (me too). If you work with Lisp for a while you will feel much more comfortable with EO style of writing code than with Java. With our current syntax we are very close to functional programming. Very close.

**Comment by MadridianFox** [comment]
@yegor256 Ok, it will be more comfortable for that, who use Lisp. How many people uses Lisp? And Java/C/C++/ ? 😄

**Comment by yegor256** [comment]
@MadridianFox well, first of all there are many Lisp/FP users :) Second, we don't really care now how many people love Java or not. We are building something new. Of course, by definition, we will have negative feedback from the majority of Java community. This will only prove that we're moving to the right direction :)

**Comment by yegor256** [comment]
@MadridianFox take a look at our new syntax, I believe you will like it
