### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#320]
@yegor256 I think we should release now as the hse compiler is included into the repo.

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#320` is not assigned, can't get performer
