### ISSUE TITLE
eo-maven-plugin:resolve doesn't update the classpath

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#323]
But it should.

Let's do what's recommended here: https://stackoverflow.com/questions/2659048/add-maven-build-classpath-to-plugin-execution-classpath

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.1`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#323` is not assigned, can't get performer
