### ISSUE TITLE
C# as a backend for EO

### ISSUE THREAD

**Issue by andriyshevchenko** [cqfn/eo#324]
It would be good to translate EO down to C# language and make it possible to execute on top of a [new .NET 5 runtime](https://dotnet.microsoft.com/download) which is cross-platform.

Any thoughts/objections?
I think I could start implementation onto it.

**Comment by yegor256** [comment]
@andriyshevchenko if you are interested in implementing it, would be great! Just make a new repo `eo2csharp` and implement it there. Similar to how this repo was done by volunteers: https://github.com/polystat/eo2py Once it's ready, we will move your repo to `@polystat` organization.

**Comment by andriyshevchenko** [comment]
@yegor256 Thanks for responding to me. Does a Telegram chat exist specifically for EO language, except of  [@polystat_org](https://t.me/polystat_org)?

**Comment by yegor256** [comment]
@andriyshevchenko no, we don't have a special chat now. Feel free to use the one for Polystat -- we discuss everything related to EO over there.
