### ISSUE TITLE
Problems in using external objects

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#325]
Отсутствует реальная поддержка создания конкретных объектов во внешнем пространстве имен файла. Такие объекты проходят компиляцию, но при обращении к ним в программе происходит прерывание работы системы:

```
[x] > cover
  x > @

cover 555 > value

[] > app
  stdout > @
    sprintf
      "%d\n"
      value
```

При этом в общем пространстве и кодом, внутри другого объекта данные объекты функционируют:

```
[x] > cover
  x > @

#cover 555 > value

[] > app
  cover 555 > value

  stdout > @
    sprintf
      "%d\n"
      value
```

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#325` is not assigned, can't get performer
