### ISSUE TITLE
Problems in using external objects

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#326]
Отсутствует реальная поддержка создания конкретных объектов во внешнем пространстве имен файла. Такие объекты проходят компиляцию, но при обращении к ним в программе происходит прерывание работы системы. Это не позволяет напрямую имитировать внешние переменные языка C. 

```[x] > cover
  x > @

cover 555 > value

[] > app

  stdout > @
    sprintf
      "%d\n"
      value
```

При этом в общем пространстве и кодом, внутри другого объекта данные объекты функционируют. 

```[x] > cover
  x > @

#cover 555 > value

[] > app
  cover 555 > value

  stdout > @
    sprintf
      "%d\n"
      value
```

**Comment by yegor256** [comment]
@kreofil я правильно понял, что этот код не компилируется?

```
x > @

cover 555 > value

[] > app
  stdout > @
    sprintf
      "%d\n"
      value
```

**Comment by yegor256** [comment]
@kreofil это еще актуально?
