### ISSUE TITLE
Only lowercase letters in aliases

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#328]
Проблема с заглавными буквами возникает также с именами в алиасах. Спрашивается, зачем вводить ограничения на локальные по сути имена там, где можно организовать более свободный формат их использования. Выявление этой ситуации, правда, возникает во время компиляции. Но из описания языка непонятно, зачем нужно подобное ограничение.

```
+alias stdOut org.eolang.io.stdout
```

**Comment by yegor256** [comment]
@kreofil this is definitely a bug. This syntax should work without problems:

```
+alias aBC org.eolang.io.aBC
```

**Comment by kreofil** [comment]
It doesn't work:

```
+package test10
+alias stdOut org.eolang.io.stdout

# Попытка выполнить цикл
[] > app
  stdOut > @
    "Hello!\n"

...
[INFO] File /home/al/Projects/git/eo/tests/test10/target/04-pre/app.eo.xml/05-to-java.xml saved (2877 bytes)
[ERROR] [app.eo:2] The alias is invalid: "stdOut org.eolang.io.stdout" (broken-aliases:4)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.725 s
[INFO] Finished at: 2021-09-15T11:05:36+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.1.19:compile (default) on project quick-start: Execution default of goal org.eolang:eo-maven-plugin:0.1.19:compile failed: There are 1 errors in app.eo, see log above -> [Help 1]
[ERROR]
...
```

But it works:

```
+package test10
+alias stdout org.eolang.io.stdout

# Попытка выполнить цикл
[] > app
  stdout > @
    "Hello!\n"

    
$ ./run.sh 
Hello!
```

**Comment by kreofil** [comment]
I think if  I have alias, I can use different names for it.

**Comment by yegor256** [comment]
@kreofil yes, it's a bug, thanks!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#328](https://github.com/cqfn/eo/issues/328); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#328](https://github.com/cqfn/eo/issues/328); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
@IngeniariusSoftware @kreofil 
fixed in f79eee28f657052b39bab2835b10198dd954c31d  
please, check and reopen if it is not fixed yet

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#328](https://github.com/cqfn/eo/issues/328); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#328](https://github.com/cqfn/eo/issues/328); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
