### ISSUE TITLE
Unified reprsentation for any objects

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#330]
Для унификации предлагается обеспечить работу с атомарными объектами по аналогии с абстрактными и конкретными объектами, разрабатываемыми на Eolang. В качестве примера можно привести создание конкретного целочисленного объекта, который создается сейчас путем прямого обозначения. Например: ```10 > i```. Предлагается обеспечить его создание как и любого другого объекта используя общую форму: ```int 10 > i```. Сокращенные формы для существующих атомарных объектов стоит оставить в качестве синтаксического сахара, обеспечивающег создание объекта по умолчанию. Помимо этого одни и те же виды литералов можно будет использовать при создании других объектов, не вводя новые литеральные обозначения. Например, для безнаковых, длинных, двойных:
    
```
long 10
unsigned 100
float 3.14
double 2.7
...
```
На мой взгляд идеология языка в принципе не должна по семантике различать атомарные объекты и объекты, написанные на Eolang. Тогда язык будет чистым. В настоящее время это проявляется в ряде моментов. Имеются отличия по трактовке вариантов инициализации, созданию конкретных объектов и т.д.

**Comment by yegor256** [comment]
@kreofil а что тогда такое будет `10` в этой конструкции:

```
int 10
```

получается, нам нужно будет вводить какой-то новый синтаксис, специально для таких "типов". а это усложнит язык и потеряем его простоту. потому, `10` это фактически равно `bytes 0A`.
