### ISSUE TITLE
Remove type identification for atoms

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#332]
Возможно спорный момент. Учитывая бестиповую концепцию языка можно говорить о том, что независимо от того, какое действие выполняется, в любой объект передаются (грубо говоря) указатели на любые другие объекты, а на выходе результат представляется через указатель также на любой объект. Исходя из этого вводить специальное описанеи для объектов атомарного типа вряд ли имеет смысл. На мой взгляд, пример в описании языка создает ощущение, что возвращается литерал ``bool``, а не булевский объект::

```
+rt jvm org.eolang:eo-runtime:0.1.24
+rt ruby eolang:0.1.0

[text] > stdout /bool
```
Но фактически, для соблюдения бестиповой концепции должен возвращаться указатель на любой объект, объект ``bool`` в этом случае подразумевается, а не является синтаксической основой языка. То есть, в рамках общей концепции должна происходить растипизация. Поэтому из языка предлагает убрать уточнение типа. Необходимо описание типов возвращаемых объектов, в соответствии с общей концепцией проще сделать в описании объекта (в данном случае ``stdout``). По сути подобный подход используется в бестиповых системах. В любом ассемблере (машинном языке) неформально описывается семантика каждой команды (типы аргументов и результатов), а на входе и выходе имеем обезличенные адреса. В целом это дискусионный вопрос, каким должен быть язык: бестиповой или с использованием той или иной системы типов. Но в данном случа тот же ``stdout``, если он используется в качестве значения атрибута в другом объекте, все равно начинает восприниматься как бестиповой.

**Comment by yegor256** [comment]
@kreofil эти уточнения специально введены, чтобы мы могли глядя на всю программу [infer types](https://en.wikipedia.org/wiki/Type_inference). то есть сделали вывод о том, какой где тип/объект будет находиться в какой момент времени. без этой информации мы никогда этого сделать не сможем.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#332` is not assigned, can't get performer
