### ISSUE TITLE
object `exit` desirable

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#333]
Возможно имеет смысл добавить атомарный объект ``exit <string>``. Несмотря на то, что в принципе различные ситуации, возникающие в ходе работы программы и связанные с ее оперативным завершением, можно реализовать за счет постепенного возврата вверх, в ряде ситуаций целесообразно сразу осуществить завершение, минуя вложенность. Этот вариант завершения аналогичен функции ``exit`` используемой в языке программирования C. Объект может быть полезен в в случае компиляции в Eolang с других языков, имеющих подобное решение.

**Comment by yegor256** [comment]
@kreofil мы специально не сделали такого, чтобы избежать "процедурности". Выход в программе должен быть только один.
