### ISSUE TITLE
Object `break` desirable

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#334]
Для завершения последовательности бывает необходимо возвращать целевой объект, а не только атомарный ``bool``. Предлагается добавить в язык атомарный объект ``break``, который может возвращать объект любого типа: ``break <object>``. В отличие от ``return`` он обеспечивает выход только из последовательности. Например, при наличии условий, последовательность может даже не проходить до конца. По аналогии в принципе можно добавить и атомарный ``return``, но в целом это можно обойти. Хотя для построения транспиляторов в Eolang ``return`` тоже может оказаться полезным.

**Comment by yegor256** [comment]
@kreofil `break` (как и `return`, `continue`, `goto`) являются наследием <del>царского режима</del> процедурного программирования и, как писал Bertrand Meyer "break and continue are just the old goto in sheep's clothing." Поэтому мы от них решили отказаться.
