### ISSUE TITLE
The comments in any string of code desirable

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#336]
Предлагается ввести возможность ставить одострочные комментарии в любой строке и с любой позиции. Я не вижу в реализации этого ничего сложного, так как обычно комментарии распознаются сканером и легко для дальнейшего парсинга могут быть заменены на перевод строки, эквивалентный пустой строке, что практически везде в компиляторе допустимо. Или вообще можно его удалить из разбора. Наличие комментариев в любом месте позволяет выстраивать необходимые пояснения или при тестировании и отладке вставлять дополнительный код и в дальнейшем комментариями шунтировать его. Эта возможность, кстати, практически существует в любом языке. Обидно, когда такой вот код перестает работать:

```
[] > app
  # Просто воткнул комментарий
  stdout > @
    "Hello!\n"
```

или такой::

```
[] > app
# Просто воткнул комментарий
  stdout > @
    "Hello!\n"
```

Если, возникают какие-то проблемы с анализом комментариев в ступеньках кода, то хорошо хотя бы иметь в любом месте комментарий начинающийся с первой позиции строки. Кстати разработчики языка Go делают аналогичный изврат, проставляя перед парсингом точки с запятой в конце строк, если они там не стоят. Описано в документации.

**Comment by yegor256** [comment]
@kreofil мы это запретили по философским причинам. Мы верим в то, что блок кода (объект) является цельной и неделимой сущностью и если внутри него нужны комментарии, значит пришло время его разбивать на более мелкие сущности. Существуют и другие мнения, но мы решили держаться этого. Тут подробнее: https://softwareengineering.stackexchange.com/a/52836/20873
