### ISSUE TITLE
`native` and other package names

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#338]
При использовании в качестве имени пакета `native` в EO получил ошибки на уровне компилятора java. Как я понимаю, имеются конфликты имен. Может быть каким-то образом сформулировать список этих имен, запрещенных к использованию или обойти проблему за счет дополнительных префиксов-суффиксов?

**Comment by yegor256** [comment]
@kreofil пожалуйста, приведите пример кода и какую ошибку получаете от компилятора.

**Comment by kreofil** [comment]
На самом деле здесь все просто. Если в качестве имени пакета вдруг оказывается ключевое слово java (class, naive, double...) то в этом случае сборка прерывается по вполне очевидным причинам. Например такой код:
```
+package class
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[x] > cover
  x > @

[] > app
  cover 555 > value

  stdout > @
    sprintf
      "%d\n"
      value
```
не проходит компиляцию в java. Здесь вижу два пути. Документально запретить использовать ключевые слова java  в качестве имен создаваемых пакетов (хоть они и не привязаны к Eolang) или формировать изменять такие имена при трансформации в другие внутренние, добавляя префикс или суффикс. Или вообще генерировать свои уникальные имена пакетов.

Несколько вариантов простых примеров с разными ключевыми словами и без них полжил сюда: [https://github.com/kreofil/C2EO-draft/tree/main/EO-sources/tests-eo/test13]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#338](https://github.com/cqfn/eo/issues/338); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.2`

**Comment by yegor256** [comment]
@kreofil it's fixed. It's possible to use any words in package names, in the version 0.6.2
