### ISSUE TITLE
more than one empty line is possible between objects

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#345]
This syntax is parseable, but it should not be (too many empty lines between objects):

```
5 > first


6 > second
```

**Comment by IngeniariusSoftware** [comment]
@yegor256 in some cases this is a useful feature to visually differentiate large objects from each other

**Comment by andreoss** [comment]
@yegor256 Done. Please close it

**Comment by yegor256** [comment]
@andreoss thanks!
