### ISSUE TITLE
Clarify parent objects

### ISSUE THREAD

**Issue by fizruk** [cqfn/eo#350]
This issue is created based on my [message in Polystat Telegram group from July 19, 2021](https://t.me/polystat_org/322):

> I am trying to understand parent objects, but the paper seems to be inconsistent about them. Here are 3 incompatible ways to handle parent objects that I have extracted from the paper:
> 
> 1. Reverse snake edges (edges to parents) are created using BIND (and apparently COPY). These arrows correspond to lexical scopes of objects in a program (𝜑-term). These snake arrows are never used in dataization algorithm, but in both compilers it seems that parents are computed lexically (matching reverse snake edges)!
> 
> 2. Dataization algorithm (in the paper) keeps track of parents using stack (if v = ρ then v <- S[1]). This stack, however, does not match reverse snake arrows. In fact, latest description of the algorithm only puts objects on stack when locating 𝜑 attribute or handling an ATOM (or following a dotted edge). I assume that after recursive call to R, stack should also be updated, but that would still not match reverse snake arrows.
> 
> 3. Atoms apparently require access to both previous ways of computing parents. From section 3.7 Atoms we can infer that, for example a number 2 can be represented by an object ⟦ δ ↦ 2, add ↦ ⟦ x ↦ ∅, 𝜑 ↦ λs. D(s[0].x) + D(s[1]) ⟧ ⟧. But when we compute 2.add(x ↦ 3) the actual stack of parents will not have correct parents: s[0] has to be "dynamic" — come from the stack (but there is an issue with stack management for dotted edges and also off-by-one problem with indexing), but s[1] has to be "lexical" — it should be the number 2 object. In the cqfn/eo compiler I see that numbers are implemented in such way that lambda has direct access to its parameter and parent object without relying on the stack of parents!
> 
> My current understanding is that stack of parents is not really used in both existing EO compilers neither for dataization, nor implementation of atoms. If my understanding is correct and compilers are assumed to be mostly correct (at least in the handling of parent objects), then I suggest updating paper to reflect the actual semantics. But if I am missing something, please let me know.

**Comment by yegor256** [comment]
@fizruk I believe it's fixed already, I'm closing

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#350` is not assigned, can't get performer
