### ISSUE TITLE
сode with access to phi attribute is not compiled

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#363]
## EO code

```java
+package example

+alias org.eolang.io.stdout

[] > obj
  "some" > @
  [] > foo
    ^.@ > @

[args...] > app
  stdout > @
    obj.foo

```

## Expectation

By analogy with the example article, I would like to access the phi attribute

![image](https://user-images.githubusercontent.com/33983579/136478917-f8b22b4d-227c-462b-9f0f-1248b6a809af.png)

##  Result

an error occurs during compilation

![image](https://user-images.githubusercontent.com/33983579/136479219-fe324b20-1539-4a4e-96b7-645b195ce6a5.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware failed to reproduce in b249dbd. I think the problem is somewhere else with your code. Check the line that goes right after the one with the error. Is it empty? Remember, we don't tolerate lines with spaces.
