### ISSUE TITLE
Parent Referencing

### ISSUE THREAD

**Issue by hadiSaleh** [cqfn/eo#365]
The EO paper proposes the following realization of parent references in the language:
Since the same object may be bound to more than one attribute, the parent ρ may
depend on where the object is bound.
This definition is erroneous and should be considered carefully and cautiously. Let’s have a look
at the following example:

```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf
[] > obj1
  add. > att1
    0
  100 > @
[args...] > app
  stdout > @
    sprintf
      "%d\n"
      att1.
        obj1
        0
```

Here, we have attribute att1 of the obj1 object. This attribute is equal to the object 0.add.
Hence, .add is a child of 0. At the same time, 0.add is a child of obj1 , which may be dataized to
100. Therefore, the program should print 100, not 0 as it is now. This rather simple example
demonstrates one of the problems (i.e., semantical indeterminism) that would occur if the
dynamic parent referencing technique will be actually implemented in the compiler as the defacto standard. Moreover, the dynamic parent referencing is unsecure, too. Consider the
following example:

```
[a] > obj1
  [b] > att1
  [c] > att2
  ^.^.a > @
```

Here, object att2 references obj1. If the parent referencing will be dynamic, the following code
would broke, becase the referenced parent does not exist in the current scope:
[] > someOtherGlobalObject
```
(obj1 7).att1.att2 > @
```
This example proves that parent referencing must be static and relying on the actual structure of
the program written by the programmer, and not relying on the indeterministic state of the
dynamic contextual environment.

**Comment by yegor256** [comment]
@hadiSaleh we have a new special attributes `&` which does exactly what you are looking for!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#365` is not assigned, can't get performer
