### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by hadiSaleh** [cqfn/eo#366]
Once a programming language has recursion, it has everything. Nevertheless, the memory
object might be handy for newcomers with previous imperative background. For now, the
memory object is able to contain data values, and not complex objects. Since that, the following
example would break:
```
[] > obj1
  12 > att1
  [] > att2
  34 > att3
[] > obj2
  memory > i
  seq
    i.write obj1
    i.write
    i.read.att2
    i.write
    i.read.att3
  add.
    i
   1
```

Here, we are trying to rewrite memory value based on the previous state of the memory. This
is not possible because of the lazy nature of the language. One of the solutions proposed by
language maintainers was to add the special dataize operation, which is able to evaluate
objects to data anywhere in the program. We would like to warn the community that this
operation is actually a reflective call breaking the declarative traits of the language. Reflection is
one of the mechanics discouraged for use by the EO philosophy. Indeed, if one needs to use a
reflective operation when implementing trivial or day-to-day programs, the language is poorly
designed. As an alternative, we would like to propose the State Monad. This is a functional
counterpart to state management.

**Comment by yegor256** [comment]
@hadiSaleh we already gave up on the idea of "dataized" object: https://github.com/cqfn/eo/issues/354
