### ISSUE TITLE
Inheritance for Types or Type composition

### ISSUE THREAD

**Issue by mdbs99** [cqfn/eo#37]
In this [chat](https://gitter.im/yegor256/elegantobjects?at=58398a92444b3778765b1451) we are discussing about inheritance for `Types` and now I'm thinking about if we really need this.
According to this [article](http://www.yegor256.com/2016/04/26/why-inputstream-design-is-wrong.html), Interfaces must be small. I agree. But if we will have inheritance for `Types` (interfaces), how guarantee they will be small?
if `A` have 3 methods and `B`, that inherits from `A`, have more 3 methods, the Object will need to  implements 6 methods. That is huge.

I'm thinking about **Type composition** instead of inheritance for Types.

Before you start to think in this idea, you need to understand how composition, supported by language, will work. In issue #6 I've proposed a syntax for object composition. But we can improve and extend that for `Types` too.

**Comment by pa9ey** [comment]
@mdbs99 How do you compose types (such that it's a distinct thing from inheriting from types)?

**Comment by mdbs99** [comment]
@pa9ey this doesn't exist (I guess) so, we need to discuss first.
As I've said before, we need composition for implements types (interfaces). Composition for Classes exists a long time ago in Object Pascal and I really don't know why doesn't exists in "object-oriented languages" like Java and C#.

But, I think, we need composition for Interfaces too (or the compiler will be smart). If we use inheritance for Types they will grow up, introducing many methods on each new subtype. So, maybe the same syntax I already proposed could be used for Interfaces.

In my example in #6 I wrote this:
```
type Dog extends Run, Bark { 
  name(): String
  sit()
}

var dog = object Dog("Rex") {
  constructor (n: String) { var name = n }
  name(): String { print (name) }
  sit() { print ("sat") }
  compose {  
    run from r1 implements Run,
    bark from b1 implements Bark
  }
}
```
The `Dog` extends `Run`, `Bark` but the implementation of `object Dog` we have a composition to implement `Run` and `Bark`.

The problem is: The compiler will be smart enough to distinct this or we need to introduce composition for Types too?

**Comment by pa9ey** [comment]
I guess what I'm saying it, I can't imagine what composition of types would actually mean.
If `C` was a composition of `A` and `B`; and `C` had all the messages on it that `B` has on it, plus all the messages that `A` has on it; would this be composition?
If so, then it's the same as inheritance.
If not, then what *would* be on `C`?  
 
Or are you saying that there would not be a `C`? An object could implement `A` + `B` but that "composition" could never have a name.

**Comment by mdbs99** [comment]
@pa9ey the major problem is grow up a Type with more and more methods using inheritance.
If the idea of Type composition is confusing, we can move on...
But the question is: How we'll make objects with few methods if we can have a Type with a thousand of methods to implement?

**Comment by pa9ey** [comment]
Well it's only a problem if objects are going implement lots of interfaces (well, 4+ maybe). Don't you either have to keep to a few very small interfaces or else use duck typing?

**Comment by mdbs99** [comment]
@pa9ey imagine that we have this hierarchy `A<-B<-C`.

1. `A` has 3 methods
2. `B` has more 2 methods
3. `C` has 1 more method

`B`inherits from from `A`, then `B` has 5 methods.
So, `C` inherits from `B`, then `C` has 6 methods to implement.
If an object wants to implement `C`, then it will need to implement 6 methods.

> ...keep to a few very small interfaces or else use duck typing

See, the problem isn't the number of interfaces, but the number of inheritances.

**Comment by pa9ey** [comment]
@mdbs99 Sure. That's fair. But it's roughly the same thing. If an object implements `C` it basically implements three interfaces. EO currently allows 4 messages per interface (type). If you implement no more than three interfaces (which isn't currently specified) then an object will have a maximum of 12 methods. (The limit for that is also not mentioned yet.)

Not that I'm saying that these limits are the "right" ones. Just that "Don't you either have to keep to a few very small interfaces or else use duck typing?"

**Comment by pa9ey** [comment]
@mdbs99 Although, even with duck typing, you might still want to limit the number methods an object can implement.

And the question still remains, how would "type composition" (whatever that is) limit the number of methods that an object has?

**Comment by mdbs99** [comment]
>  If an object implements C it basically implements three interfaces.

No, it implements only one.

> ...If you implement no more than three interfaces

How to control that? The compiler allow inheritance or not. To control the number of they, I guess, is complex.

> ...then an object will have a maximum of 12 methods.

And that is to much, don't?

**Comment by mdbs99** [comment]
> And the question still remains, how would "type composition" (whatever that is) limit the number of methods that an object has?

@pa9ey  Ok, what do you think?

```
type Run:
  Run run()

type Bark:
  Bark bark()

type Dog:
  String name()
  Dog sit()
  compose:
    Run run()
    Bark bark()
```
Instead of extends, the `Dog` was composed.
So, to implements Dog type we'll need three objects. Not only one with 4 methods. Got it?

**Comment by yegor256** [comment]
@mdbs99 I understand your concern about too big objects (with too many methods), but isn't it an unsolvable problem? If your design requires subtyping from three different types, each of which has 4 methods -- so be it. This is the design. How can we on the level of language resolve that? If your object has to be a dog, a cat and a flower at the same time -- it's weird, but it's your design. Or I miss something?

**Comment by mdbs99** [comment]
@yegor256 imagine that you need to represent a `Dog`. Someone says: "Hey, we already has a type for this... look the dog.eo file".

You open the file and see this:
```
type Dog extends Mammal:
  Dog bark()
```
And that is it.
You see this and think: "Oh, that's Ok, only one method. Easy."
But to implement a `Dog` properly, you discovered that you need to code 30 methods for all hierarchy!

So, if we'll need to see all hierarchy to implements a simple `Dog`, don't you think this break the encapsulation?

**Comment by yegor256** [comment]
@mdbs99 yes, it will be difficult. I don't think it breaks encapsulation, but it will be difficult. I like your idea about "composing objects from other objects," but we are discussing it in some other ticket, if I remember. So, I'm in favor of object composition, but can't understand what is type composition.

**Comment by mdbs99** [comment]
@yegor256 I meant that breaks encapsulation because it use inheritance: you need to know the hierarchy if you will change something.

> ...can't understand what is type composition

That is an attempt to make Types always small... but if it will introduce more complexity — for people or compiler — I can give up for this idea.

**Comment by stain** [comment]
I think this is interesting, but I think forcing the choice of composition
is not right in a type, that is an implementation details.

People who want to do bad design will always find a way. With your proposal
you could end up with a large and restrictive type composition graph that
needs to be implemented, that could also get messy..

**Comment by yegor256** [comment]
@mdbs99 we don't have types anymore
