### ISSUE TITLE
Meaning of `^`

### ISSUE THREAD

**Issue by eyihluyc** [cqfn/eo#376]
The [paper](https://www.eolang.org/eolang-paper.pdf) states that the parent depends on 'where the object is bound', however, the following example shows the contrary.

Here, an object is copied inside some other object. The question is what is the parent of this copy: where object was copied, or where the original object was created.

```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[] > a
  19 > @
  [x] > m

[] > b
  37 > @
  a.m > n
    3

[] > app
  stdout > @
    sprintf
      "%s"
      b.n.^
```
This program is dataized to `19`, implying that `b.n.^ == a`, not `b`,  so parent of copy is same as the parent of the original object.

Result is same if instead of `a.m 3`, `n` is bound simply to `a.m`.

Hence, in any case, place of application does not influence on `rho`; it is defined by the original object only.

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.6`

**Comment by yegor256** [comment]
@eyihluyc your code example is correct and the paper was wrong. I tried to make necessary changes in the paper, here 09c8239b. I will try to explain more soon.
