### ISSUE TITLE
possible duplicate computation

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#378]
Some example of EO code and the C equivalent

<table>
<tr>
<th>EO</th>
<th>C</th>
</tr>
<tr>
<td><pre lang=\"java\"><code>
+package sandbox
&nbsp;
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf
&nbsp;
[args] > complexReturnC
&nbsp;
&nbsp;&nbsp;[a] > f
&nbsp;&nbsp;&nbsp;&nbsp;memory > result
&nbsp;&nbsp;&nbsp;&nbsp;memory > isReturn
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;if. > @
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isReturn.write FALSE
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.eq 1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (a.add 1)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.eq 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (a.add 2)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isReturn.write TRUE
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.write 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.eq 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (a.add 3)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isReturn.write TRUE
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.write 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isReturn
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.eq 4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (a.add 4)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seq
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (a.add 5)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isReturn.write TRUE
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.write a
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error "Unexpected behavior"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error "Unexpected behavior"
&nbsp;
&nbsp;&nbsp;[] > main
&nbsp;&nbsp;&nbsp;&nbsp;memory > a
&nbsp;&nbsp;&nbsp;&nbsp;memory > result
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;seq > @
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a.write (^.args.get 0).as-int
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.write (^.f a)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stdout (sprintf "complexReturn = %d
" result)
&nbsp;
[args...] > app
&nbsp;&nbsp;(complexReturnC args).main > @
&nbsp;

<code></pre></td>
<td><pre lang=\"c\"><code>
#include <stdio.h>
#include <stdlib.h>
&nbsp;
int f(int a) {
&nbsp;
&nbsp;&nbsp;if (a == 1)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;a = a + 1;
&nbsp;&nbsp;}
&nbsp;
&nbsp;&nbsp;if (a == 2)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a = a + 2;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return 2;
&nbsp;&nbsp;}
&nbsp;&nbsp;else if (a == 3)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a = a + 3;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return 3;
&nbsp;&nbsp;}
&nbsp;
&nbsp;&nbsp;if (a == 4)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;a = a + 4;
&nbsp;&nbsp;}
&nbsp;
&nbsp;&nbsp;a = a + 5;
&nbsp;&nbsp;return a;
}
&nbsp;
int main(int argc, char** argv) {
&nbsp;&nbsp;&nbsp;&nbsp;int a = atoi(argv[1]);
&nbsp;&nbsp;&nbsp;&nbsp;int result = f(a);
&nbsp;&nbsp;&nbsp;&nbsp;printf("complexReturn = %d", result);
}
<code></pre></td>
</tr>
</table>

### Expectation

./run.sh 5
complexReturn = 10

### Result

./run.sh 5
complexReturn = 15

**Comment by yegor256** [comment]
@IngeniariusSoftware yes, indeed, we have duplication evaluation problem now, see #417
