### ISSUE TITLE
bound array to named attribute 

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#385]
## EO code

```java
+package sandbox

+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%d %d %d":format
      1 2 3:args
```

## Expectation

> 1 2 3

## Result

![image](https://user-images.githubusercontent.com/33983579/138258378-6ffb8d24-8b8e-4b55-9c20-06dfbc6604f7.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware I believe it was a problem in your code, I'm closing
