### ISSUE TITLE
Is it possible to implement support for an array as an argument in sprintf?

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#386]
## EO code

```java
+package sandbox

+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[elements...] > arr
  elements > @

[args...] > app
  stdout (sprintf "%d %d %d" (arr 1 2 3)) > @

```

**Comment by IngeniariusSoftware** [comment]
@yegor256 , yes I tried this again, but unfortunately I got this error:
![image](https://user-images.githubusercontent.com/33983579/140986079-8f53d3dd-2c33-4273-b308-f2348ce3d937.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by yegor256** [comment]
This is how it works, since version 0.21.0:

```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf 
      "%d %d %d" 
      ...* 1 2 3
```

The prefix `...` turns an array into vararg.
