### ISSUE TITLE
attribute number limitation?

### ISSUE THREAD

**Issue by M-M-M-M** [cqfn/eo#39]
> An object may have up to five attributes.

What is the reason for limiting the number of attributes to 5?

**Comment by yegor256** [comment]
@M-M-M-M mostly in order to avoid big objects. If you need to have more that five, your design very likely is wrong. So, it's a good trigger for you to realize your "mistake" earlier than later. It's compile-time static analysis. Make sense?

**Comment by amaembo** [comment]
Is it compile-time warning or fatal error? Could it be ignored via some, un, annotation?

**Comment by MonsieurLuge** [comment]
There is always rule exceptions. This 5 attributes constraint must result to a warning when compiling instead of an error. I think.

**Comment by alexpanov** [comment]
@yegor256 
I agree. Having a language that actively prevents fat objects is a good thing.
If, for example, you need to "spread" multiple objects across one table, there will most likely be ways to do so.

**Comment by yegor256** [comment]
@MonsieurLuge I think that we should **not** have any warnings. EO must be a very strict language. It either compiles without any issues, or fails and stops. No compromises.

**Comment by MonsieurLuge** [comment]
Ok. I understand and agree.

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.15`

**Comment by yegor256** [comment]
@M-M-M-M it's fixed, I'm closing
