### ISSUE TITLE
new line at EOF

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#395]
<pre>
1 > x
# no new line here
</pre>

This code fails to be parsed with 
```
org.eolang.parser.ParsingException: [1:5] missing EOL at '<EOF>': "
"
```

**Comment by andreoss** [comment]
@yegor256 Done. Please close it.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#395` is not assigned, can't get performer
