### ISSUE TITLE
Can we get rid of garbage collection?

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#4]
Can we get rid of garbage collection? Is it technically possible? If all objects are immutable, I think it is...

**Comment by englishman** [comment]
As EO(L) will be compiled into Java lang then why garbage collection question was raised at all?

**Comment by yegor256** [comment]
@englishman we can compile into Java code with only static methods, no objects. There will be no garbage collection in this case.

**Comment by yegor256** [comment]
@englishman and Java won't be the only target platform. we will compile to other platforms too, but later (C, maybe Assembly directly, etc)

**Comment by SilasReinagel** [comment]
How would all objects being immutable relate to garbage collection? Aren't objects still being retained in memory until they cease to be needed? Are you proposing developers manually cleanup their objects again?

**Comment by gukoff** [comment]
In case **all** objects are immutable, the garbage collection seems to be unnecessary, because:
* circular dependencies are impossible;
* we can use reference counting to determine whether an object has to be destructed;
* we can consider an empty default destructor and the universal after-destructor behaviour: decrement reference counters of all attributes and free the memory. It would make us to write destructors only when it's really necessary(open descriptors, etc);
* explicit destruction is better than implicit destruction.

**Comment by mdbs99** [comment]
@gukoff this is exactly behavior (all you wrote) in Object Pascal  — and I liked.

**Comment by gukoff** [comment]
> @gukoff this is exactly behavior (all you wrote) in Object Pascal — and I liked.

Here, the first statement is the most important. I guess, not all the objects are immutable in Object Pascal; does every circular dependency lead to a memory leak there?

**Comment by mdbs99** [comment]
@gukoff the objects in Object Pascal are the same that Java: They are mutable by default. Your code will make them immutable.
There are no memory leak because the programmer controls that. Don't exists a CG.
But if you use Interfaces instances, the compiler uses reference counting and release these instances when them get out the scope and no more referenced by anyone.

PS: I have a [blog](http://objectpascalprogramming.com/) that talks about truly object-oriented programming using Object Pascal.

**Comment by stain** [comment]
If all objects would live on the stack, then there is no need for GC, just reference counting. However then you would want to have tail recursion so you can shorten the stack - tail recursion on the JVM stack is a bit tricky.

**Comment by pchmielowski** [comment]
BTW. if someone is not familiar with details of Garbage Collection and Reference Counting approaches (like myself until recently), I'm recommending this short podcast:
http://fragmentedpodcast.com/episodes/064/

**Comment by alexpanov** [comment]
I do not understand the issue. Please correct me if I'm wrong with my assumptions.
As far as I see it, there are three ways to go about garbage collection without having to deal with memory leaks:

1. Do automatic GC;
1. Do manual GC;
1. Do no GC at all and make no new objects.

Option `2` is tedious and error prone. I believe it should be out of the realm of possibility unless there is a goal of not having any adoption at all.

Option `3` is something I'm not certain about. If *all* objects are immutable, how does HTTP request processing look like, for example? Am I correct when I say that there will be at least some objects created to response to an HTTP request? If it's true, that means  that option `3` is not possible.

It might be just a matter of preference, however it seems like leveraging existing GC 'infrastructures' is going to save a lot of effort.

I personally am practically certain that I'm not going to use any language that requires manual GC under any circumstances.

**Comment by interstar** [comment]
@gukoff  Isn't reference counting a kind of garbage collection?

**Comment by gukoff** [comment]
> @gukoff Isn't reference counting a kind of garbage collection?

You are right, it is. What I meant is the non-deterministic garbage collection.

**Comment by psionski** [comment]
@interstar I think yes - both tracing [garbage collection](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)) and reference counting are forms of garbage collection. What they probably mean is that they want to avoid _tracing_ GC (e.g. mark-and-sweep).

@gukoff, this is a fascinating idea! However, if you truly want no cycles, you have to forbid anything that might semantically appear "simultaneous", for example the bit of Haskell code in https://wiki.haskell.org/Tying_the_Knot :
```
cyclic = let x = 0 : y
             y = 1 : x
         in  x
```
Note that even though no [mutable values](https://en.wikibooks.org/wiki/Haskell/Mutable_objects) were used, there's still a cycle.

**Comment by moriline** [comment]
with all due respect you should will be set **muttable** objects, because some objects have different states. Sooner or later.

**Comment by Lewiscowles1986** [comment]
Surely this would be unworkable (working against the platform) as the JVM platform implements it's own GC? (so you'll be GC'd anyway)

**Comment by zeitlinger** [comment]
@gukoff: you can have circular dependencies with reference counting, as long as one is the owner - see https://doc.rust-lang.org/book/ownership.html

**Comment by Sammers21** [comment]
@gukoff,

> we can use reference counting

Reference counting is a garbage collection technique

> determine whether an object has to be destructed

If you compile EO code into java source code files there it would be no way to destruct an object.

**Comment by yegor256** [comment]
This is outside of EO scope, I believe. The destination platform (JVM or such) will deal with objects the way they want.
