### ISSUE TITLE
update canonical dir

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#403]
https://github.com/cqfn/eo/tree/master/sandbox/canonical

pom with 0.16.1

![image](https://user-images.githubusercontent.com/33983579/139399426-f7f8ded2-419e-403a-892d-28fefe0f7697.png)

pom with 0.16.2

![image](https://user-images.githubusercontent.com/33983579/139399482-e0acc69e-e779-4844-88b4-3f0480f03528.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware try the latest version 0.16.6, it works OK
