### ISSUE TITLE
unicode-char syntax is not supported

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#407]
Try to add this to `full-syntax.yaml`:

```
'\u5BB6` > x
```

It should work (as a single "char"), but it fails

**Comment by yegor256** [comment]
@andreoss please, fix this, the budget is 0.5h

**Comment by andreoss** [comment]
```
'\u5BB6` > x
```
@yegor256 is '`' (backtick) intentional here?

**Comment by yegor256** [comment]
@andreoss no, it's a typo, sorry. Should be `'\u5BB6'`.

**Comment by andreoss** [comment]
@yegor256 will be done as part of #480. This one can be closed.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#407` is not assigned, can't get performer
