### ISSUE TITLE
Type vs "Anything in the heiarchy rooted at this type"

### ISSUE THREAD

**Issue by OneWingedShark** [cqfn/eo#41]
One problem that many modern OOP languages have is a failure to discern between "exactly this type" and "this type or any of its decedents" in parameters. -- For convenience let us call the "hierarchy rooted at this type"a class.

("type types" just sound wrong,; and I'd rather not use "abstract type" or "interface" because they're further away from the idea than I'd like.)

One way to distinguish between the type and the class would be to co-opt something like Ada's class attribute. (Attributes being a property of the type rather than a method [e.g. an array-type has the attributes `first` and `last` which are _always_ the first and last values of the index] and are indicated with the `'` character.)

Thus, in Ada, it's possible to express something like:
`Function Image( Object : Sometype ) return String;`
and
`Function Image( Object : Sometype'Class ) return String;`
with the former meaning "a parameter of exactly this type" and the latter meaning "a parameter of this type or anything descended from it".

There are several advantages to this separation:

1. Dynamic-dispatch is **slow** compared to static calls.
2. It allows for a clear indication between dynamically-dispatched calls and static-calls in the source.
3. Only method calls with a class parameter need dynamic dispatching; calls without can be statically determined.
4. Inheritance-wise, a method with `class` means that it is written/implemented in the general manner and need not (and probably should not) be overridden... whereas an inheriting type **should** override a method with a parameter of the type.

**Comment by yegor256** [comment]
@OneWingedShark you know that we decided not to have classes in EO? Only types and subtypes.

**Comment by OneWingedShark** [comment]
Perhaps using the word "class" was a mistake, I am using the term to mean "family of types" -- IIUC the EO types are essentially just interfaces, which is fine... but that doesn't change the need (or advantages) of being able to say/distinguish-between "this thing specifically" and "this thing and any of its children". The former can (and ought to) be done statically, the latter cannot be done statically in the general case.

(You _can_ do a lot w/ static analysis, to include resolving some dynamic calls to static calls, which is awesome, but TTBOMK hasn't been adopted. [There was an ACM paper on it awhile back, they used Modula-2; sorry, I cannot remember the title, date, or author.] -- this general case problem comes to the forefront when dealing w/ libraries.: given a method operating on a "thing of this type or anything derived from it", you cannot optimize it at all because there's no guarantees [other than the base type's interface] that can be presented to the compiler.)

**Comment by mdbs99** [comment]
Wow, Ada...

>Assim, em Ada, é possível expressar algo como: 
Function Image( Object : Sometype ) return String;
e 
Function Image( Object : Sometype'Class ) return String;
com o primeiro significado "um parâmetro de exatamente este tipo" eo último significado "um parâmetro deste tipo ou qualquer coisa desceu a partir dele".

That isn't a good syntax.
I could be wrong, but in Object Pascal you only write this:
```
function Image(var Object : TSometype): string;
function Image(Object : TSometype): string;
```
This do the same of your code.
The "only" difference is that `var` keyword was used.

**Comment by OneWingedShark** [comment]
> Wow, Ada...
>
>> `Function Image( Object : Sometype ) return String;`
>> and
>> `Function Image( Object : Sometype'Class ) return String;`
>
> That isn't a good syntax.

The point I'm trying to illustrate isn't about syntax, but a very specific portion of semantics with respect to dealing with OOP.

>I could be wrong, but in Object Pascal you only write this:
>
>    function Image(var Object : TSometype): string;
>    function Image(Object : TSometype): string;
>
> This do the same of your code.
> The "only" difference is that var keyword was used.

Those aren't the same as what I'm trying to say/illustrate; in Ada they are equivalent to 
`function Image(Object : in out TSometype) return string;` and `function Image(Object : TSometype) return string;`, respectively.

What I'm trying to bring up is the point that there's a difference between "exactly, literally THIS type" and "this type, and anything that extends it". -- In the former we know *exactly*, statically what's there and what operations are available... in the second, we don't, and so require dynamic dispatching [e.g. C++'s vtables].

As an example, let us consider the type Integer and the subtype Positive (Integer with the added constraint of "X > 0" for all values X). If we have method `F1( Item : Integer )` should `Item` refer to only Integer, or should it refer to Integer and Positive both? (This is what the underlying semantics of Ada's `Sometype` and `Sometype'Class` syntax, the former is exactly that type and the latter is that type and things derived from it; it has nothing to do with whether or not the [parameter is by value or reference](http://docwiki.embarcadero.com/RADStudio/Berlin/en/Parameters_%28Delphi%29#Value_and_Variable_Parameters).)

The consideration is relevant to both performance and optimization as every operation that can be done w/o a dynamic dispatch is simpler and faster and less information is unknown.  -- For example of optimization, if we have the general function `Op#( X : Positive ) return Positive` where `#` is 1..4 we could have a call-chain of ` Op1( Op2( Op3( Op4( Positive_Value ) ) ) )` and eliminate ***all*** checks on the constraint in the bodies of all the `Op#`-functions as soon as we verify that `Positive_Value` indeed satisfies the constraints of `Positive`... and we can do it because the functions all return Positive. (The case doesn't hold if they return `Integer`.)

**Comment by mdbs99** [comment]
@OneWingedShark I know about "parameter is by value or reference". But using Objects, the parameter is always by reference. In that case, `var` keyword works different — but I could be wrong — only in FreePascal, ie, in Delphi there is no difference. I mean, the`var` keyworkd will says to compiler: "Accept only this type".
I've tried to found a paper, but I didn't found (yet). I'll search again later.

**Comment by OneWingedShark** [comment]
@mdbs99 
> I know about "parameter is by value or reference". But using Objects, the parameter is always by reference.

With Delphi, Object Pascal and Java this is correct, as per the language definition.  
This need not be the case language-/implementation-wise though.

>  In that case, `var` keyword works different — but I could be wrong — only in FreePascal, ie, in Delphi there is no difference. I mean, the `var` keyword will says to compiler: "Accept only this type".

You're wrong, the `var` keyword (in parameters) has two meanings to the compiler in Object Pascal; the first is "this thing is modifiable inside the subprogram", the second is "this thing is passed by reference".

The `const` keyword in Delphi parameters was added to provide a foil to the `var` keyword, explicitly saying "this thing is **not** modifiable by the subprogram".

**Side note:** The `var` keyword for parameters, along with `const` and `out` are [allowed to be typeless](http://docwiki.embarcadero.com/RADStudio/Berlin/en/Parameters_%28Delphi%29#Untyped_Parameters). This typeless parameter form goes all the way back to the [UCSD Pascal](http://www.gnu-pascal.de/gpc/var.html) days -- and have been in Turbo Pascal since at least Version 3, which was before objects were added. (Here's [the manual](http://bitsavers.informatik.uni-stuttgart.de/pdf/borland/turbo_pascal/TURBO_Pascal_Reference_Manual_CPM_Version_3_Dec88.pdf) as a PDF, the page you want is PDF page 129 [marked 115].)

In Delphi/Object Pascal `Function Fn( X : Object ): Integer`, and Java `int fn( Object x )`, and the C++ or C# equivalent these are all the same: the parameter is _not_ specifically/exclusively the type, but "instance of the class", which does mean there's no way in those languages to actually specify "only this type". -- This design decision makes a lot of sense in the context of those languages.

In the context of both Delphi and Java, they are both single-inheritance languages (see [note 7](https://en.wikipedia.org/wiki/Java_%28programming_language%29#Notes)) with single-root object hierarchies. Because of this, allowing a parameter of the root-type "`Object` in both cases" to refer to "this, and anything derived from it" means that you could pass am object of `Window` to `fn` because that single-inheritance means that it _is_ an `Object` because that inheritance-line goes directly [and linearly] to `Object`.

C++ is different, it [doesn't have a single base object](http://stackoverflow.com/a/11747470/608963). However, IIRC [my C++ is rusty], coming from the implicit-conversion happy background of C, it too chose to make the parameter (at least accept) anything derived from the type. ([This](https://bytes.com/topic/c/answers/578257-static-vs-dynamic-dispatch#post2266072) comes close to what I'm trying to get at, in a way.)

**Comment by mdbs99** [comment]
> You're wrong, the var keyword (in parameters) has two meanings to the compiler in Object Pascal; the first is "this thing is modifiable inside the subprogram", the second is "this thing is passed by reference".

@OneWingedShark 
Look this [thread](http://www.hu.freepascal.org/lists/fpc-devel/2010-May/019898.html). If you do not want to read everything, take a look on the 2d Florian Klaempfl's answer [here](http://www.hu.freepascal.org/lists/fpc-devel/2010-May/019945.html).

That's what I was talk about.

**Comment by OneWingedShark** [comment]
@mdbs99 -- That example code illustrates, tangentially, the problem that I'm getting at.

    {$mode objfpc}
    type
      tc1 = class
      end;
    
      tc2 = class(tc1)
      end;
    
      tc3 = class(tc2)
      end;
    
    procedure p(var c : tc1);
      begin
        c:=tc2.create;
      end;
    
    var
      c3 : tc3;
    
    begin
      p(c3);
    end.

The reason that the above was, at all, ever considered valid is because in Delphi/Object Pascal there is no way to indicate whether or not you're referring to "*this type exactly*" or "*this type, and anything derived from it*"

The `var` parameter mode has nothing to do with this issue.

**Comment by OneWingedShark** [comment]
> There was an ACM paper on it awhile back, they used Modula-2; sorry, I cannot remember the title, date, or author.

Found it:  
[Simple and Effective Link-Time Optimization of Modula-3 Programs](http://dabamirror.sci-hub.io/0907a19f84f6a6fc61cc0416a09a9958/fernndez1995.pdf)

**Comment by yegor256** [comment]
@OneWingedShark I'm closing this, since we don't have types anymore in EO
