### ISSUE TITLE
Mutable objects in EO

### ISSUE THREAD

**Issue by IamMaxim** [cqfn/eo#412]
We are currently trying to create mappings from Java to EO. Consider this snippet in Java:
```java
class A {
    int i = 0;
    int j = 0;

    public void inc() {
        i++;
        j++;
    }
}

class Scratch {
    public static void main(String[] args) {
        A j = new A();

        for (int i = 0; i < 10; i++) {
            j.inc();
        }
    }
}
```

The only mechanism for storing mutable data in EO is `memory`, which can only store primitive data.
This prevents us from straightforward conversion. What idiomatic EO approach do you suggest to apply in this case?

**Comment by yegor256** [comment]
@IamMaxim why can't you make it like this:

```
[] > A
  memory > i
  memory > j
  [] > inc
    seq > @
      i.write (i.add 1)
      i.write (i.add 1)
```

**Comment by IamMaxim** [comment]
The problem is mostly about `main` method, which creates A instances. Consider this example, which dynamically changes instance of A:
```java
class A {
    int i = 0;
    int j = 0;

    public void inc() {
        i++;
        j++;
    }
}

class Scratch {
    public static void main(String[] args) {
        A j = new A();

        for (int i = 0; i < 10; i++) {
            if (i % 3 == 0)
                j = new A();

            j.inc();
        }
    }
}
```

**Comment by yegor256** [comment]
@IamMaxim I still don't see a problem here. Just make a new object `A` and that's it.

**Comment by yegor256** [comment]
@IamMaxim let's discuss it in c2eo project
