### ISSUE TITLE
Argument name shadows return field name: is this a feature?

### ISSUE THREAD

**Issue by dours** [cqfn/eo#416]
First, a concrete failing test: one cannot store an object with field "i" in an array, because it is impossible to read the field back (because the first argument of array.get is also called "i", so (arr.get 0).i returns 0, not 11):
```
[] > array-get-arg-name-shadows-field-name
  [] > a
    11 > i
  (* a) > arr
  (arr.get 0).i.eq 11 > @
```
Same test with "j" instead of "i" passes (as expected).

Second, a more general test (also fails for a similar reason: (f z).x equals z for all z):
```
[] > arg-name-shadows-field-name
  [x] > f
    [] > @
      123 > x
  (f 567).x.eq 123 > @
```

Is this a bug or a feature?

**Comment by yegor256** [comment]
@dours this definitely is a feature. This is how decoration works. What's in the object is more important vs. what's in the decoratee.
