### ISSUE TITLE
Shared vs distinct roots.

### ISSUE THREAD

**Issue by OneWingedShark** [cqfn/eo#42]
Delphi and Java have what is at times an excellent facility and other times not so helpful -- the single root-class "Object". One of the good things is that you have a standard basic and guaranteed interface for all your types... one of the bad things is that it forces the inclusion of things that otherwise might be senseless for the particular type you want to model. (For example, if you're modeling a memory-mapped I/O port you **don't** want a `copy` method, because there is [hopefully] only one such port.)

**Comment by yegor256** [comment]
@OneWingedShark the points you're raising here are really interesting and valid. However, there are too many of them for a single ticket. Can you please split it on two/three? (You can edit this ticket too, to make it smaller)

**Comment by OneWingedShark** [comment]
Ok, I moved the exceptions to #44 and Messages to #45.

(Though they are all related in the conceptual levels: exceptions are a special message; exceptions can be modeled as either a single type, or as a class of types [influencing how the language handles exceptions]; and the single root vs multiple-root vs single-type question applies to both exceptions and types, and may be answered differently for each.)

**Comment by yegor256** [comment]
@OneWingedShark we don't have types in EO anymore, that's why no `Object` type
