### ISSUE TITLE
check date/time of files at OptimizeMojo

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#420]
`OptimizeMojo` does this:

```
            if (tojo.exists(AssembleMojo.ATTR_XMIR2)) {
                Logger.debug(
                    this, "Already optimized %s to %s",
                    Save.rel(src), Save.rel(Paths.get(tojo.get(AssembleMojo.ATTR_XMIR2)))
                );
                continue;
            }
```

Instead, it should also check the date/time of the XMIR2 file. If it exists by is older than the source, we should optimize.

Let's not forget to unit-test this.

**Comment by yegor256** [comment]
@andreoss please, help us with this (budget is 30)

**Comment by andreoss** [comment]
@yegor256 Done in #442. Please close

**Comment by andreoss** [comment]
@yegor256 It's still open
