### ISSUE TITLE
check date/time of files in TranspilerCanonical

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#421]
`TranspilerCanonical` does this:

```java
        if (Files.exists(target)) {
            Logger.info(
                this, "XMIR %s (%s) already transpiled to %s",
                Save.rel(file), name, Save.rel(target)
            );
        } else {
```

Instead, it should also check the date/time of the target file. If it's older than the source, we should transpile.

Let's not forget to unit-test this.

**Comment by yegor256** [comment]
@andreoss please, help us with this (budget is 30)

**Comment by andreoss** [comment]
@yegor256 Done in https://github.com/cqfn/eo/pull/453. Please close

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#421` is not assigned, can't get performer
