### ISSUE TITLE
as-ascii-char for int atom

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#422]
We need something like this to support the char type from the c language

**Comment by yegor256** [comment]
@IngeniariusSoftware I think it won't make sense, since `int` has 8 bytes. I suggest to do it this way:

```
40-00 > b
(b.part 0 1).as-char > c
c.eq 'A'
```

as-char will take the first byte and make it a char. If there are more than one byte, it will return `[]` (an exception)

**Comment by IngeniariusSoftware** [comment]
@yegor256, ok, I will try to check this

**Comment by yegor256** [comment]
@IngeniariusSoftware you are welcome to submit a PR

**Comment by yegor256** [comment]
@IngeniariusSoftware still working on this?

**Comment by IngeniariusSoftware** [comment]
@yegor256 not yet

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#422` is not assigned, can't get performer
