### ISSUE TITLE
as-ascii-int for char atom

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#423]
We need something like this to support the char type from the c language

**Comment by yegor256** [comment]
@IngeniariusSoftware why `ascii`? I would just make `char.as-int`.

**Comment by IngeniariusSoftware** [comment]
@yegor256 , ok, thanks

**Comment by yegor256** [comment]
@IngeniariusSoftware you are welcome to submit a pull request

**Comment by yegor256** [comment]
@IngeniariusSoftware still working on this?

**Comment by IngeniariusSoftware** [comment]
@yegor256 not yet
