### ISSUE TITLE
too-many-attributes 

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#424]
This code doesn't compile:

```
+package c2eo

[args...] > app

  TRUE > @

  [] > a
  [] > b
  [] > c
  [] > d
  [] > e
  [] > f
  [] > g
```

Error:

![image](https://user-images.githubusercontent.com/33983579/141752110-9ca43d49-8d75-408c-a443-0890c5f041a6.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware this is by design. We don't want to have objects with too many free attributes, it's a bad practice.
