### ISSUE TITLE
JUL to SLF4J logging doesn't work not for eo-runtime

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#429]
JUL is being used in `Dataized` in order to log dataization messages. However, we don't see them in the log, because JUL-to-SLF4J bridge is not turned on in the `eo-runtime` module. This is how it should be turned on, somewhere _before_ all tests start:

```java
SLF4JBridgeHandler.install();
Logger.getLogger("").setLevel(Level.FINE);
```

We should find a way how to do this. Maybe this one will be helpful: https://stackoverflow.com/questions/43282798/in-junit-5-how-to-run-code-before-all-tests

**Comment by yegor256** [comment]
@marceloamadeu please help us here

**Comment by marceloamadeu** [comment]
@yegor256 It was very useful.

> We should find a way how to do this. Maybe this one will be helpful: https://stackoverflow.com/questions/43282798/in-junit-5-how-to-run-code-before-all-tests

The following links also helped a lot:

- [Extension Model](https://junit.org/junit5/docs/current/user-guide/#extensions)
- [Configuration Parameters](https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-build-maven-config-params)
- [Automatic Extension Registration](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic)

**Comment by yegor256** [comment]
@marceloamadeu still doesn't work, after the merge of your PR

**Comment by marceloamadeu** [comment]
@yegor256 sorry i will check...

**Comment by yegor256** [comment]
@andreoss can you take a look?

**Comment by andreoss** [comment]
@yegor256 Yes, please assign

**Comment by yegor256** [comment]
@andreoss yours, go ahead pls

**Comment by andreoss** [comment]
@yegor256 This can be closed.Tthough for now logging can cause problems like 
https://github.com/cqfn/eo/issues/520

**Comment by yegor256** [comment]
@andreoss thanks!
