### ISSUE TITLE
Change return type of Book#asText in the example

### ISSUE THREAD

**Issue by Tradunsky** [cqfn/eo#43]
Does String type suppose to be an elegant type?

I thought that java's Object#toString is often misused, perhaps it is the case.

I suggest we change it with Text type.

**Comment by yegor256** [comment]
@Tradunsky I think I agree. Text would be a better name. Can you submit a pull request?

**Comment by Tradunsky** [comment]
@yegor256 Yep, sure. #63

**Comment by pa9ey** [comment]
@Tradunsky Have you got an examples of what you mean by Object#toString being misused?

Also, if Text would be for human-readable text, why wouldn't a book title count as Text? Or even an ISBN for that matter?

**Comment by Tradunsky** [comment]
@pa9ey 
The intention to get rid of String might be a good idea, but first of all we should think of a problem that we are going to solve.

Performing code review for youth engineers I saw some interesting logic based on Type#toString result. According to javadoc: 
> Returns a string representation of the object. In general, the
> {@code toString} method returns a string that
> **"textually represents"** this object. The result should
> be a concise but informative representation that is easy for a
> **person to read**.

So, if the method asText supposed to be useful for humans (debugging at least), it should not provide  developers with methods for processing it incorrectly.

The second problem is related to representation of basic data as String(or Text). For example, why do we should represent money as string literal? Shall this kind of a type has their own representation, like without quotes (1$, 25uah, 100500rub)? I know that we should choose the level of abstraction in the case of ISBN or Person name, but it looks strange to choose Text for one word or a number. However, the source of that data might be a unknown and it would be easy to create some complex objects from basic type like String.

**Comment by yegor256** [comment]
@Tradunsky I think this ticket can be closed as fixed?

**Comment by Tradunsky** [comment]
@yegor256 It is up to you

**Comment by yegor256** [comment]
@Tradunsky not relevant anymore, thanks for submitting though
