### ISSUE TITLE
.@ must calculate only once

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#430]

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.10`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#567](https://github.com/cqfn/eo/issues/567) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#567](https://github.com/cqfn/eo/issues/567) is solved here.
