### ISSUE TITLE
too many atoms

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#431]
I believe the following atoms are redundant. We can implement their functionality in EO, instead of Java. Let's remove them and implement them in EO.

  * `array.empty` (let's rename to `array.is-empty`)
  * `float.geq` (the same as `eq + or + greater`)
  * `float.leq` (same as `less or eq`)
  * `float.less` (same as `not greater and not eq`)
  * `float.neg` (same as `mul -1`)
  * `float.neq` (same as `not eq`)
  * `float.signum` (same as `self / self.abs`)

The same for `int`.

**Comment by andreoss** [comment]
@yegor256 Done in two parts. Please close.

1) https://github.com/cqfn/eo/pull/452
2) https://github.com/cqfn/eo/pull/477

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#431` is not assigned, can't get performer
