### ISSUE TITLE
Windows 10 illegal characters

### ISSUE THREAD

**Issue by egorklementev** [cqfn/eo#433]
When trying to compile `mvn clean compile` on Windows 10 the following errors arise:
```
COMPILATION ERROR : 
.../target/generated-sources/EOorg/EOeolang/EObytes.java:[14,66] illegal escape character
.../target/generated-sources/EOorg/EOeolang/EObytes.java:[14,90] illegal escape character
.../target/generated-sources/EOorg/EOeolang/EOstring.java:[14,92] illegal escape character
...
100 errors 
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
```

Full report:
https://github.com/egorklementev/j2eo/runs/4240664886?check_suite_focus=true

**Comment by yegor256** [comment]
@egorklementev thanks for reporting, can you fix it?

**Comment by egorklementev** [comment]
It seems like in the following generated Java code `\` symbol (in a `source` string) is not liked by Java on Windows. Even my Vim extension is not happy with that.
```java
package EOorg.EOeolang;

import org.eolang.*;

@XmirObject(name = "bytes", oname = "bytes", source = "D:\projects\Java\eo\sandbox\canonical\target\04-pull\org\eolang\bytes.eo")
public final class EObytes extends PhDefault {
  public EObytes(final Phi sigma) {...}
}
```

And, unfortunately, I don't know how to fix it.

**Comment by yegor256** [comment]
@egorklementev it's a bug in `to-java.xsl`: this is where we generate this code. We should replace all `\` symbols with `\\`. Shouldn't be hard to do.

**Comment by yegor256** [comment]
@egorklementev this bug is fixed (but something else is still broken, please create a new ticket)

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#433` is not assigned, can't get performer
