### ISSUE TITLE
"\n" is not parseable in a string

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#437]
This will not print two lines:

```
[args...] > app
  stdout
    "Hello \n friend"
```

But it should. The symbol `\n` should be parsed as `\u000a`.

Also, we should parse `\t`, `\r`, and others, which are used in Java.

I believe, we should make the necessary changes in `XeListener`. Also, let's not forget to test it, making a new YAML for `PacksTest`

**Comment by yegor256** [comment]
@marceloamadeu  please help us with this one

**Comment by marceloamadeu** [comment]
@yegor256 I'm not able to simulate the error here... Any tips on how I can do this?
Tks

**Comment by yegor256** [comment]
@marceloamadeu I would create a new YAML test for `PackTest`, which would just parse EO to XML. Then, with XPath assertions I would check that the right content is placed in XML

**Comment by marceloamadeu** [comment]
@yegor256 I did some tests with `\n` and also with `\\u000a`.

With `\n` the result was:

`<![CDATA[ Hello friend ]]>`


**Tests with \n**
```
+package org.eolang
+alias stdout org.eolang.io.stdout
+junit

[] > escape-sequences
  stdout > @
    "Hello \n friend"
```

**escape-sequences-tests.xmir**
```
<objects>
      <o line="27" name="escape-sequences">
         <o base="stdout" line="28" name="@">
            <o base="string" data="string" line="29">Hello \n friend</o>
         </o>
      </o>
   </objects>
```

**EOescape_sequencesTest.xml**
```
<testcase name="testWorks" classname="EOorg.EOeolang.EOescape_sequencesTest" time="0.001">
   <system-out>
      <![CDATA[ Hello friend ]]>
   </system-out>
</testcase>
```

----------------------------------------------------------------------------------------------------------------------
**Tests with \\u000a**
```
+package org.eolang
+alias stdout org.eolang.io.stdout
+junit

[] > escape-sequences
  stdout > @
    "Hello \\u000a friend"
```
**escape-sequences-tests.xmir**
```
<objects>
      <o line="27" name="escape-sequences">
         <o base="stdout" line="28" name="@">
            <o base="string" data="string" line="29">Hello \\u000a friend</o>
         </o>
      </o>
   </objects>
```

**EOescape_sequencesTest.xml**
```
<testcase name="testWorks" classname="EOorg.EOeolang.EOescape_sequencesTest" time="0.002">
   <system-out>
      <![CDATA[ Hello \u000a friend ]]>
   </system-out>
</testcase>
```

**Comment by yegor256** [comment]
@marceloamadeu yes, this is wrong. This is what is expected:

```
[] > escape-sequences
  stdout > @
    "Hello \n friend"

<objects>
      <o line="27" name="escape-sequences">
         <o base="stdout" line="28" name="@">
            <o base="string" data="string" line="29">Hello &x0A; friend</o>
         </o>
      </o>
   </objects>
```

**Comment by andreoss** [comment]
@yegor256 I guess, it can be closed in favor of #480.

**Comment by marceloamadeu** [comment]
@andreoss Thanks for helping.

@yegor256 Sorry for the delay. I hope I can help in the next issues

**Comment by yegor256** [comment]
@andreoss @marceloamadeu thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#437` is not assigned, can't get performer
