### ISSUE TITLE
return object from mutable code: should it be possible?

### ISSUE THREAD

**Issue by dours** [cqfn/eo#439]
A test below fails, because seq dataizes all its arguments. This prohibits to return an object from a function. A possible workaround is to pass a return cage to assign return result to as an argument. 
But maybe it's ok to also add a gray object like seqReturn, which dataizes all its arguments except the last one? 
```
[] > return-object-from-a-mutable-code
  [z] > a
  [y] > mkA
    cage > x
    seq > @
      x.write
        a y
      x
  (mkA 7).z.eq 7 > @
```

**Comment by yegor256** [comment]
@dours maybe let's just make `seq` return the object? It will dataize it and then return the object, not the data. WDYT?

**Comment by dours** [comment]
@yegor256 it shouldn't help with my example, because a is not dataizable => the first step (dataize it) leads to exception and the second (return the object) never happens

**Comment by IamMaxim** [comment]
@yegor256 reminder about returning last object without dataization

**Comment by yegor256** [comment]
@dours @IamMaxim I believe it's fixed in 4470f4df

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#439` is not assigned, can't get performer
