### ISSUE TITLE
Exceptions: Single type verses rooted heirarchies?

### ISSUE THREAD

**Issue by OneWingedShark** [cqfn/eo#44]
Exceptions can be a funny beast: they can be considered their own entities/types, like in Ada where there's no commonality between `Constraint_Error` and `Assertion_Error` other than they're exceptions -- and this makes sense: it's rather senseless to allow exceptions to be treated like a family of types (Class) so that you could simply recast `Constraint_Error` as `Assertion_Error` (though similar-in-effect re-raising an exception is **not** the same thing). Another good point about exceptions not sharing a common ancestor is that you can make it impossible to catch the "root exception". -- On the other hand, am exception-hierarchy **does** allow handling exceptions by "this [exception-]type and everything derived from it". (IOW it's a design decision with pros and cons on both sides.)

As in Comment/Issue #42 this is another question that should be asked of exceptions about hierarchies, and it can be orthogonal to the answer given there about the object hierarchies. Of course they could be the same and unified, but as exceptions are for exceptional conditions perhaps they should be treated as special cases.

**Comment by yegor256** [comment]
@OneWingedShark I think that we should not care about the type of exception, just like it's done in C++: any object of any type can be thrown. And, since we don't have type introspection, we can only catch "whatever is there". Thus, we will make life easier: no matter what you throw, we can only once. Here is what I think about in more details: http://www.yegor256.com/2015/07/28/checked-vs-unchecked-exceptions.html

**Comment by Glusk2** [comment]
@OneWingedShark  If you only use one type of exceptions, the problems that you speak of disappear.
@yegor256 Is there really any catching going on (as in Java `try-catch` block)? I like the [example](https://github.com/yegor256/eo#exceptions) but so far it's only for exception throwing. I guess catching is then done in a similar way - if object returned isn't of the right type, re-throw it up the call stack?
Anyway, this issue can be closed, right?

**Comment by OneWingedShark** [comment]
@Glusk2 Not really, then you're stuck with what's essentially a "something went wrong"-message.

**Comment by yegor256** [comment]
@OneWingedShark we don't have exceptions in EO
