### ISSUE TITLE
empty byte array syntax

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#443]
Empty byte array should be spelled as `-`, for example:

```
01-FE-A2.as-string
01-FE.as-string
01-.as-string  # one-element array (works now)
-.as-string  # empty array (doesn't work)
```

This is not supported now. Let's fix and test using `full-syntax.yaml` and `PacksTest`.

**Comment by yegor256** [comment]
@andreoss please, fix this

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#443](https://github.com/cqfn/eo/issues/443); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#443](https://github.com/cqfn/eo/issues/443); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#443](https://github.com/cqfn/eo/issues/443); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#443](https://github.com/cqfn/eo/issues/443); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
@yegor256 Can we use `--` instead for empty byte array? (Which makes more sense to me, because byte is two symbols currently).
Using `-` causing problems with negative `INT` and `FLOAT`, but I guess this can be solved by handling `-` as a separate token

**Comment by yegor256** [comment]
@andreoss yes, `--` looks like a good idea!

**Comment by andreoss** [comment]
@yegor256 Done in https://github.com/cqfn/eo/pull/478 
Please close.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#443` is not assigned, can't get performer
