### ISSUE TITLE
Modelling double-linked list with cage fails

### ISSUE THREAD

**Issue by dours** [cqfn/eo#449]
Here is a simplified model of a double-linked list with the help of object references (cage). First points to last and last points to first. It fails with "You can't overwrite static expression".
```
[] > cyclic-ref
  [ptr value] > pair
  cage > first
  cage > last
  seq > @
    first.write (pair (last 1))
    last.write (pair (first 2))
    and.
      first.ptr.value.eq 2
      first.ptr.ptr.value.eq 1
```

**Comment by dours** [comment]
oops, the test is wrong, `pair (last 1)` instead of `pair last 1`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#449` is not assigned, can't get performer
