### ISSUE TITLE
adding bitwise operations

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#451]
Implementation of bitwise operations for int atom (bit_or, bit_and, bit_xor, bit_not, shift_left, shift_right)

@yegor256 , what do you think about adding these operations?

**Comment by yegor256** [comment]
@IngeniariusSoftware good idea. I would call them this way:

```
.or
.xor
.and
.not
.lshift
.rshift
```

**Comment by yegor256** [comment]
@IngeniariusSoftware you are welcome to submit a PR

**Comment by IngeniariusSoftware** [comment]
@yegor256, done https://github.com/cqfn/eo/pull/456

**Comment by yegor256** [comment]
@IngeniariusSoftware it's "done" when PR is merged :)

**Comment by yegor256** [comment]
@IngeniariusSoftware thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#451` is not assigned, can't get performer
