### ISSUE TITLE
MainTest is flaky 

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#455]
1) Fails on Windows 
https://github.com/cqfn/eo/runs/4331203668?check_suite_focus=true
2) Fails in presence of `_JAVA_OPTIONS` or `_JAVA_TOOL_OPTIONS`

**Comment by yegor256** [comment]
@andreoss do you know how to fix this?

**Comment by andreoss** [comment]
@yegor256 I don't see a point in running a new java process in order to test Main.
`Main` can be refactored to be testable (now it consists only of static methods)`
Otherwise the tests can be less strict, i.e 1) do not use unicode 2) match only last line in order to avoid jvm initialization output

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#455](https://github.com/cqfn/eo/issues/455); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@andreoss we are using a new JVM instance on purpose: to let `Main` configure logging. If you test it inside the same JVM, it's hard to guarantee the isolation of a test. As for the testability of `Main`, I agree, would be great to refactor it so that there is only one static method `main()`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#455](https://github.com/cqfn/eo/issues/455); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#455](https://github.com/cqfn/eo/issues/455); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
Closed in favor of https://github.com/cqfn/eo/issues/465

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#455](https://github.com/cqfn/eo/issues/455); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
