### ISSUE TITLE
bitwise operations are wrongly placed

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#457]
@IngeniariusSoftware I believe, we made a mistake in #452. These operators should be in `bytes`, not in `int`. In order to do `left` on `int` we should do:

```
42 > a
(a.bytes.left 4).as-int
```

I suggest we fix this.

**Comment by yegor256** [comment]
@IngeniariusSoftware can you move them?

**Comment by IngeniariusSoftware** [comment]
@yegor256 , ok I'll do it

**Comment by IngeniariusSoftware** [comment]
@yegor256 https://github.com/cqfn/eo/pull/458

**Comment by yegor256** [comment]
@IngeniariusSoftware thanks! you can close this ticket, it's yours.

**Comment by yegor256** [comment]
@IngeniariusSoftware thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#457` is not assigned, can't get performer
