### ISSUE TITLE
"identical" atom

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#460]
I'm thinking about introducing a new atom identical, which will accept two arguments and will become TRUE if they both are identical objects, maybe assigned to different attributes:

```
[] > test-identical
  42 > x
  x > y
  and. > @
    (identical x 42).eq TRUE
    (identical x y).eq TRUE
    (identical x 7).eq FALSE
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#460` is not assigned, can't get performer
