### ISSUE TITLE
build is broken on Windows

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#465]
There are some issues with encoding. Let's fix.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#465](https://github.com/cqfn/eo/issues/465); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by JuptaCore** [comment]
Acctualy i don't understand how it's work but anyway i try to help.
What i am did?
1) Clone repository of EO
2) Try run command "mvn clean install -Pqulice' in cmd 
3) Get erorr "is not recognized as an internal or external command, operable program or batch file"

maybe i do something wrong?

**Comment by yegor256** [comment]
@yegor256 you need to install Java 11+ and Maven 3.2+ first.

**Comment by JuptaCore** [comment]
I am download java and maven and trying to run this command ''mvn clean install -Pqulice"
and got this error

![image](https://user-images.githubusercontent.com/87895348/144597005-a24f771e-fe18-4a64-8ef7-40d8e21dd27f.png)

**Comment by JuptaCore** [comment]
next command "mvn clean install -Pqulice -e -X" added -e and -X
and got this 
![image](https://user-images.githubusercontent.com/87895348/144597579-e6736dc4-5598-4b39-856f-4aa3e5e9fc4f.png)
![image](https://user-images.githubusercontent.com/87895348/144597653-501050f5-868b-4d37-af9e-2af48ac80d61.png)

**Comment by JuptaCore** [comment]
I followed in https://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
where does it say that i am missed pom.xml

![image](https://user-images.githubusercontent.com/87895348/144602922-b6653729-36e0-4d72-91a2-8ab3136eab24.png)

**Comment by yegor256** [comment]
@JuptaCore you have to run `mvn` while staying in the code base you just cloned from GitHub

**Comment by JuptaCore** [comment]
got this error
![image](https://user-images.githubusercontent.com/87895348/144616946-d724d5fd-5f5c-418a-92d2-4fc26cdbed43.png)


and this 
![image](https://user-images.githubusercontent.com/87895348/144616746-130cbfac-e2c7-4f47-8991-39e25e691da0.png)
![image](https://user-images.githubusercontent.com/87895348/144616792-bb283ce9-7dfd-4cd8-9350-30f47aa86b69.png)

**Comment by yegor256** [comment]
@JuptaCore this is the bug we want to fix

**Comment by yegor256** [comment]
@andreoss do you have Windows platform? Can you fix this please?

**Comment by andreoss** [comment]
@yegor256 Don't have a Win machine to debug this.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#465](https://github.com/cqfn/eo/issues/465); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@baudoliver7 please help us here

**Comment by baudoliver7** [comment]
@yegor256 Ok :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#465](https://github.com/cqfn/eo/issues/465); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
