### ISSUE TITLE
recursive update exception

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#468]
code
```c
+package sandbox

[args...] > app
  memory > n

  [] > func
    if. > @
      n.greater 0
      seq
        n.write (n.sub 1)
        func
        TRUE
      TRUE

  seq > @
    n.write 4
    func
    TRUE

```

exception

![image](https://user-images.githubusercontent.com/33983579/144760093-f058e78b-64ab-4cdf-9163-7acb564d08bb.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware definitely a bug, thanks for reporting

**Comment by yegor256** [comment]
@IngeniariusSoftware this code works:

```
+package sandbox

[args...] > app
  memory > n
  [] > func
    if. > @
      n.greater 0
      seq
        n.write (n.sub 1)
        ^.func
        TRUE
      TRUE

  seq > @
    n.write 4
    func
    TRUE
```

Pay attention, I replaced `func` with `^.func`. I'm trying to investigate why...

**Comment by yegor256** [comment]
@IngeniariusSoftware it seems that this not a bug, but a feature. You do this (I'm simplifying):

```
[] > app
  [] > func
    seq > @
      func
```

Here, the third line is `new func(func)`. You make an new copy of the abstract object `func`, setting its parent to... itself. Of course, it leads to endless recursion later.

On the other hand:

```
[] > app
  [] > func
    seq > @
      ^.func
```

Here, you take the attribute `func`  from the object `app`. This object already exists and its parent is `app`. No endless recursion.
