### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by alexpanov** [cqfn/eo#47]
There have been other issues that sort of touch this topic.

However, I think that the issue of interoperability is crucial for *any sort of adoption*. Unless adoption is not a goal, there has to be an explicit focus on interoperability.

I am aware that as of now, the JVM is the only target platform, so that makes things a bit easier. It is true that most of the JVM libraries are garbage, especially the older ones. Yet, many of them save time and as a consequence, money and that matters.

**Comment by stain** [comment]
Also discussed in #52.

**Comment by Tertioptus** [comment]
I think there should be a CPU or PC abstraction that handles all interoperability.  It would basically force the EO developer to request that the host thread/PC/CPU/etc run some program with certain parameters.  This way we don't bail monoglot programmers out, who really should be writing low-level code in other languages that are better suited for the job.  In such case these programs are not packaged in the application itself as accessible libraries.  They can be executable, cross-platform jars, that are packaged with the build files.  They can be running processes on your typical OS.  Shell scripts and the like. External/low-level processes in the EO platform should just be allowed to be registered, requested, and hooked during bootstrapping, but not actually apart of whatever container the EO application exists in. 

For example, if you want to controls IOs on a RaspberryPi, create a little app in Java, C++, C, what have you.  Where you may have to write imperative code for performance.  Then just register a Process abstraction of the program (probably delivered with the build files) with the PC abstraction.

**Comment by Tertioptus** [comment]
Actually instead of PC, it should be OS.

**Comment by yegor256** [comment]
@alexpanov I don't really understand the "bug" here. What is wrong with our current README and what do you want us to fix? Check this out please: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by alexpanov** [comment]
@yegor256 fair question. The 'bug' here is that the README does not outline the position on interoperability with existing JVM libraries.
I am arguing that there needs to be at least some focus on it.
Otherwise, it is also acceptable to state that interoperability is *not* a goal/priority if it is the case.

**Comment by yegor256** [comment]
@alexpanov got it, but how is this ticket different from #52?

**Comment by alexpanov** [comment]
@yegor256 I'd love to know that too =)

**Comment by yegor256** [comment]
@alexpanov we compile to Java now. Later, we'll have EO-to-Python and other languages.
