### ISSUE TITLE
catch unused aliases

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#471]
Let's create an additional XSL check in eo-parser, which will catch unused aliases. For example, in this code the alias `stdout` is unused and has to be removed:

```
+alias org.eolang.io.stdout

[x] > foo
  x.div 42 > @
```

**Comment by yegor256** [comment]
@andreoss can you fix this?

**Comment by andreoss** [comment]
@yegor256 Taken

**Comment by andreoss** [comment]
@yegor256 Done. Please, close

**Comment by yegor256** [comment]
@andreoss thanks!
