### ISSUE TITLE
multi-line string literals

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#472]
Let's add this syntax:

```
[] > foo
  stdout > @
    """
    Hello, dude!
      How are you?
    """
```

This should be printed:

```
Hello, dude!
  How are you?
```

**Comment by andreoss** [comment]
@yegor256 Ready to take this

**Comment by yegor256** [comment]
@andreoss sure, go ahead

**Comment by andreoss** [comment]
@yegor256 Done, please close

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#472](https://github.com/cqfn/eo/issues/472); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#472](https://github.com/cqfn/eo/issues/472); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
