### ISSUE TITLE
Build failure of example in README

### ISSUE THREAD

**Issue by admin1475963** [cqfn/eo#476]
`mvn clean test` failed in example [https://github.com/cqfn/eo#quick-start](url).
Here is log:
[log.txt](https://github.com/cqfn/eo/files/7677484/log.txt)

**Comment by yegor256** [comment]
@admin1475963 fixed in bc7f733e thanks for reporting!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#476` is not assigned, can't get performer
