### ISSUE TITLE
It is not possible to use previous versions of EO, because runtime version is hardcoded in library .eo files

### ISSUE THREAD

**Issue by dours** [cqfn/eo#479]
eo-maven-plugin of any version loads library .eo files from objectionary. These files have runtime version hardcoded in them, and it is the latest version of runtime. Thus, I cannot use EO complier version, say, 0.19 with runtime 0.19, I must use it with the latest runtime, which may be incompatible with the desired version of compiler, or it may have new bugs, which I want to avoid until they are fixed.

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@dours try version 0.20.1. Now you can specify `hash` in `pom.xml`, which you find here: https://github.com/yegor256/objectionary/commits/master

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#479` is not assigned, can't get performer
