### ISSUE TITLE
Escape sequences in strings

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#480]
Grammar does not handle escape sequences in strings
Bot `"\"` and `"\\"` allowed, only the second one compiles to java 

`"\"\""` is not parsed correctly

```
# Compiles to malfomed Java code
[] > backslash
  eq. > @
    "\".length
    1
    
# Works
[] > backslash
  eq. > @
    "\\".length
    1

# Unparsable
[] > quotes
  eq. > @
    "\"\"".length
    2
```

**Comment by yegor256** [comment]
@andreoss please, fix this

**Comment by andreoss** [comment]
@yegor256 Please assign to me (cannot self-assign). 
EO string should be grammatically identical to Java syntax?

**Comment by yegor256** [comment]
@andreoss yes, in strings we should fully support Java syntax

**Comment by andreoss** [comment]
@yegor256 Done. Please close.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#480` is not assigned, can't get performer
