### ISSUE TITLE
how use the heap?

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#483]
I tried using the heap but something went wrong
code
```java
[arg] > app
  heap 1024 > h
  h.pointer 0 1 > ptr
  ptr.block > int_b
    8
    [b] (b.as-int > @)
  seq > @
    int_b.write 5
    stdout (sprintf "%d" int_b)
    TRUE
```

result
![image](https://user-images.githubusercontent.com/33983579/145718672-691c6a96-c827-46fa-8905-f874698f7845.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware you can't write int to block. You have to write bytes:

```
[arg] > app
  heap 1024 > h
  h.pointer 0 1 > ptr
  ptr.block > int_b
    8
    [b] (b.as-int > @)
  seq > @
    int_b.write 5.as-bytes
    stdout (sprintf "%d" int_b)
    TRUE
```

Pay attention to `int_b.write 5.as-bytes`.

**Comment by yegor256** [comment]
@IngeniariusSoftware I added verification of types: fa40c17b

**Comment by IngeniariusSoftware** [comment]
@yegor256, thanks!

**Comment by IngeniariusSoftware** [comment]
@yegor256 then maybe there is a typo in 216

![image](https://user-images.githubusercontent.com/33983579/145719821-561cfd05-906d-4400-bf40-6505dd7b3173.png)
