### ISSUE TITLE
alias syntax clarification

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#486]
These lines produce different XML
```
+alias stdout org.eolang.io.stdout
+alias org.eolang.io.stdout
```

The produce different XML code
1) 
```xml
         <head>alias</head>
         <tail>stdout org.eolang.io.stdout</tail>
         <part>stdout</part>
         <part>org.eolang.io.stdout</part>
```
2) 
```        xml
         <head>alias</head>
         <tail>org.eolang.io.stdout</tail>
         <part>org.eolang.io.stdout</part>
```

Proposal:
XML outputs should be identical

**Comment by yegor256** [comment]
@andreoss well, the parsing step should not improvise and change the code. It should produce XMIR as was EO sources presented. Later, we can introduce an additional XSL transformation, which would do the optimization of aliases and unify them.

**Comment by andreoss** [comment]
@yegor256 
Actually `expand-aliases` and `resolve-aliases` already do what I had in mind.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#486` is not assigned, can't get performer
