### ISSUE TITLE
ci build should run xcop

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#488]
rultor runs xcop on merge, so should CI build

Also, it would be nice to slip tests and linters in two separate jobs, as it was done in cactoos
https://github.com/yegor256/cactoos/blob/master/.github/workflows/build.yml#L30-35

**Comment by yegor256** [comment]
@andreoss can you do this?

**Comment by andreoss** [comment]
@yegor256 Yes, please assign to me.

**Comment by andreoss** [comment]
@yegor256 Done.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#488](https://github.com/cqfn/eo/issues/488); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
