### ISSUE TITLE
error when using prefix ... converts array to vararg

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#489]
code
```java
+package sandobx

+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[args] > app
  stdout > @
    sprintf
      "%d %d %d"
      ...* 1 2 3

```

result
![image](https://user-images.githubusercontent.com/33983579/146026458-c1289395-bb0c-4c2f-990f-cd7952581896.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware try again, should work now (I deployed version 0.21.0 to objectionary)

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#489` is not assigned, can't get performer
