### ISSUE TITLE
The cage is empty, can't read it

### ISSUE THREAD

**Issue by dours** [cqfn/eo#491]
```
[] > yy
  [nothing] > f
    [] > @
      cage > a
  f 0 > v
  seq > @
    v.a.write 1
    v.a.eq 1
```

**Comment by yegor256** [comment]
@dours this test fails, that's why your code doesn't work either:

```
[] > returns-same-object
  [] > foo
    [] > @
      memory > x
  eq. > @
    foo.x.<
    foo.x.<
```

I'm trying to find out whether it's a bug or a feature...

**Comment by yegor256** [comment]
@dours it was a bug. Fixed in ccf0e2a7

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#491` is not assigned, can't get performer

**Comment by dours** [comment]
@yegor256 Thank you. Could you also add the .eo files to the objectionary? The test now works ok in the master of EO, but plugin version 0.21.1 still downloads .eo files 0.21.0. They fail the test in a standalone maven run.

**Comment by yegor256** [comment]
@dours done, here: https://github.com/yegor256/objectionary/commit/110574a3b38742e0c0e41dcd20c76cd478358467
