### ISSUE TITLE
Turn atoms int.eq, string.eq, float.eq, bool.eq, and char.eq into objects

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#504]
All these atoms (int.eq, string.eq, float.eq, bool.eq, char.eq) but become objects and should use `as-bytes.eq`. For example, `int.eq` may be implemented as:

```
[] > int
  [x] > eq
    ^.as-bytes.eq (x.as-bytes)
```

"Type" information will be lost. Thus, this will be true:

```
1.eq TRUE
```

And this:

```
"hello".eq 68-65-6C-6C-6F
```

**Comment by yegor256** [comment]
@andreoss I'm sure you can do this, please

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#504](https://github.com/cqfn/eo/issues/504), since the job is not in scope anymore
