### ISSUE TITLE
SnippetTest logs too much

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#507]
At the moment `SnippetTest` logs everything directly to console, paying no attention to `log4j.properties` configuration. Something is wrong with the way we use `VerboseProcess` in the `exec()` method. Let's fix and make sure logging happens through Log4j.

**Comment by yegor256** [comment]
@andreoss maybe you can fix this

**Comment by yegor256** [comment]
@andreoss I'm wrong, no bug here

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#507](https://github.com/cqfn/eo/issues/507), since the job is not in scope anymore
