### ISSUE TITLE
Parser/resolver problem

### ISSUE THREAD

**Issue by dours** [cqfn/eo#508]
This parses ok:
```
[] > oshit
  cage > c1
  cage > c2
  seq > @
    1 > a
    c1.write a
    2 > b
    c2.write b
    TRUE
```

This fails, because it wants to download foreign objects `a` and `b`. What's the difference?
```
[] > oshit
  TRUE.while > @
    [i]
      cage > c1
      cage > c2
      seq > @
        1 > a
        c1.write a
        2 > b
        c2.write b
        TRUE
```

**Comment by dours** [comment]
the problem is with the vars-float-up pass, the workaround is to give names everywhere, so the following code compiles:
```
[] > ab2
  TRUE.while > @
    [i] > name
      seq > @
        stdout "ab2\n"
        1 > a
        2 > b
        TRUE
```

**Comment by dours** [comment]
not at all, this one fails to parse with the same error as well:
```
[] > xtrivial
  [] > xfib
    seq > @
      [] > tmp1
```

**Comment by yegor256** [comment]
@dours I see the problem, will fix now

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by yegor256** [comment]
@dours I believe it's fixed, try version 0.21.3

**Comment by dours** [comment]
This example also does not work. Moreover, I don't see any commits with fixes. Have you forgotten to commit?
```
[] > ab2
  TRUE.while > @
    [i]
      seq > @
        stdout "ab2\n"
        1 > a
        2 > b
        TRUE
```

**Comment by dours** [comment]
@yegor256  This example also does not work. Moreover, I don't see any commits with fixes. Have you forgotten to commit?
```
[] > ab2
  TRUE.while > @
    [i]
      seq > @
        stdout "ab2\n"
        1 > a
        2 > b
        TRUE
```

**Comment by yegor256** [comment]
@dours yes, forgot to push :(
