### ISSUE TITLE
Cannot extract object copying to a function: is this a feature?

### ISSUE THREAD

**Issue by dours** [cqfn/eo#512]
This example (it exchanges values of `b` and `c` using `a` as a temporary variable) works:
```
[] > mkCopyEvenSimpler
  cage > a
  cage > b
  cage > c
  c' > copyC
  b' > copyB
  a' > copyA
  seq > @
    stdout "mkCopy\n"
    a.write 1
    c.write 3
    b.write 2
    copyC.<
    a.write copyC
    stdout "a\n"
    copyB.<
    c.write copyB
    stdout "c\n"
    copyA.<
    b.write copyA
    stdout "b\n"
    (c.eq 2).and (b.eq 3)
```

Let's refactor it, let's extract object copying to a function `mkCopy`. Now the next example leads to StackOverflow. Why is it different at all? I explicitly dataize each call to `mkCopy` in order to force the computation and get the copy in order, but still...
```
[] > mkCopy
  [value] > mkCopy
    value' > copy
    seq > @
      copy.<
      copy
  cage > a
  cage > b
  cage > c
  seq > @
    stdout "mkCopy\n"
    a.write 1
    c.write 3
    b.write 2
    a.write (mkCopy c).@
    stdout "a\n"
    c.write (mkCopy b).@
    stdout "c\n"
    b.write (mkCopy a).@
    stdout "b\n"
    (c.eq 2).and (b.eq 3)

```

**Comment by yegor256** [comment]
@dours keep in mind that `copy.<` is NOT an "explicit dataization". It just making a copy of an object explicitly.

**Comment by yegor256** [comment]
@dours this:

```
a.write (mkCopy c).@
```

the parser reads as:

```
(a.write (mkCopy c)).@
```

You better do this:

```
a.write ((mkCopy c).@)
```

**Comment by dours** [comment]
@yegor256 Why does `a.write ((mkCopy c).@)` force dataization? Shouldn't `.@` be evaluated lazily?

**Comment by yegor256** [comment]
@dours I think this question is moving us away from the topic of this ticket. you better open a new one.
