### ISSUE TITLE
Another parser problem, similar to #508

### ISSUE THREAD

**Issue by dours** [cqfn/eo#514]
Similar to #508: This one still does not compile with 0.21.3 (tries to download `tmp1`)
```
[] > xtrivial
  [] > xfib
    seq > @
      [] > tmp1
        TRUE > @
```

**Comment by yegor256** [comment]
@dours I forgot to push changes in #508 :( Now they are here, you should try version 0.21.4

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.4`
