### ISSUE TITLE
let's report jacoco aggregate

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#519]
Now we only report coverage of eo-parser module to codecov (see `codecov.yml`). Let's report an aggregate report, as explained here: https://github.com/jacoco/jacoco/wiki/MavenMultiModule

**Comment by yegor256** [comment]
@andreoss please help us here

**Comment by andreoss** [comment]
@yegor256 `aggregated-report` seems to be a too convoluted way (having an extra module to do aggregation). For codecov it's enough to read jacoco reports for each module separately, without creating one aggregated report

**Comment by yegor256** [comment]
@andreoss let's do it the way you propose, I agree

**Comment by yegor256** [comment]
@andreoss I believe it's fixed, I'm closing. Thanks!
