### ISSUE TITLE
Lazy semantics difference

### ISSUE THREAD

**Issue by dours** [cqfn/eo#522]
The first test passes, the second does not. Is it because of some implicit copying of `a`?
```
[] > dataiz
  cage > a
  cage > b
  cage > c
  seq > @
    stdout "dataiz"
    a.write 1
    b.write 2
    c.write (a.add b)
    b.write 1000
    c.eq 3
```

```
[] > dataiz
  cage > a
  cage > b
  cage > c
  seq > @
    stdout "dataiz"
    a.write 1
    b.write 2
    c.write (a.add b)
    a.write 1000
    c.eq 3
```

**Comment by yegor256** [comment]
@dours they both should NOT pass, I believe. let me check.

**Comment by yegor256** [comment]
@dours I tried to reproduce, but no luck: https://github.com/cqfn/eo/commit/825b6cf98e0d5a995b25615f1268ae04b0cb06f2

**Comment by yegor256** [comment]
@dours are you sure your first test passes? I just ran it and it fails.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#522` is not assigned, can't get performer

**Comment by dours** [comment]
@yegor256 I also cannot reproduce it with 0.21.5
