### ISSUE TITLE
Enable some tests on Windows

### ISSUE THREAD

**Issue by baudoliver7** [cqfn/eo#526]
To continue on increasing portability of the project on Windows, we should enable :
- `SnippetTest`
- `PlaceTest`
- `UnplaceTest`

**Comment by yegor256** [comment]
@baudoliver7 can you do this?

**Comment by baudoliver7** [comment]
@yegor256 Sure, I will do it :)

**Comment by yegor256** [comment]
@baudoliver7 thanks!

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#550](https://github.com/cqfn/eo/issues/550) is still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the only puzzle [#550](https://github.com/cqfn/eo/issues/550) is solved here.
