### ISSUE TITLE
Is it forbidden to use an object by FQN?

### ISSUE THREAD

**Issue by i582** [cqfn/eo#537]
I am trying to compile a small script:

```
+package main

[args...] > main
  org.eolang.io.stdout > @
    "Hello World"
```

But I get the error:

```
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.21.5:assemble (default) on project
 eo-parent: Execution default of goal org.eolang:eo-maven-plugin:0.21.5:assemble failed:
 org.apache.maven.plugin.MojoFailureException: Failed to execute org.eolang.maven.PullMojo:
 Failed while trying to save to ./target/eo/04-pull/org/eolang/org.eo: https://raw.githubusercontent.com/yegor256/objectionary/master/objects/org/eolang/org.eo ->
 [Help 1]
```

It turns out that I cannot use the object by its FQN? That is, I always need to write `+alias ...` at the beginning if it is an object not from the current package?

Also, if you write FQN in the first identifier for the alias:

```
+package main
+alias io.stdout org.eolang.io.stdout

[args...] > main
  io.stdout > @
    "Hello World"
```

And then try to use it, you will get the same error.

I think it's worth adding this to the formal language description so that users don't have a question in the future.

**Comment by yegor256** [comment]
@i582 once we fix #531, it will be possible to do this:

```
+package main

[args...] > main
  /org/eolang/io/stdout > @
    "Hello World"
```

**Comment by yegor256** [comment]
@i582 I closed #531, it was a wrong idea, it seems (thanks to your ticket, which provoked thinking). It will work like this instead:

```
+package main

[args...] > main
  /.org.eolang.io.stdout > @
    "Hello World"
```

Here, `/` is the root object Φ.

**Comment by i582** [comment]
@yegor256 By the way, the use of FQN there can introduce some ambiguity:

For example:

```
+package main

[args...] > main
  /.org.eolang.some-object-with-property.property-name > @
    "Hello World"
```

Can we determine at the parsing stage that `property-name` is just a property, and not an object inside the package `/.org.eolang.some-object-with-property.property-name`? It seems that at the parsing stage this is impossible, but it seems that later it will be possible to determine this when all the symbols are known.

But such ambiguity is not very good, since reading the code it will not be clear what it is, a property or an object inside the package.

**Comment by i582** [comment]
@yegor256 In general, I don't see much point in allowing FQN to be used in such places, if the user wants to use the object, they must first import it explicitly. 

If this is described in a formal description, then, it seems to me, everything will be fine.

**Comment by yegor256** [comment]
@i582 we have to make "packages" also objects. Thus, `/.org.eolang` will be an object, and `/.org` also an object.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.0`

**Comment by yegor256** [comment]
@i582 now it's possible to do this:

```
+package main

[args...] > main
  Q.org.eolang.stdout > @
    "Hello World"
```
