### ISSUE TITLE
Path slashes are removed on Windows

### ISSUE THREAD

**Issue by baudoliver7** [cqfn/eo#545]
We noticed since `tojos` have been moved in separate project, that back slashes vanished from file paths on Windows.

**Comment by baudoliver7** [comment]
@yegor256 please, assign me this task.

**Comment by yegor256** [comment]
@baudoliver7 go ahead

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#545](https://github.com/cqfn/eo/issues/545); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#545](https://github.com/cqfn/eo/issues/545); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
