### ISSUE TITLE
Windows illegal character '\u201e'

### ISSUE THREAD

**Issue by egorklementev** [cqfn/eo#547]
When trying to compile a raw sandbox sample from this repository on Windows 10 the following errors arise:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/projects/Java/eo/sandbox/canonical/target/generated-sources/EOorg/EOeolang/EOarray$EOmap$EO?1$EO_1.java:[31,37] illegal character: '\u201e'
[ERROR] /D:/projects/Java/eo/sandbox/canonical/target/generated-sources/EOorg/EOeolang/EOarray$EOmap$EO?1$EO_1.java:[32,27] illegal character: '\u201e'
[ERROR] /D:/projects/Java/eo/sandbox/canonical/target/generated-sources/EOorg/EOeolang/EOarray$EOmap$EO?1$EO_1.java:[32,29] invalid method declaration; return type required
[ERROR] /D:/projects/Java/eo/sandbox/canonical/target/generated-sources/EOorg/EOeolang/EOarray$EOmap.java:[46,42] illegal character: '\u201e'
```
in this generated Java code:
``` java
    this.add("П†", new AtOnce(new AtComposite(this, rho -> {
      Phi ret_base = new PhMethod(rho, "ПЃ");
      Phi ret = new PhMethod(ret_base, "mapi");
      ret = new PhCopy(ret);
        Phi ret_1 = new EOarray$EOmap$EOП„1$EO_1(rho);
        ret = new PhWith(ret, 0, ret_1);
      return ret;
    })));
```
The exact illegal symbol is the "two commas" symbol here: `new EOarray$EOmap$EOП„1$EO_1` .
Google says it is a "double low-9 quotation mark" symbol.

**Comment by baudoliver7** [comment]
@egorklementev Please, add this to properties tag of `canonical` pom.xml :
```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
```
and try to compile again.

**Comment by baudoliver7** [comment]
@egorklementev Everything is ok now ?
I suggest you to update your branch to have latest modifications.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.6`

**Comment by egorklementev** [comment]
@baudoliver7 Now everything is okay on `0.21.5` (on Windows).

**Comment by baudoliver7** [comment]
@egorklementev Good !
Please, close the ticket since everything is solved.

**Comment by baudoliver7** [comment]
@yegor256 According to `rultor` logs, release failed because of the latest commit you made while releasing.
Could you release again ?

**Comment by yegor256** [comment]
@egorklementev try version 0.21.6, it's released to Maven Central
