### ISSUE TITLE
SnippetTest.java:69-71: Enable PlaceTest and UnplaceTest...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/eo#550]
The puzzle `526-1315d399` from #526 has to be resolved: 

https://github.com/cqfn/eo/blob/b2b8dac2c97071920f068a74aba30ff575bf7f23/eo-maven-plugin/src/test/java/org/eolang/maven/SnippetTest.java#L69-L71

The puzzle was created by @baudoliver7 on 28-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by baudoliver7** [comment]
@yegor256 please, assign
