### ISSUE TITLE
Why it is only possible to copy an identifier, not a field or any expression?

### ISSUE THREAD

**Issue by dours** [cqfn/eo#555]
both do not compile (with different errors):
```
[] > copySyntax2
  [] > z
    11 > field
  (z.field)' > eleven
  seq > @
    eleven.<
    eleven.eq 11
```
```
[] > copySyntax
  [] > z
    11 > field
  z.field' > eleven
  seq > @
    eleven.<
    eleven.eq 11

```

**Comment by yegor256** [comment]
@dours this is by design. If we allow to use apostrophe is any place, we will end up with pretty messy structure of XMIR (I just tried). That's why, just an object can be explicitly copied, by its name.
