### ISSUE TITLE
PullMojo.java:40-43: Enable Objectionary caching in...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/eo#561]
The puzzle `490-f28eb43a` from #490 has to be resolved: 

https://github.com/cqfn/eo/blob/16f840437832445f7b8602b6e63291a07f1feb84/eo-maven-plugin/src/main/java/org/eolang/maven/PullMojo.java#L40-L43

The puzzle was created by @andreoss on 29-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by marceloamadeu** [comment]
@yegor256 Can I try to solve this issue?

**Comment by yegor256** [comment]
@marceloamadeu yes, go ahead

**Comment by marceloamadeu** [comment]
@yegor256 and @andreoss 

For **"Add a parameter to bypass/overwrite cache"** can be used the parameter **overWrite**? Or is it necessary to create another parameter (i.e. overWriteCache)?

    @Parameter(required = true, defaultValue = "false")
    private boolean overWrite;

Tks

**Comment by yegor256** [comment]
@marceloamadeu I suggest to try to rely on [`-U`](https://stackoverflow.com/a/9697970/187141) parameter of Maven, if it's possible to get access to it from the plugin

**Comment by marceloamadeu** [comment]
Thanks @andreoss  and @baudoliver7  for the help... ;-)

@yegor256 Please close this issue

**Comment by 0pdd** [comment]
The puzzle `490-f28eb43a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#624](https://github.com/objectionary/eo/issues/624) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#624](https://github.com/objectionary/eo/issues/624) is solved here.
