### ISSUE TITLE
EoLexer.java:42-46: Remove EoLexer.action method. Having...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/eo#567]
The puzzle `430-42a96944` from #430 has to be resolved: 

https://github.com/cqfn/eo/blob/5375ceda855a51b7bc9acdba715a60279e80d9a4/eo-parser/src/main/java/org/eolang/parser/EoLexer.java#L42-L46

The puzzle was created by @andreoss on 03-Jan-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by andreoss** [comment]
Correction: Actual parent task is #390

**Comment by andreoss** [comment]
@yegor256 I can take this.

**Comment by yegor256** [comment]
@andreoss go ahead
