### ISSUE TITLE
Grammar improvement

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [cqfn/eo#568]
Hello, @yegor256.
I noticed that swapping list of abstract attributes with the attribute name and moving down attribute definition can improve code readability. Compare `#1` and `#2`
![image](https://user-images.githubusercontent.com/48378098/148277451-d06b2340-f4cc-486b-94cd-3aa95842657d.png)
Now, in `#2`, attribute names of an object are all indented with exactly 2 more spaces than their parent object. 
Also `#2` seems to be more similar to [Phi Calculus syntax](https://arxiv.org/pdf/2111.13384.pdf#page=7). 
What do you think, will such minor language change be beneficial?

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 the idea is to always start a line with an object, because it is the first-class citizen here. Not the name of it, which is a secondary thing. In your second snippet we have both objects and names at the first position -- this is confusing.

**Comment by br4ch1st0chr0n3** [comment]
@yegor256, there should be no confusion due to a context. If a name is followed by an arrow, it's an attribute name. Otherwise, it's an object.

From my point of view, if an operation starts, it should continue until its leaf terms if read up-down left-right.  In `line 3`,
