### ISSUE TITLE
Link - eolang-paper.pdf

### ISSUE THREAD

**Issue by marceloamadeu** [cqfn/eo#571]
@yegor256 In the https://www.yegor256.com/2021/10/21/objectionary.html there is an incorrect link in the phrase 

- You can read its more or less formal description [**here**](https://www.eolang.org/eolang-paper.pdf)
and
- If you wonder what this XML means, read [**this document**](https://www.eolang.org/eolang-paper.pdf): there is a section about XMIR.

Can we fix this?

Thanks

**Comment by yegor256** [comment]
@marceloamadeu fixed and deployed, thanks: https://github.com/yegor256/blog/commit/66f9c611c6410ba843f9a6f153b330179fd2740d
