### ISSUE TITLE
Can't simply run command in the How to Contribute section of README

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [cqfn/eo#572]
On Ubuntu 20.04, before executing `./mvnw clean install -Pqulice` I needed to:
- set `$JAVA_HOME` variable
- run `chmod +x mvnw`
- [produce jar](https://stackoverflow.com/a/50105966) (ignored in `.gitignore`)

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 I removed this stuff. Just use `mvn clean install -Pqulice` and you'll be fine.
