### ISSUE TITLE
commented-out tests

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#574]
It seems to me that commented-out code, especially tests, is not a very good practice

https://github.com/cqfn/eo/blob/4cbdec00974193e653a5e6d800295d0dedd5474b/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo#L78-L87

https://github.com/cqfn/eo/blob/4cbdec00974193e653a5e6d800295d0dedd5474b/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo#L212-L223

**Comment by yegor256** [comment]
@IngeniariusSoftware yes, indeed, it's a bad practice, but that's the best we can do, until we have this lib: https://github.com/yegor256/objectionary/issues/6
