### ISSUE TITLE
endless while cycle

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#575]
code
```java
+package c2eo.src

+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > whiletest
  memory > m

  [] > main
    seq > @
      m.write 5
      while.
        (((m.greater 0).if 1 0).eq 0).if FALSE TRUE
        seq
          m.write (m.sub 1)
          stdout (sprintf "%d\n" m)
      TRUE

  main > @

```

result
![image](https://user-images.githubusercontent.com/33983579/149355374-08fc62f1-244a-4362-9b7d-7212537c7c4e.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware can you make this code shorter? Are you sure that ALL lines in your example are relevant to the bug you report?

**Comment by IngeniariusSoftware** [comment]
@yegor256, I made it shorter

**Comment by IngeniariusSoftware** [comment]
@yegor256, to be more precise, the whole problem is in this chain of calculations ` (((m.greater 0).if 1 0).eq 0).if FALSE TRUE`

**Comment by yegor256** [comment]
@IngeniariusSoftware you are right, reopening

**Comment by yegor256** [comment]
@IngeniariusSoftware it's reproduced and fixed in 7d86e635

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@IngeniariusSoftware try version 0.22.2, it should work
