### ISSUE TITLE
replacing "-" with "_"

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#576]
replacing "-" in the package name in the final file with "_" is this correct behavior?

`+package c2eo.src.main-while-while01` -> 

in target dir

![image](https://user-images.githubusercontent.com/33983579/149358241-6c5f68f7-ade8-49e6-a615-c7924f033bf5.png)

**Comment by andreoss** [comment]
@IngeniariusSoftware This looks correct, `-` would be illegal as a package name in JVM.
