### ISSUE TITLE
`as-bool` for `bytes`

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#581]
We have the attribute `as-bytes` in `bool`, but there is no `as-bool` in `bytes`

**Comment by yegor256** [comment]
@IngeniariusSoftware it's fixed, thanks

**Comment by 0crat** [comment]
Job [#581](https://github.com/cqfn/eo/issues/581) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#581](https://github.com/cqfn/eo/issues/581); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#581](https://github.com/cqfn/eo/issues/581); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
