### ISSUE TITLE
Remove --verbose argument from canonical sandbox run.sh script

### ISSUE THREAD

**Issue by Graur** [cqfn/eo#583]
There was a bug fix change in #434, when `--version`  was changed to `--verbose`  in  `sandbox/canonical/run.sh`.
Maybe we need to remove this argument for default behavior to clear console output from a large amount of text (according to the #434 issue)?

**Comment by marceloamadeu** [comment]
@Graur I also think it would be better to clear the console output.

We can change to `sandbox/canonical/run.sh --verbose`?

So `--verbose` is not required

@Graur and @yegor256 What do you think?

**Comment by Graur** [comment]
@marceloamadeu I agree. It took me a while to figure out what was going wrong when I ran this script for the first time.

**Comment by yegor256** [comment]
@Graur done in 0196d63e thanks!
