### ISSUE TITLE
cannot store a function to `cage` and then call it

### ISSUE THREAD

**Issue by dours** [cqfn/eo#589]
("You can't overwrite static expression")
```
[] > simplestClass
  cage > c
  write.
    c
    [x]
      TRUE > @
  c 2 > @
```

**Comment by dours** [comment]
@yegor256 , please, note. The trick above would help me with implementation of classes.

**Comment by dours** [comment]
oops, the example above also has an attribute without a name, I guess (but it still compiles and reports the error I mentioned).
Anyway, this example is more correct, but also leads to the same error
```
[] > simplestClass
  cage > c
  seq > @
    write.
      c
      [x]
        TRUE > @
    c 1
```

**Comment by yegor256** [comment]
@dours this code can't work. This one can, though:

```
[] > simplestClass
  cage > c
  seq > @
    write.
      c
      [x]
        TRUE > @
    c.@ 
      1
```

`c 1` means making a copy of `cage` with a new argument `1`. Of course, doesn't work, since there is no "free" attributes in the cage. We should take what's inside by using `@` first, and then deal with it. See 5406f436
