### ISSUE TITLE
Add more examples of syntactic constructions

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [cqfn/eo#594]
Please add an example for `inverse dot` notation into [full-syntax](https://github.com/cqfn/eo/blob/master/eo-parser%2Fsrc%2Ftest%2Fresources%2Forg%2Feolang%2Fparser%2Fpacks%2Ffull-syntax.yaml)

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 added a bit: b9ffc976 Enough or you meant something more specific?

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 I'm closing. If you need more, open another ticket please.
