### ISSUE TITLE
It seems there is a mistake in phi-calculus paper

### ISSUE THREAD

**Issue by maxonfjvipon** [cqfn/eo#599]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/37025995/157933349-737bc46c-ccce-4111-8988-dcadd2e98947.png">

Paragraph 3.5. `x.y.z = x` does not have any sense. It seem there is should be `x.y.𝜌 = x`

UPD: [#600 closed](https://github.com/cqfn/eo/pull/600)

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#599` is not assigned, can't get performer
