### ISSUE TITLE
A better sintaxe

### ISSUE THREAD

**Issue by mdbs99** [cqfn/eo#6]
I would like to propose some sintaxe, as I've said [here](https://gitter.im/yegor256/elegantobjects?at=57f276aed45d7f0f525c0402).

The sintaxe bellow have:

1. Types, instead Classes
2. The keyword `constructor` instead using the name of type, because now the Object was disconnected from Type, ie, don't have a Class!
3. I propose a new keyword `implements` that allow us to use an elegant delegation.

```
type Run { running() }

type Bark { barking() }

type Dog extends Run, Bark { 
  name(): String
  sit()
}

var r1 = object Run("fast!") {
  constructor (v: String) {
    var value = v
  }
  running() { print(value) }
}

var b1 = object Bark("AU AU") {
  constructor (v: String) {
    var value = v
  }
  barking() { print(value) }
}

var dog = object Dog("Rex") {
  constructor (n: String) { var name = n }
  name(): String { print (name) }
  sit() { print ("sat") }
  compose {  
    run from r1 implements Run,
    bark from b1 implements Bark
  }
}

dog.name() // "Rex"
dog.sit() // "sat"
dog.run.running() // "fast!"
dog.bark.barking() // "AU AU"

```

**Comment by yegor256** [comment]
@mdbs99 why no semi-colons? won't it be difficult to parse this code?

**Comment by mdbs99** [comment]
Here an example of `copy`:
```
var dog = object Dog("Rex") { ... } 
var lucy = object Dog("Lucy") from dog
```
Now you have `lucy`, an object copied from `dog` (Rex) but name was initialized using Rex's constructor.

**Comment by yegor256** [comment]
@mdbs99 why this:

```
name(): String
```

instead of this:

```
String name();
```

I think it's better to stay as close to Java as possible. Or I'm wrong?

**Comment by yegor256** [comment]
@mdbs99 in your syntax I can't have a method with the name `constructor`, right?

**Comment by mdbs99** [comment]
How to use delegation (see comments [here](https://gitter.im/yegor256/elegantobjects?at=57f2a6eb0ec6f9457d9b8ded))

```
type Stream { serialize() }

var b64 = object Stream(d: String) {
  // implements base64
}

type Dog extends Run, Bark, Stream { 
  name(): String
  sit()
}
var dog = object Dog("Rex") {
  constructor (n: String) { var name = n }
  name(): String { print (name) }
  sit() { print ("sat") }
  delegation {  
    run from r1 implements Run
    bark from b1 implements Bark
    stream from b64 implements Stream(name())
  }
}

print ("Dog in base 64: " +dog.stream.serialize())
```

**Comment by mdbs99** [comment]
@yegor256 yes, we can't.

**Comment by mdbs99** [comment]
@yegor256 
Everybody copy C++ or Java syntax. Let's move on.
A developer who loves Java won't like this new language, I suppose.
So, let's create a new language... a better one.

**Comment by vivekimsit** [comment]
we can take help from Scala too I like their idea of `trait` and `object`.

http://docs.scala-lang.org/tutorials/tour/classes.html

**Comment by yegor256** [comment]
@mdbs99 hm... I think I agree (about non-Java syntax). Where did you get your syntax?

**Comment by mdbs99** [comment]
@yegor256 nowhere, I invented when we talked on Gitter.

**Comment by englishman** [comment]
@mdbs99 could you, pls, explaine this syntax
```
...
compose {  
    run from r1 implements Run
    bark from b1 implements Bark
    stream from b64 implements Stream(name())
}
...
```
E.g. here 
`run from r1 implements Run`
what does this mean? What are `run` and `r1`?

**Comment by englishman** [comment]
@mdbs99 also here
```
...
constructor (v: String) {
    var value = v
}
...
```
What is `value`? Is this local ctor variable or object field?

**Comment by mdbs99** [comment]
@englishman 

> `run from r1 implements Run`

This is a Object Pascal feature (but the syntax is different, see [here](http://www.freepascal.org/docs-html/ref/refse44.html)).
Means you have a Object that could implement many interfaces, but you don't need to implement these methods, just delegate them for another objects.

> what does this mean? What are run and r1?

So, in that syntax I've proposed `run` is a property that will receive an instance that implements the Interface `Run`, ie, the `r1` object (declarated in first comment).

**Comment by mdbs99** [comment]
@englishman 

> What is value? Is this local ctor variable or object field?

Yes, looks ambiguous...
Maybe we can use `@` like Ruby for all attributes, because is annoying to write `this` for attributes but not methods — an inconsistency, IMO.

**Comment by yegor256** [comment]
@mdbs99 I like the idea about `@`, here is the ticket: https://github.com/yegor256/eo/issues/10

**Comment by DronMDF** [comment]
Drop semicolon - this is a good idea.
Only one expression per line.

**Comment by MonsieurLuge** [comment]
I like the `def` keyword instead of `var`. Sounds more object oriented to me.

And why not get rid of the equal sign when defining variables, and keep it only for comparisons ?
```
def name is String("Mattew")

return name = String("Johnny")
```

**Comment by yegor256** [comment]
@DronMDF I agree, we don't need semi-colons at all

**Comment by yegor256** [comment]
@MonsieurLuge check this out: https://github.com/yegor256/eo/issues/20

**Comment by mdbs99** [comment]
@yegor256 I think this issue can be closed because people chose another syntax.
But, if we close this, I will start another issue to talk about composition to implement Types. What do you think?

**Comment by vivekimsit** [comment]
To be honest I think the syntax looks too verbose and too much indentation.

```
Int max(Int a, Int b):
  if:
    lessThan:
      a,
      b
    b,
    a
```

I am not a language designer but I would love to see something close to this:

```
if a lessThan b then b else a
```

**Comment by mdbs99** [comment]
@vivekimsit I've suggested to use brackets, at first, because I guess most here likes Java. But after I've talked to use `end` to delimit a block — like Ruby or Pascal (without `begin`).
I still think that using `end` is a better choice. That make possible to write as you said, in one line.

**Comment by vivekimsit** [comment]
@mdbs99 seriously I want the honest opinion about the syntax being discussed above like I would never like to review the code written above. At least the syntax shouldn't be completely alien.

**Comment by mdbs99** [comment]
I guess you talking about the syntax that use whitespaces, right?

**Comment by vivekimsit** [comment]
```
Int max(Int a, Int b):
  if:
    lessThan:
      a,
      b
    b,
    a
```

**Comment by yegor256** [comment]
@mdbs99 we have a new syntax now
