### ISSUE TITLE
Object equality

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#60]
How does `equals` object work?
Is every type _equatable_?
If yes, can I override default behaviour?

**Comment by yegor256** [comment]
@g4s8 good question. I think that two objects are equal if there encapsulated attributes are equal, e.g.:

```
equals: // it's true
  text("hello"),
  text("hello")
```

**Comment by mdbs99** [comment]
> ...encapsulated attributes are equal,

So `equals` can see inside any objects?

**Comment by g4s8** [comment]
@yegor256, if I understand, `equals` has internal implementation to access object attributes (like java reflection)? Maybe it will be better if `equals` arguments implement some type? E.g.:
```
type Equatable:
    Bool sameAs(? other)

object equals<T as Equatable> ():
    T @first
    T @second
    ctor(T first, T second)
    Bool bool():
        first.sameAs(second)
````

**Comment by mdbs99** [comment]
@g4s8 I think we don't need generics, see #1.

**Comment by g4s8** [comment]
> I think we don't need generics 
@mdbs99, ok, but this is just an example. I mean that not any object should be equatable. For instance `if`, `plus`, `minus`: whether `plus 4 1` is equal to `plus 3 2` or not?
So if equality is not a built-in object property, then each equatable object should implement it itself. Besides object can be equal only to object with same type, and I don't know how to describe it without generics.

**Comment by NikoGJ** [comment]
equals: should be a method on the object and would require another object as an argument. You basically ask an object if he is the same as another one

**Comment by mdbs99** [comment]
@g4s8 I need to think more about that.

**Comment by Lebedevsd** [comment]
@mdbs99, @g4s8  but as far as I understand the objects `plus 4 1` are not equal `plus 3 2` even in java, but as types (interfaces) Number which have only one method `int value()` they are kind of equal.
So do we need to think about object and interface equality? 
Because as an interfaces `Number` this two objects `plus 4 1`, `plus 3 2` are equal.

**Comment by jachinte** [comment]
@Lebedevsd, cc. @g4s8 is there a discussion about how operators will work in EO? as far as I understand, without using syntactical sugar, `plus` should not be a special object, so objects `plus 4 1` and `plus 3 2` are objects, not values. If you want to get the result of the operation, you should ask the object to return the result; something like `myPlus.value()`. Then, `myPlus1.value()` and `myPlus2.value()` are equal, but `plus 4 1` and `plus 3 2` are not.

**Comment by g4s8** [comment]
@jachinte, it's not correct, `plus`, `equals` and whatever else are objects. There is no operators. The problem here is 'whether any object must be equatable and how to get object equality'.

**Comment by androidfred** [comment]
Not everything makes sense to perform equality operations on, so making everything equatable irrespective of whether there is an implementation of equality or not (like Java does) is nonsensical and dangerous.

In Haskell, only things which explicitly implement equality can have equality operations performed on them, and attempting to perform equality operations on non equatable things results in a compilation error.

**Comment by yegor256** [comment]
@g4s8 two objects are equal only if their datarization function results are equal

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#60` is not assigned, can't get performer
