### ISSUE TITLE
better error logging

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#603]

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#604](https://github.com/cqfn/eo/issues/604) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.11`

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#604](https://github.com/cqfn/eo/issues/604) is solved here.
