### ISSUE TITLE
SyntaxTest.java:75-78: This test doesn't work, because...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/eo#604]
The puzzle `603-524ef27e` from #603 has to be resolved: 

https://github.com/cqfn/eo/blob/85bbeb4d8f4e90866d170cbd5d2d8864cc9e9f85/eo-parser/src/test/java/org/eolang/parser/SyntaxTest.java#L75-L78

The puzzle was created by @yegor256 on 24-Mar-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@andreoss interesting bug, can you try to fix?

**Comment by 0pdd** [comment]
The puzzle `603-524ef27e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#604](https://github.com/cqfn/eo/issues/604); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#604](https://github.com/cqfn/eo/issues/604); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
