### ISSUE TITLE
`bytes.size` enters inifinte looop

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#607]
This code never terminates 

<pre>
+junit
[] > main
  ram 1024 > r
  3.as-bytes > b
  r.write 0 b > w
  and. > @
    w.eq TRUE
    (r.read 0 <b>b.size</b>).as-int.eq 3
</pre>

Meanwhile, this works

<pre>

[] > main
  ram 1024 > r
  3.as-bytes > b
  r.write 0 b > w
  and. > @
    w.eq TRUE
    (r.read 0 <b>(b.size)</b>).as-int.eq 3

</pre>

**Comment by yegor256** [comment]
@andreoss this is because the first snippet read as such:

```
+junit
[] > main
  ram 1024 > r
  3.as-bytes > b
  r.write 0 b > w
  and. > @
    w.eq TRUE
    **((r.read 0 b)**.size).as-int.eq 3
```
