### ISSUE TITLE
seems like a boolean value fails to dataize

### ISSUE THREAD

**Issue by dours** [cqfn/eo#617]
```
[unused] > constructor-arguments
  [res] > return
    res > result
  cage > tmp
  [] > xmyC
    (return (123.eq 5)) > @
  seq > @
    stdout (sprintf "constructor-arguments\n")
    tmp.write (((((xmyC)))))
    stdout "A\n"
    (tmp.result)
```

leads to `Can't get(), attribute "as-bytes" is absent among other 4 attrs (result, ρ, res, σ) and φ is absent` after `A` is printed

**Comment by yegor256** [comment]
@dours I believe it's normal behavior, since `xmyC` can't be dataized, because it's `return ...`, which doesn't have `@`

**Comment by dours** [comment]
@yegor256  which line tries to dataize `xmyC`? Only `xmyC.result` is dataized, I think, which is a boolean!
