### ISSUE TITLE
Java compatibility: should we believe in it for now?

### ISSUE THREAD

**Issue by sergiofigueras** [cqfn/eo#66]
Hello :),

So, I'm checking that there are a lot of different Java compatibility concerns and efforts here, like using Java libraries, generating .java files, etc.

So, the whole question about it for me is: do we REALLY NEED to be Java compatible? I think that here we have a lot of Java devs that love it (like myself), but the whole problem with bringing all of those Java concerns is that maybe we are getting into a topic that will be really hard to manage with our focus of develop a completely new and full object oriented language. It seems that it absolutely not sustainable.

Ok, by one side there is a lot of Java stuff developed that would be awesome to bridge with EO, but by the other side, we are getting rid of our objective of develop a completely and whole new OO pure language.

We are a really small team for now, so I think that it would be better if we can focus on our biggest challenge here, that is cleanliness and validate our language. For me, bringing Java compatibility  sounds completely strange as if for example you are building a bakery but want to sell someone else's bread because your village likes it, and your clients will come to you not to buy your breads, but your milk that is better than the other one (not really nice example, but I hope that you guys understood it).

What do you think?

**Comment by alexpanov** [comment]
Is there a need for this issue specifically when there are https://github.com/yegor256/eo/issues/47 and https://github.com/yegor256/eo/issues/52 already?

**Comment by phase** [comment]
> Is there a need for this issue?

No

---

If it runs on the JVM, it will be compatible with Java.  EO libraries will at least be callable from Java, but doing the other way around is entirely up to you.

**Comment by yegor256** [comment]
@phase the compiler (a primitive first version that doesn't really work) is ready, check master branch.

**Comment by yegor256** [comment]
@sergiofigueras I believe that the goal is to make EO compilable to any platform, including JVM and x86 binaries. JVM is popular and will save a lot of time for us. How exactly we will use existing Java libraries is still a question for me too.

**Comment by yegor256** [comment]
@sergiofigueras it's a dup of #52
