### ISSUE TITLE
Syntax highlighting for Vim

### ISSUE THREAD

**Issue by pchmielowski** [cqfn/eo#71]
I've created basic rules for Vim to highlight the syntax:
https://github.com/pchmielowski/EoVim

Please contribute ;)

[edit] It looks like that:
![screenshot](https://raw.githubusercontent.com/pchmielowski/EoVim/master/syntax.png)

**Comment by yegor256** [comment]
@pchmielowski we have a new syntax now, can you please update your highlighter?

**Comment by pchmielowski** [comment]
> @pchmielowski we have a new syntax now, can you please update your highlighter?

Not right now and most likely not in the foreseeable future 😉

**Comment by yegor256** [comment]
@nlchar maybe you can contribute to that repository of @pchmielowski ? It seems pretty simple to me, and our current syntax is pretty straight forward. Would be nice to have a syntax highlighter for Vim.

**Comment by nlchar** [comment]
> @nlchar maybe you can contribute to that repository of @pchmielowski ? It seems pretty simple to me, and our current syntax is pretty straight forward. Would be nice to have a syntax highlighter for Vim.

@yegor256 maybe `visual-studio code` is better as it is more popular and easier to use?

**Comment by yegor256** [comment]
@nlchar we should do both, I think

**Comment by nlchar** [comment]
> @nlchar we should do both, I think

@yegor256 added to our backlog. I will investigate what can be done in the field now and then we will prioritize the task.

**Comment by yegor256** [comment]
@pchmielowski @nlchar when ready, submit a new ticket with a solution :) I'm closing this one.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#71` is not assigned, can't get performer
