### ISSUE TITLE
Code sample with state change is missing

### ISSUE THREAD

**Issue by alexpanov** [cqfn/eo#75]
[This comment](https://github.com/yegor256/eo/issues/45#issuecomment-265107553) got me thinking about another aspect of an all-objects-are-immutable language.

I do not understand how state changes are handled.
In the example referenced above, a `vehicle` pulls up at a traffic light and observes that traffic light state change.
What happens when the traffic light state does change? Does the traffic light get replaced by a new one? Apart from that making zero sense, the vehicle does not observe that same traffic light. It still is only aware of the obsolete one.

I do not see how to avoid the rebuild-the-world problem on every single change which is not practical for obvious reasons.

I would love to see an example handling some state change because so far the code samples are primitive in terms of functionality.

**Comment by yegor256** [comment]
@alexpanov did you read this: http://www.yegor256.com/2016/09/07/gradients-of-immutability.html

**Comment by alexpanov** [comment]
@yegor256 I have. I still want to see those concepts implemented in `eo`. Maybe it's time for an `eo-examples` repository or at least a module with `.eo` files that one can check out and play with?

**Comment by yegor256** [comment]
@alexpanov see the example with `while` in README
