### ISSUE TITLE
EO object

### ISSUE THREAD

**Issue by RayoGundead** [cqfn/eo#76]
Sounds really meta.
Basically, an `EO` object for each file/package/image file/whatever.the.structure.of.src.is.going.to.be.

an object for the language/interpreter/compiler itself

multi-line
looks too procedural for my liking.
```
EO: package: namespaceName
EO: import: whatever.namespace.object as: watevsObj
EO: import: another.namespace.object as: anObj
```

separated by whitespace(space)
```
EO: import: ( whatever.namespace.object as: watevsObj ) ( another.namespace.object as: anObj )
```

separated by whitespace(\n)
```
EO: import:
    another.namespace.object as: watevsObj
    watevs.ns.obj as: anObj
```

some random idea for reveal module pattern  syntax
```
EO: export: oneObj twoObj threeObj
```

go crazy wth the idea and have types and objects declared
starting to look like pascal
```
EO:
    import: watevs.ns.aType as: aType
    types:
        SomeType:
            aType aMethod()
            SomeType anotherMethod(aType anArg)
        SomeOtherType: extends: SomeType
            aType watMethod()
            SomeType mehMethod(aType anArg)
    objects:
        yayObj: as: SomeType
            ...
        yayAnotherObj: as: SomeOtherType
            ...
```

Like with GreaterThan, Max, etc... this could be an object built into the language

**Comment by RayoGundead** [comment]
One more to add...

Telling the compiler which object is the main/entry point/AppObj of the application:
```
EO: 
    import: whatevs.ns.Main as AppObj
    main: AppObj
```

**Comment by mdbs99** [comment]
@RayoGundead I like your thoughts, but I think we don't need `:` for everything
I rewrote your code, look:

```
    import watevs.ns.aType as aType
    types:
        SomeType:
            aType aMethod()
            SomeType anotherMethod(aType anArg)
        SomeOtherType extends SomeType:
            aType watMethod()
            SomeType mehMethod(aType anArg)
    objects:
        yayObj as SomeType
            ...
        yayAnotherObj as SomeOtherType
            ...
```
I don't know what you mean about `EO:`

And about entry point, please see #78

**Comment by RayoGundead** [comment]
What I mean is `EO` is an object representing the compiler/processor/interpreter.

**Comment by mdbs99** [comment]
Hmm... but why have an `EO` in all files? Isn't too verbose?

**Comment by RayoGundead** [comment]
It doesn't have to be.

You can just have one file containing the `EO` object. That file you can pass to the compiler. I guess you could say that the `EO` object is the MakeFile for the project, but instead of a file, it's an object.

Even better, have one image file containing all the objects in the project/package/app/lib managed by the objectionary(whatever package management for objects it is) and one `EO` object.

**Comment by g4s8** [comment]
What's the benefit of EO object? @RayoGundead, could you provide more real example?

**Comment by mdbs99** [comment]
I see EO object as a program file.
Maybe put this option here #78.

**Comment by g4s8** [comment]
@mdbs99, as I understand, EO object is something like codegeneration object, he is able to compile objects and types in runtime. Something like `System.Reflection.Emit` in C#. @RayoGundead, am I wrong?

**Comment by mdbs99** [comment]
@g4s8 Ok, could be, but why not use this object implicitly?
I mean, why we need to use EO: in all files?

**Comment by yegor256** [comment]
@RayoGundead I also don't see what we need this "object". Meta-programming is a good idea, but it's better to have that meta information attached to each object, without any global structure. I guess.

**Comment by nlchar** [comment]
@yegor256 I propose rejecting this improvement idea since the author (@RayoGundead) has not been here for more than two years. The idea is unclear and not necessary to be embedded into the language at the moment, so it can be considered out of scope.

**Comment by yegor256** [comment]
@nlchar I agree, closing

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#76` is not assigned, can't get performer
