### ISSUE TITLE
Module/package

### ISSUE THREAD

**Issue by g4s8** [cqfn/eo#77]
It seems that we need syntax for module or package declaration to define objects and types inside it, like mentioned in #22.
E.g.:
```
module org.eolang:
    object if as If:
        #...
```

**Comment by yegor256** [comment]
@g4s8 I would rather require an explicit definition of the package/module in the object name, where and when necessary. For example, this one will put object `if` into `org.eolang`:

```
object org.eolang.if as If:
  # ...
```

While this code will leave it outside of any package/module:

```
object if as If:
  # ...
```

WDYT?

**Comment by g4s8** [comment]
@yegor256, explicit definition looks good, cause we always can use `import org.eolang.if` in client code, right?

But I missed the point of "outside of any package/module" in second example. Do you mean that this `if` will be in some default package or some anonymous package (different for each object, declared without package)?

And what about access controll? Would an object be allowed to access any object/type in other packages?

**Comment by yegor256** [comment]
@g4s8 yes, we will use `import` in client's code.

Maybe I'm wrong, but I thought that we should have an ability to skip packaging and declare objects in "default" package, as you called it. Just like you can do it in Java, if you don't use `package` at all. I'm not sure, maybe it's not a good idea though. Maybe we should be more strict and always require a package.

I think that any object should be allowed to access any package/object. This package-only access rights, which are offered in Java, are just a mess, I believe.

**Comment by yegor256** [comment]
@g4s8 now it works like this:

```
+package org.example

[args...] > main
  stdout
    "Hello, world!"
```
