### ISSUE TITLE
Language support for collections

### ISSUE THREAD

**Issue by SilasReinagel** [cqfn/eo#8]
Presently there is a weird division in programming where you have to use Multiple of a type of object differently than a single object. 

This leads to creating String and List<String> and so forth. Collection objects are used extremely frequently in real application code. What if the langauge were to be able to create this collection behavior automatically?

What if using a plural form of a known class name would automatically compile to a collection by default. 

Consider this code.

```
Color white = color("#ffffff")
Color black = color("000000")
Colors appColors = colors(white, black)
```

While the Color type or object would need to be declared, it would be nice if Colors behaved like a List<Color> or similar.

**Comment by yegor256** [comment]
@SilasReinagel I was waiting for this ticket. Thanks!

**Comment by scadgek** [comment]
There is a reason behind separate collection classes - they're backed different data structures. How do you suggest to implement this variety in `colors`?

**Comment by pchmielowski** [comment]
@scadgek Maybe in some inverted-Java-way: `Colors appColors = colors<LinkedList>(white, black)`
And if user does not provide `< ... >` block, compiler will choose the default structure.

**Comment by yegor256** [comment]
@pchmielowski we have arrays in Java, but don't have collections. This is sort of legacy from C/C++. And I'm mostly thinking about iterables, not collections. How exactly that lists, queues, sets, maps, etc will be implemented is up to JDK (EDK maybe). But we have to have that "iterable" thing built into the language, I believe.

**Comment by scadgek** [comment]
@yegor256 So if I understand you correctly, you consciously deprive the developers of the ability to choose the underlying data structure?

**Comment by SilasReinagel** [comment]
I don't think the goal is to deprive developers of important abilities. The goal is to simplify the common use cases. 

So, maybe there should be a way to specify a name for plural and the type of structure used. If unspecified, a default could be inferred.

Furthermore, many collection functionalities could be added via decoration. `Colors appColors = unique(colors(white, black)) ` would behave like a Set instead of a List.

**Comment by stain** [comment]
I think we can take inspiration from Java 8 streams here, where the type of collection you want comes about later and just modulate the stream, e.g. `unordered(gradient(colors(white, black), 0.1))` to get an unordered stream from a color gradient with a 0.1 increase.

**Comment by yegor256** [comment]
@stain we have `array` object now, which is an immutable primitive collection with random access.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#8` is not assigned, can't get performer
