### ISSUE TITLE
UML like associations 

### ISSUE THREAD

**Issue by erikgollot** [cqfn/eo#81]
In UML we've associations,  why not in languages?
With roles and multiplicity.
This lack is the reason why JPA annotations have mappedBy attribute.

**Comment by erikgollot** [comment]
Let me give more insight

you've the following situation:
                                  MyAssociation
ClassA 1,1 myRoleA------------------myRoleB 0,* ClassB

You can expect to write this situation into your code like this

```
class ClassA {

@Association(name="MyAssociation", lower=0,upper=-1)
public Collection<ClassB> myRoleB;

}

class ClassB {

@Association(name="MyAssociation", lower=1,upper=1)
public ClassA myRoleA;

}
```

**or**

```
class ClassA {

@Association(name="MyAssociation", role.my.lower=0,role.my.upper=-1,role.other.lower=1,role.other.upper=1,other=ClassB.myRoleA)
public Collection<ClassB> myRoleB;

}

class ClassB {

public ClassA myRoleA;

}
```

**Comment by alexpanov** [comment]
Is there any difference between this issue and https://github.com/yegor256/eo/issues/82? If so, please explain

**Comment by jachinte** [comment]
@erikgollot I think this is an interesting concept, but it's hard for me to understand your example. Maybe you can use [UMPLE's syntax](http://cruise.eecs.uottawa.ca/umple/AssociationDefinition.html) to make it clearer? also, they model UML using a textual notation, you can take some knowledge from there :+1:

**Comment by yegor256** [comment]
@erikgollot indeed, the example looks difficult to digest. Please, use simpler names, like books, cars, animals, etc.

**Comment by erikgollot** [comment]
ok. Let's assume that an Animal has a Pet House. On the Animal side, the Animal has an attribute "house". On the Pet House side, the Pet House has an attribute resident. We can imagine that an Animal can have 0..N houses and an Pet House has only one resident.

Animal --1--resident------>house--0..N--Pet House

**Comment by yegor256** [comment]
@erikgollot I'm closing this, since it's not relevant to the new version of EO
