### ISSUE TITLE
Association inheritance 

### ISSUE THREAD

**Issue by erikgollot** [cqfn/eo#82]
If you add the association feature, we can expect to manage inheritance between associations. ..like in UML.

**Comment by alexpanov** [comment]
@erikgollot Please elaborate. Code suggestions would be perfect. Thanks!

**Comment by erikgollot** [comment]
More insight...

                                          MyAssociation
            ClassA 1,1 myRoleA---------------------myRoleB 0,* ClassB   
			                                    |
	ClassAChild1     ClassAChild2      |            ClassBChild1      ClassBChild2		
         |                                                   |                  |
         --------------------------------------------------
		                     MyAssociationChild
							 
MyAssociationChild inherits from MyAssociation, meaning that into the myRoleB of a ClassAChild, you can only put ClassBChild objects.

You can expect to have the following code

```
class ClassAChild1{

@Association(name="MyAssociationChild", lower=1,upper=1,parent="MyAssociation")
public Collection<ClassBChild1> myRoleB; 

}

class ClassBChild1 {

@Association(name="MyAssociationChild", lower=1,upper=1,parent="MyAssociation")
public ClassAChild1 myRoleA;

}

**or**

class ClassAChild1 {

@Association(name="MyAssociation", role.my.lower=0,role.my.upper=-1,role.other.lower=1,role.other.upper=1,other=ClassBChild1.myRoleA,parent="MyAssociation")
public Collection<ClassBChild1> myRoleB;

}

class ClassBChild1 {

public ClassAChild1 myRoleA;

}
```

Hope it's more clear  ?

**Comment by alexpanov** [comment]
@erikgollot 
What sort of constraints and/or functionality would that introduce? I do not understand the outcome.
Can you please rewrite the code snippets to a real world abstraction like books or cars? I think it is quite hard to grasp a new concept which you apparently are trying to explain when the names are meaningless like `ClassAChild1`.

**Comment by erikgollot** [comment]
This issue is linked to issue 81

**Comment by yegor256** [comment]
@erikgollot it looks rather difficult to understand for me too... Please elaborate with a simpler example.

**Comment by erikgollot** [comment]
ok, take the sample of #81 an Animal has Pet Houses. Now, you've Cat and Dog classes that are children of Animal. You want to restrict the Relationship between Cat and Pet House and between Dog and Pet House. You want to say a Dog can only have Niches and a Cat  can only have Baskets.

You says : Dog--1-resident--------->0..N--house-Niche
and Cat--1-resident---------->0..N--house-Basket

Both Relationship inherits from the Relationship between Animal and Pet House

**Comment by yegor256** [comment]
@erikgollot I believe it's not relevant anymore, since we don't have types in EO
