### ISSUE TITLE
Delegate keyword & feature

### ISSUE THREAD

**Issue by erikgollot** [cqfn/eo#83]
In many pattern we use delegation and we're obliged to implement unnecessary methods. It would be nice to have a 'delegate' keyword to automatically delegates...

**Comment by mdbs99** [comment]
See #6 about delegation.

**Comment by yegor256** [comment]
@erikgollot indeed, we need it, but I think you're talking about "decorating", right? https://en.wikipedia.org/wiki/Decorator_pattern

**Comment by erikgollot** [comment]
yes

**Comment by yegor256** [comment]
@erikgollot I made the required changes and submitted PR #114

**Comment by yegor256** [comment]
@mdbs99 delegation and decoration is built-in EO now
