### ISSUE TITLE
Remove Joiner dependency

### ISSUE THREAD

**Issue by fabriciofx** [cqfn/eo#93]
Let's remove the `Joiner` dependency, because we can use JDK's `String.join()` to do same thing.

**Comment by yegor256** [comment]
@fabriciofx how is it going?

**Comment by fabriciofx** [comment]
@yegor256 Could you help me [here](https://github.com/yegor256/eo/pull/94#issuecomment-271011781)?

**Comment by fabriciofx** [comment]
@yegor256 I figured out now what should be done. Could you check if it is correct now?

**Comment by yegor256** [comment]
@fabriciofx can you please submit a new pull request? The previous one is gone, I suppose

**Comment by yegor256** [comment]
@fabriciofx I believe it's not valid anymore
